add example task topic
SUSE/doc-modular pull request #1
Opened 2021-07-29 14:54 UTC by taroth21

First draft of a task topic type.

Open issues:

- metadata?
- article uses no profiling ATM
- productname entity not set yet (on purpose)
- no real links in 'Related topics'
- 'Troubleshooting' section still empty
- not verified for different product versions yet (default base modules etc.)

2021-07-29 15:38 UTC, fsundermeyer requested changes
Looks good! Thanks a lot!

2021-07-29 15:38 UTC, fsundermeyer commented on xml/task-register-product-after-installation.xml
> +    <para>If you want to register your product at an &smt; server, the &rmt; server needs to be
```suggestion
    <para>If you want to register your product at an &rmt; server, the &rmt; server needs to be
```

2021-07-29 15:38 UTC, fsundermeyer commented on xml/task-register-product-after-installation.xml
> +     If you want to register your product at the &scc; center, your system needs to be connected to the Internet.
```suggestion
     If you want to register your product at the &scc;, your system needs to be connected to the Internet.
```

2021-07-29 15:38 UTC, fsundermeyer commented on xml/task-register-product-after-installation.xml
> +   <title>Registering your product from command line after the installation</title>
```suggestion
   <title>Registering your product from command the line after the installation</title>
```

2021-07-29 15:38 UTC, fsundermeyer commented on xml/task-register-product-after-installation.xml
> +  <para>To register the base product plus modules and extensions from the command line, use
```suggestion
  <para>To register the base product plus its default modules and extensions from the command line, use
```

2021-07-29 15:38 UTC, fsundermeyer commented on xml/task-register-product-after-installation.xml
> +  to keep your product up-to-date have been added to your system.
The system is now also eligible for support.

2021-07-29 15:38 UTC, fsundermeyer commented on xml/task-register-product-after-installation.xml
> + </itemizedlist>
```suggestion
   <listitem>
    <para>Managing modules and extensions in a running system</para>
   </listitem>
  </itemizedlist>

2021-07-29 15:38 UTC, fsundermeyer commented on xml/task-register-product-after-installation.xml
> + <para></para>
Possible causes of a failed registration:
* faulty internet/network connection
* wrong email address

FAQ:
I have added a module/extension and it asks for a registration key

2021-07-30 11:08 UTC, taroth21 commented on xml/task-register-product-after-installation.xml
> +     If you want to register your product at the &scc; center, your system needs to be connected to the Internet.
Nope, I double-checked: `&scc;` already resolves to 'SUSE Customer Center', so rejecting this suggestion.

2021-07-30 11:16 UTC, taroth21 commented on xml/task-register-product-after-installation.xml
> +  to keep your product up-to-date have been added to your system.
```suggestion
  to keep your product up-to-date have been added to your system. The system is now eligible for support. 
```

2021-08-03 13:47 UTC, fsundermeyer approved these changes
LGTM

2021-08-03 16:28 UTC, taroth21 commented
Thanks for reviewing and approving, Frank! As most of the open issues listed in the PR description have been addressed meanwhile, I will merge it now.

2021-08-03 16:29 UTC, merged