NTP configuration, YaST and config file.
SUSE/doc-modular pull request #10
Opened 2021-08-23 10:54 UTC by tbazant

2021-08-23 18:27 UTC, lproven requested changes
Mostly just small stuff. The bigger one I will try to do as a separate commit.

2021-08-23 18:27 UTC, lproven commented on xml/task-configure-ntp.xml
> +     or local network is reachable.
```suggestion
     The system's networking is configured so that a time server is reachable
     on an external or local network.
```

2021-08-23 18:27 UTC, lproven commented on xml/task-configure-ntp.xml
> +     network offers NTP servers via DHCP.
```suggestion
     NTP servers. If your internal network offers NTP servers via DHCP,
     pick <guimenu>Dynamic</guimenu>.
```

2021-08-23 18:27 UTC, lproven commented on xml/task-configure-ntp.xml
> +   &productname; uses &chrony; as an implementation of the &ntp; protocol.
I think this entity [productname] may not be set for a standalone article; it is showing up just as PRODUCT in the rendered output.

2021-08-23 18:27 UTC, lproven commented on xml/task-configure-ntp.xml
> +   </itemizedlist>
I think the un-emphasised driver names, coupled with hyphens, looks less than ideal.

I suggest a [variablelist], with the driver as each [term] and then 2 [para]s, one with the explanation, one with the example.

2021-08-23 18:27 UTC, lproven commented on xml/task-configure-ntp.xml
> +   You can use &chronyc; to change the behavior of &chronyd; at runtime. It
```suggestion
   You can use the <command>&chronyc;</command> to change the behavior of &chronyd; at runtime. It
```

2021-08-23 18:27 UTC, lproven commented on xml/task-configure-ntp.xml
> +     &chronyc; when disconnecting the network link.
```suggestion
     a response. This option avoids the need to run the <command>offline</command>
     command from &chronyc; when disconnecting the network link.
```

2021-08-23 18:27 UTC, lproven commented on xml/task-configure-ntp.xml
> +     up to a minute until the network connectivity has been established.
```suggestion
     up to a minute until the network connectivity is established.
```

2021-08-23 18:37 UTC, lproven commented on xml/task-configure-ntp.xml
> +   </itemizedlist>
I have put a proposed varlist in:
https://github.com/SUSE/doc-modular/pull/11

2021-08-24 11:25 UTC, tbazant commented on xml/task-configure-ntp.xml
> +   &productname; uses &chrony; as an implementation of the &ntp; protocol.
i know but we're supposed to use it for now

2021-08-24 11:28 UTC, tbazant commented on xml/task-configure-ntp.xml
> +   </itemizedlist>
ok, will merge that separately

2021-08-24 11:29 UTC, tbazant commented on xml/task-configure-ntp.xml
> +   You can use the <command>&chronyc;</command> to change the behavior of &chronyd; at runtime. It
```suggestion
   You can use the <command>&chronyc;</command> command to change the behavior of &chronyd; at runtime. It
```

2021-08-24 14:04 UTC, lproven approved these changes

2021-08-30 08:04 UTC, tbazant reviewed
lproven's variable list LG

2021-08-30 08:04 UTC, tbazant commented on xml/task-configure-ntp.xml
> +       NTP shared memory driver. For example:
```suggestion
       &ntp; shared memory driver. For example:
```

2021-09-15 16:56 UTC, lproven requested changes

2021-09-15 16:56 UTC, lproven commented on xml/task-configure-ntp.xml
> +    The <literal>server</literal> directive tells &chronyd; to use specific
```suggestion
    The <literal>server</literal> directive tells &chronyd; to use a specific
```

2021-09-15 16:56 UTC, lproven commented on xml/task-configure-ntp.xml
> +    access However, the host <literal>1.2.3.4</literal> is allowed access.
```suggestion
    access. However, the host <literal>1.2.3.4</literal> is allowed access.
```

2021-09-16 13:20 UTC, merged