Cheat sheet, assembly changes and infrastructure changes
SUSE/doc-modular pull request #108
Opened 2023-03-22 17:08 UTC by janajaeger

After our Smart Docs template training, a few things come to our minds:

- snippet handling needs to be added (dir, example, assembly reference)
- trans and bugtracker meta tags aren't supported yet
- we need a cheat sheet for the writers ...

2023-03-29 13:57 UTC, tomschr requested changes
@janajaeger Some minor issues. :slightly_smiling_face:

2023-03-29 13:57 UTC, tomschr commented on templates/articles/assembly.asm.xml
> +        </meta>
I think, you can format it more nicely:

```suggestion
        <meta name="bugtracker">
          <phrase role="url">https://bugzilla.suse.com/enter_bug.cgi</phrase>
          <phrase role="component">Non-product-specific documentation</phrase>
          <phrase role="product">Smart Docs</phrase>
          <phrase role="assignee">assignee@suse.com</phrase>
        </meta>
```

2023-03-29 13:57 UTC, tomschr commented on templates/articles/assembly.asm.xml
> +      </dm:editurl>
Linebreaks are... evil. :wink: 

```suggestion
        <dm:editurl>https://github.com/SUSE/doc-modular/tree/main/articles/</dm:editurl>
```

2023-03-29 13:57 UTC, tomschr commented on templates/common/legal.xml
If you move the snippet dir, this needs to be adapted.

2023-03-29 13:57 UTC, tomschr commented on templates/snippets/snippet_warning.xml
Same here.

2023-03-30 09:24 UTC, janajaeger commented on snippets/snippet_warning.xml
> +<warning xml:id="foobar"
Moved the snippet itself and will remove the ID there.

2023-03-31 07:43 UTC, dariavladykina reviewed
Hi, just minor nits detected. Thanks!

2023-03-31 07:43 UTC, dariavladykina commented on templates/snippets/snippet_warning.xml
> +  <title>Foobar</titel>
```suggestion
  <title>Foobar</title>
```

2023-03-31 07:43 UTC, dariavladykina commented on templates/articles/assembly.asm.xml
>        <meta name="social-descr">ultra short description for social media, max 55 chars</meta>
```suggestion
      <meta name="social-descr">ultrashort description for social media, max 55 chars</meta>
```

2023-03-31 11:59 UTC, merged