Jufa/sudo new structure-testing
SUSE/doc-modular pull request #121
Opened 2023-04-04 14:24 UTC by Amrita42

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

2023-05-04 12:45 UTC, tomschr requested changes
@jfaltenbacher / @janajaeger Sorry, I know I'm a bit early to the party, :wink: but I tried to consolidate just the metadata. But it seems I got dragged into smaller tag issues. Left some suggestions. Just ignore those, if you are already aware of it.

2023-05-04 12:45 UTC, tomschr commented on articles/sudo-run-commands-as-superuser.asm.xml
> +        <productname version="ALP">&sles;</productname>
That looks fishy to me. :wink: I think, "ALP" should go _inside_ the tag:

```suggestion
        <productname version="1">ALP</productname>
```

Taken from 
https://github.com/SUSE/doc-modular/blob/main/articles/ALP.asm.xml#L164

2023-05-04 12:45 UTC, tomschr commented on articles/sudo-run-commands-as-superuser.asm.xml
> +  <structure renderas="article" xml:id="sudo-run-commands-as-superuser">
Add the language here:

```suggestion
  <structure renderas="article" xml:id="sudo-run-commands-as-superuser" xml:lang="en">
```

2023-05-04 12:45 UTC, tomschr commented on articles/sudo-run-commands-as-superuser.asm.xml
Inside the `<description>` tag, no entities are allowed. Sorry.

You don't need to add here the exact title. This tag will never be used for the output. You could also completely remove it and the assembly would still be correct.

The only use case that this tag serves is to be used as a hint for _you_ as a writer.

2023-05-04 12:45 UTC, tomschr commented on references/sudo-commands.xml
> +    <title></title>
Empty title?

2023-05-04 12:45 UTC, tomschr commented on references/sudo-commands.xml
> +            <command>/etc/</command> directory. To create it, run <command>sudo
Wrong tag:

```suggestion
            <filename>/etc/</filename> directory. To create it, run <command>sudo
```

2023-05-04 12:45 UTC, tomschr commented on references/sudo-commands.xml
> +</screen>
Don't indent screens. Always start at the first column. You will only waste valuable space. :wink: Same for the other screens.

2023-05-04 12:45 UTC, tomschr commented on references/sudo-commands.xml
> +            <command>YYYY-MM-DD</command> format for <command>user-1</command>
Wrong tag:

```suggestion
            <literal>YYYY-MM-DD</literal> format for <command>user-1</command>
```

2023-05-04 12:45 UTC, tomschr commented on references/sudo-commands.xml
> +            <command>test</command> to <command>user-1</command>, run the
Wrong tags:

```suggestion
            the <filename>/home/test/user-1-files</filename> directory from
            <filename>test</filename> to <filename>user-1</filename>, run the
```

2023-05-04 12:45 UTC, tomschr commented on references/sudo-commands.xml
> +            <command>user-1</command>, run the following command:
Wrong tags:

```suggestion
            the <filename>/home/test/user-1-files/</filename> directory as
            <filename>user-1</filename>, run the following command:
```

2023-05-04 12:45 UTC, tomschr commented on references/sudo-commands.xml
> +            <command>.bash_profile</command> files.
Wrong tags:

```suggestion
            startup scripts such as <filename>.profile</filename> and
            <filename>.bash_profile</filename> files.
```

2023-05-04 12:45 UTC, tomschr commented on references/sudo-edit-configuration.xml
> +    <screen>&prompt.sudo; visudo -f /etc/sudoers.d/01_test
Same:

```suggestion
    <screen>&prompt.sudo;visudo -f /etc/sudoers.d/01_test
```

2023-05-04 12:45 UTC, tomschr commented on references/sudo-edit-configuration.xml
> +    <screen>&prompt.sudo; visudo -c
Same:

```suggestion
    <screen>&prompt.sudo;visudo -c
```

2023-05-04 12:45 UTC, tomschr commented on tasks/sudo-manage-wheel-group.xml
> +<screen>sudo usermod -a -G wheel <replaceable>USERNAME</replaceable></screen>
Shouldn't there be a `&prompt.user;`?

```suggestion
<screen>&prompt.sudo;usermod -a -G wheel <replaceable>USERNAME</replaceable></screen>
```

2023-05-04 12:45 UTC, tomschr commented on tasks/sudo-manage-wheel-group.xml
> +<screen>sudo visudo -f /etc/sudoers.d/NAME</screen>
Same:

```suggestion
<screen>&prompt.sudo;visudo -f /etc/sudoers.d/NAME</screen>
```

2023-05-05 08:02 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +        <productname version="ALP">&sles;</productname>
here I am unsure how it should be, maybe Jana can tell

2023-05-05 08:05 UTC, jfaltenbacher commented on references/sudo-commands.xml
> +    <title></title>
invited @sounix000 to the party :)

2023-05-05 08:06 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +<screen>sudo usermod -a -G wheel <replaceable>USERNAME</replaceable></screen>
changed as suggested

2023-05-05 08:06 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +<screen>sudo visudo -f /etc/sudoers.d/NAME</screen>
this part is deleted now

2023-05-05 11:21 UTC, sounix000 commented on references/sudo-commands.xml
> +    <title></title>
I don't want any title or subtitle here, as it is unnecessary. However, on removing the title element, there is an error. Hence the workaround. I will remove it if there exists a better solution (which I am quite sure, exists).

2023-05-05 11:29 UTC, janajaeger commented on articles/sudo-run-commands-as-superuser.asm.xml
> +        <productname version="ALP">&sles;</productname>
I just copied what Frank had in his doc? Frankly, I don't know.

2023-05-05 11:30 UTC, janajaeger commented on articles/sudo-run-commands-as-superuser.asm.xml
> +  <structure renderas="article" xml:id="sudo-run-commands-as-superuser">
@tomschr is this another template update in disguise then?

2023-05-05 12:30 UTC, tomschr commented on articles/sudo-run-commands-as-superuser.asm.xml
> +  <structure renderas="article" xml:id="sudo-run-commands-as-superuser">
Well, the assemble.xsl stylesheet has a bug (it doesn't take into account the language). This is fixed now.

But we also need to set the language, we need to add them in a `<structure>`. It's also covered in the assembly template.

2023-05-05 12:44 UTC, janajaeger commented on concepts/difference-between-sudo-and-su.xml
> +        <meta name="maintainer" content=" Amrita " its:translate="no"/>
content actually needs to hold the full email address instead of the author's name ;)

2023-05-05 12:48 UTC, janajaeger commented on concepts/sudo-concept.xml
> +   <para>The &sudo; package is installed by default for all Linux distributions.</para>
This is a duplicate of the stuff stated earlier in the assembly itself. Also, "all Linux distros" is not appropriate here. We focus on SUSE only ;) It's absolutely true that sudo is widely used, but our scope is SUSE ;)

2023-05-05 12:49 UTC, janajaeger commented on references/sudo-commands.xml
> +    <meta name="maintainer" content="Julia Faltenbacher"/>
add email instead of full name, just as in the assembly file.

2023-05-05 14:35 UTC, sounix000 commented on references/sudo-troubleshoot.xml
> +     <option>.</option>) or with editor temporary or backup files (ending in
**Suggestion**: `, or with an editor's temporary`

2023-05-05 14:40 UTC, sounix000 commented on references/sudo-troubleshoot.xml
> +     <option>~</option>). Make sure your custom configuration files neither
I'm not sure if I understand correctly, but I guess the restrictions are placed only on the file names. In that case: 
`Make sure the names of your custom configuration files`.

2023-05-05 14:42 UTC, sounix000 commented on references/sudo-troubleshoot.xml
> +    <title>Custom directives clash</title>
**Suggestion**: `conflict` instead of `clash` in the title. Somehow, clash doesn't feel right, and I haven't seen it being used much in technical contexts.

2023-05-05 14:42 UTC, sounix000 commented on references/sudo-troubleshoot.xml
> +
Remove blank sentence.

2023-05-05 14:44 UTC, sounix000 commented on references/sudo-troubleshoot.xml
> +      <filename>/etc/sudoers.de/</filename> do not work, check the order
`/etc/sudoers.de/` => `/etc/sudoers.d/`. Remove the extra `e`.

2023-05-05 14:52 UTC, sounix000 commented on references/sudo-troubleshoot.xml
> +      to check for errors and then fix them using <command>visudo</command>.
Consider giving an example for errors and the fixes applicable.

2023-05-05 14:52 UTC, sounix000 commented on references/sudo-troubleshoot.xml
> +      &root; pasword to start a root shell. Run <command>visudo -c</command>
Correct type `pasword`.

2023-05-05 14:57 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +        The integrity of your system's &sudo; configuration is paramount.
**Suggested**: Consider replacing `paramount` with something simpler. For example, `very important`.

2023-05-05 14:59 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +        the administrator to edit the &sudo; configuration.</para>
`the adminstrator` => `an administrator`. I think `the` is not the appropriate article here.

2023-05-05 15:00 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +
Remove blank line.

2023-05-05 15:08 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +  <filename>/etc/sudoers.d</filename>. These are pulled in by default by a
For directories such as `/etc/sudoers.d`, consider ending with `/` or write it as `the /etc/sudoers.d directory`.

2023-05-05 15:09 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +
Remove blank line.

2023-05-05 15:14 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +
Remove blank line.

2023-05-05 15:15 UTC, janajaeger commented on references/sudo-edit-configuration.xml
> +        the administrator to edit the &sudo; configuration.</para>
Thanks, applied!

2023-05-05 15:16 UTC, janajaeger commented on references/sudo-edit-configuration.xml
> +
Thanks, applied!

2023-05-05 15:17 UTC, janajaeger commented on references/sudo-edit-configuration.xml
> +  <filename>/etc/sudoers.d</filename>. These are pulled in by default by a
Thanks, applied!

2023-05-05 15:19 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +    <screen>&prompt.sudo; EDITOR=/usr/bin/nano visudo -f /etc/sudoers.d/<replaceable>NAME</replaceable></screen>
Remove the whitespace character after `&prompt.sudo`. Also, consider the following version for better readability of the doc source:
```
<screen>
&prompt.sudo;<command>EDITOR=/usr/bin/nano visudo -f /etc/sudoers.d/<replaceable>NAME</replaceable></command>
</screen>
```

2023-05-05 15:21 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +
Remove blank line.

2023-05-05 15:22 UTC, janajaeger commented on references/sudo-edit-configuration.xml
> +    <screen>&prompt.sudo; EDITOR=/usr/bin/nano visudo -f /etc/sudoers.d/<replaceable>NAME</replaceable></screen>
Done.

2023-05-05 15:22 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +      When naming your custom configuration files, stick to the following
Consider changing `stick to the` to something more like `use the` or `remember the`.

2023-05-05 15:24 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +      general rules:
I guess this should be in the previous line?

2023-05-05 15:26 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +            rather than the system adminstrator and ignores them. The same
Typo in `administrator`.

2023-05-05 15:28 UTC, janajaeger commented on references/sudo-troubleshoot.xml
> +     <option>~</option>). Make sure your custom configuration files neither
Done.

2023-05-05 15:28 UTC, janajaeger commented on references/sudo-troubleshoot.xml
> +    <title>Custom directives clash</title>
Done

2023-05-05 15:29 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +          </para>
Consider replacing `trumps` without something like `sudo processes the last read version.`

2023-05-05 15:29 UTC, janajaeger commented on references/sudo-troubleshoot.xml
> +
Done

2023-05-05 15:30 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +          Apply the changes and exit. This results in a malfuntioning or broken
Typo in `malfuntioning`.

2023-05-05 15:31 UTC, janajaeger commented on references/sudo-troubleshoot.xml
> +      &root; pasword to start a root shell. Run <command>visudo -c</command>
Done

2023-05-05 15:32 UTC, sounix000 commented on references/sudo-edit-configuration.xml
> +      behaviour of &sudo; which can simply be caused by directives being
`behaviour` => British English, eh?

2023-05-05 15:33 UTC, janajaeger commented on references/sudo-troubleshoot.xml
> +      to check for errors and then fix them using <command>visudo</command>.
Good point. Added a FIXME to add later when I am done with the config topic.

2023-05-05 16:00 UTC, janajaeger commented on references/sudo-edit-configuration.xml
> +
done

2023-05-05 16:04 UTC, janajaeger commented on references/sudo-edit-configuration.xml
> +      behaviour of &sudo; which can simply be caused by directives being
oops ...

2023-05-05 16:33 UTC, janajaeger commented on references/sudo-edit-configuration.xml
> +    Settings in the custom configuration files under
I can't for the life of me find a better wording. sudo isn't made for casual reading, anyway ;)

2023-05-08 06:58 UTC, Amrita42 commented on concepts/sudo-concept.xml
> +   <para>The &sudo; package is installed by default for all Linux distributions.</para>
Yes , correct, I retained some of the existing content but let me re-visit again and also will add SUSE to the distros

2023-05-08 09:46 UTC, Amrita42 commented on concepts/difference-between-sudo-and-su.xml
> +        <meta name="maintainer" content=" Amrita " its:translate="no"/>
done for both files :) Thanks

2023-05-09 14:41 UTC, janajaeger commented on articles/sudo-run-commands-as-superuser.asm.xml
> +        </para>
Where is the varlist proposed by Dima with the WHAT, WHY, EFFORT, GOAL thing? We agreed that all of our articles should contain this type of orientation.

2023-05-09 14:41 UTC, janajaeger commented on articles/sudo-run-commands-as-superuser.asm.xml
> +        <para>
This is sort of non-informational. Either don't have it at all or provide more than a mere description of the articles structure.

2023-05-09 14:41 UTC, janajaeger commented on articles/sudo-run-commands-as-superuser.asm.xml
> +                    &rootuser; or sudo privileges. Add reference of how to
What's the meaning of the "add link" part?

2023-05-09 15:05 UTC, janajaeger commented on concepts/difference-between-sudo-and-su.xml
> +       <para>You are switching to root, and you need the root password. &sudo; is the safest way to elevate privileges.
This is not a good example. After you have run sudo su -, you stay root. That is probably not what you wanted to highlight here. su - or sudo su - basically result in the same: a permanent root prompt.

2023-05-09 15:32 UTC, janajaeger commented on references/sudo-commands.xml
> +  <title>Common &sudo; commands</title>
Please ditch the duplicated title ;) The "common sudo commands" title is actually a bit confusing and misleading. I'd suggest you promote the title in the info tag to your main title. You don't have to have a separate title in the info tag, so why not ditch it?

2023-05-09 15:32 UTC, janajaeger commented on references/sudo-commands.xml
> +<screen>
Don't keep them separate. Use one screen for the entire sequence, I'd say.

2023-05-09 15:32 UTC, janajaeger commented on references/sudo-commands.xml
> +            <command>sudo</command> before the command. If you are using
Lose the "if you are using zypper as your package manager". zypper is still the default and we probably shouldn't indirectly make people aware of alternative solutions ;) Just a "political" issue here.

2023-05-09 15:32 UTC, janajaeger commented on references/sudo-commands.xml
> +          <para>
Again, waving the "political issue" flag. Do we have to use software provided by MS as an example?

2023-05-09 15:32 UTC, janajaeger commented on references/sudo-commands.xml
> +&prompt.sudo;<command>usermod -e 2023-04-30 user-1</command>
user-1? Check with Toms and/or Daria. I bet we have a default user to be used in docs.

2023-05-10 06:44 UTC, tomschr commented on concepts/sudo-concept.xml
> +      &sudo; is an abbreviation for “super user do”.  It is a Linux command that you can use to execute programs as a &rootuser; user.
Yes, `<quote>`. :wink:

2023-05-10 06:49 UTC, tomschr commented on references/sudo-commands.xml
> +&prompt.sudo;<command>usermod -e 2023-04-30 user-1</command>
We have plenty of users to use. You can add one of the following entities (full names in parenthesis, append `full` to the entity name):

* `exampleuser` => tux (Tux Linux)
* `exampleuserII` => wilber (Wilber Fox)
* `exampleuserIII` => suzanne (Suzanne Geeko)

2023-05-10 07:05 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +        </para>
yep, but that would be the very last discipline I'd say. We can only give this information when all content is ready, no?

2023-05-10 07:07 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +        <para>
same as above. We can give good description here only if all content is there

2023-05-10 07:12 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +                    &rootuser; or sudo privileges. Add reference of how to
sorry, this should have been a comment. Might be good to point the reader to the section where these privileges are explained and how to gain.

2023-05-10 07:29 UTC, Amrita42 commented on articles/sudo-run-commands-as-superuser.asm.xml
> +        </para>
yes correct, it is subject to change based on our final content. For now , kept it as a placeholder

2023-05-10 07:39 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +                    &rootuser; or sudo privileges. Add reference of how to
this is a 'community' file I'd say. Let's discuss later in our status call

2023-05-10 15:36 UTC, janajaeger commented
This should never have been closed. Reopening!

2023-05-10 15:38 UTC, janajaeger commented on articles/sudo-run-commands-as-superuser.asm.xml
Fixed and committed

2023-05-11 14:19 UTC, Amrita42 commented on concepts/sudo-concept.xml
> +      <command>su</command> are not logged.
Removing this sentence as it creates confusion, it is there in original content for both su and sudo

2023-05-11 14:21 UTC, Amrita42 commented on concepts/difference-between-sudo-and-su.xml
> +            If you want to execute a command as a &rootuser; user, you must always use the sudo command.
yeah , makes sense , will modify

2023-05-11 14:46 UTC, Amrita42 commented on tasks/sudo-manage-wheel-group.xml
> +        Log out and log in again from the Terminal or close the current session
I think it should be terminal since its not in the title

2023-05-12 06:51 UTC, Amrita42 commented on references/sudo-user-authorization.xml
> +        Before you start editing &sudo; configuration files or creating your
I would suggest rephrasing as :  Learn about the basic sudoers configuration settings before you start editing or creating your own sudo configuration files.

2023-05-12 07:14 UTC, Amrita42 commented on references/sudo-user-authorization.xml
> +    The <filename>sudoers</filename> configuration files contain two types of
I am not sure if its only two option types , as per https://www.sudo.ws/docs/man/1.8.13/sudoers.man/ , I see the following statement:
_Parameters may be flags, integer values, strings, or lists._

2023-05-12 09:30 UTC, Amrita42 commented on references/sudo-user-authorization.xml
> +              This flag controls whether the invoking user is required to enter
To me , this is a little confusing . 
**Suggestion:** 
If set, sudo prompts for the password of user specified in the -u option.

2023-05-12 09:47 UTC, Amrita42 commented on references/sudo-user-authorization.xml
> +              variables listed in <literal>env_keep</literal> are imported from
I am not sure if its only env_keep, I found this ref >> _Any variables in the caller's environment that match
    the env_keep and env_check lists are then added,_   https://news.ycombinator.com/item?id=5306099. please take a look.

2023-05-12 10:03 UTC, Amrita42 commented on references/sudo-user-authorization.xml
> +          A list of commands.
Cmnd_Alias — A Cmnd_List is a list of one or more command names, directories, and other aliases.  ref : https://www.sudo.ws/docs/man/1.7.10/sudoers.man/

2023-05-12 13:17 UTC, janajaeger commented on references/sudo-user-authorization.xml
> +    The <filename>sudoers</filename> configuration files contain two types of
Actually both is true. The "can contain any value" covers integers, list or strings. Leaving as is in order to not overcomplicate things ;)

2023-05-12 13:17 UTC, janajaeger commented on references/sudo-user-authorization.xml
> +        Before you start editing &sudo; configuration files or creating your
Good one. Will do!

2023-05-12 13:27 UTC, janajaeger commented on references/sudo-user-authorization.xml
> +              This flag controls whether the invoking user is required to enter
Nice catch. This is definitely less confusing.

2023-05-12 13:43 UTC, janajaeger commented on references/sudo-user-authorization.xml
> +              variables listed in <literal>env_keep</literal> are imported from
Yup. That's taken from the man page. I'll try to make sense of it.

2023-05-12 14:28 UTC, janajaeger commented on references/sudo-user-authorization.xml
> +              variables listed in <literal>env_keep</literal> are imported from
Checked it against our default config. Not sure whether we encourage the use of env_check. Adding a comment in the code and adding env_check to the list of Otto questions. What's currently stated here is not wrong, but it might just be only one part of the whole thing as you stated.

2023-05-12 16:06 UTC, janajaeger commented on references/sudo-user-authorization.xml
> +          A list of commands.
Fixed.

2023-05-15 06:47 UTC, Amrita42 commented on articles/sudo-run-commands-as-superuser.asm.xml
> +          On &productname; certain commands cannot be executed by the normal
**Suggestion:** 
Certain commands  on SUSE Linux cannot be executed by the normal user but require administrator privileges.

2023-05-15 07:05 UTC, Amrita42 commented on tasks/sudo-change-pw-timeout.xml
> +    certain period. Once it is expired, the user is prompted for the password
Do we want to specify the default timeout period for SUSE linux distros ?

2023-05-15 07:21 UTC, Amrita42 commented on tasks/sudo-change-pw-timeout.xml
> +    To extend or shorten the time-out when executing commands that require
I see instances of time-out and timeout in the content, please check , I think it is time-out when we use in the content, not part of code.

2023-05-15 07:36 UTC, Amrita42 commented on tasks/sudo-manage-wheel-group.xml
> +      full administrator privileges, as for example the privileges for
```suggestion
      full administrator privileges, as, for example the privileges for
```

2023-05-15 07:38 UTC, Amrita42 commented on tasks/sudo-manage-wheel-group.xml
> +      example, create a dedicated group for all users that are managing and
_example, create a dedicated group for all users that are managing and installing_ >> suggest " installing and managing...."

2023-05-15 09:12 UTC, Amrita42 commented on tasks/sudo-run-command.xml
> +    following example showcases how to execute a command prefaced with &sudo;.
```suggestion
    following example shows how to execute a command prefaced with &sudo;.
```

2023-05-15 09:16 UTC, Amrita42 commented on tasks/sudo-start-shell-as-root.xml
> +          enter your user password. With method it is not needed to share the
```suggestion
          enter your user password. With this method it is not needed to share the
```

2023-05-15 09:18 UTC, Amrita42 commented on tasks/sudo-start-shell-as-root.xml
> +      password again. When closing the shell, also this environment is
"This environment is terminated when you close the shell and you have to enter .......  "

2023-05-15 09:20 UTC, Amrita42 commented on tasks/sudo-start-shell-as-root.xml
> +      Which shell is opened is specified by the <envar>SHELL</envar>
The <envar>SHELL</envar> environment variable or the user's default shell specifies which shell opens.  [used active tense]

2023-05-15 09:24 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +        </para>
varlist and content added

2023-05-15 09:24 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +                    &rootuser; or sudo privileges. Add reference of how to
link added

2023-05-15 09:26 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +        Log out and log in again from the Terminal or close the current session
fixed as suggested

2023-05-15 09:29 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +          On &productname; certain commands cannot be executed by the normal
changed as suggested

2023-05-15 09:34 UTC, jfaltenbacher commented on tasks/sudo-change-pw-timeout.xml
> +    To extend or shorten the time-out when executing commands that require
changed as suggested

2023-05-15 09:35 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +    available on all Linux systems by default. The group is managed in the
changed as suggested

2023-05-15 09:36 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +      Carefully think of adding users to a user group as not all users need
changed as suggested

2023-05-15 09:37 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +      full administrator privileges, as for example the privileges for
changed as suggested

2023-05-15 09:38 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +      example, create a dedicated group for all users that are managing and
changes as suggested

2023-05-15 09:38 UTC, jfaltenbacher commented on tasks/sudo-run-command.xml
> +    following example showcases how to execute a command prefaced with &sudo;.
changed as suggested

2023-05-15 09:39 UTC, jfaltenbacher commented on tasks/sudo-start-shell-as-root.xml
> +          enter your user password. With method it is not needed to share the
changed as suggested

2023-05-15 09:41 UTC, jfaltenbacher commented on tasks/sudo-start-shell-as-root.xml
> +      Which shell is opened is specified by the <envar>SHELL</envar>
changed as suggested

2023-05-15 13:17 UTC, janajaeger reviewed
Found a few minor issues. Mainly to do with spelling of timeout/time-out and the default settings ;)

2023-05-15 13:17 UTC, janajaeger commented on tasks/sudo-change-pw-timeout.xml
> +    <title>Changing the &sudo; password prompt time-out</title>
time-out or timeout?

2023-05-15 13:17 UTC, janajaeger commented on tasks/sudo-change-pw-timeout.xml
> +<screen>sudo visudo --f=/etc/sudoers.d/timestamp_timeout</screen>
Check my section on custom configs. It might be useful to add some numbering here to make sure the configs are applied in the correct order and don't cancel themselves out.

2023-05-15 13:17 UTC, janajaeger commented on tasks/sudo-change-pw-timeout.xml
> +<screen>timestamp_timeout=5</screen>
To set 5 minutes, you don't need to do anything ... that's the current default. I suggest you chose another figure here ;)

2023-05-15 13:46 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +      full administrator privileges, as for example the privileges for
changed as suggested

2023-05-15 13:48 UTC, jfaltenbacher commented on tasks/sudo-start-shell-as-root.xml
> +      password again. When closing the shell, also this environment is
changed as suggested

2023-05-15 13:52 UTC, jfaltenbacher commented on tasks/sudo-change-pw-timeout.xml
> +<screen>timestamp_timeout=5</screen>
some people say 15 min is the default... ask Otto?

2023-05-15 14:17 UTC, janajaeger reviewed
Wording issues ahead. Sorry for being such a PITA

2023-05-15 14:17 UTC, janajaeger commented on tasks/sudo-manage-wheel-group.xml
> +    To make the default rule more restrictive, comment out or remove the allow-
The wording is a bit confusing here. I don't quite get which "default rule" is referred to :(

2023-05-15 14:17 UTC, janajaeger commented on tasks/sudo-manage-wheel-group.xml
> +            <title>Dangerous rule in <filename>sudoers</filename></title>
IMHO a warning should be self-explanatory. "Do not skip this step" doesn't  explain much. Include the dangerous rule and make it clearer why it is dangerous?

2023-05-15 14:42 UTC, janajaeger reviewed
Minor nitpicks

2023-05-15 14:42 UTC, janajaeger commented on tasks/sudo-run-command.xml
> +    security reasons, it is not recommended to log in as &rootuser;. A safer
"For security reasons" says everything and nothing at the same time. Is there a more precise way of putting this?

2023-05-15 14:42 UTC, janajaeger commented on tasks/sudo-run-command.xml
> +    &sudo; to gain &rootUser; privileges.
&rootUser; ?

2023-05-16 06:23 UTC, jfaltenbacher commented on tasks/sudo-change-pw-timeout.xml
> +    <title>Changing the &sudo; password prompt time-out</title>
time-out (checked back with Daria)

2023-05-16 08:26 UTC, jfaltenbacher commented on tasks/sudo-change-pw-timeout.xml
> +<screen>timestamp_timeout=5</screen>
changed to 3 min

2023-05-16 08:26 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +    on all Linux systems by default. The group is managed in the
all Linux

2023-05-16 08:33 UTC, jfaltenbacher commented on tasks/sudo-run-command.xml
> +    &sudo; to gain &rootUser; privileges.
fixed

2023-05-16 08:36 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +    the appropriate line in <filename>/etc/sudoers</filename> and comment out
part was deleted a while ago

2023-05-16 08:36 UTC, jfaltenbacher commented on tasks/sudo-manage-wheel-group.xml
> +    Depending on whether you want users to re-enter their passwords, uncomment
part was deleted a while ago

2023-05-16 09:06 UTC, jfaltenbacher commented on tasks/sudo-run-command.xml
> +    security reasons, it is not recommended to log in as &rootuser;. A safer
rewritten

2023-05-17 05:57 UTC, Amrita42 commented on concepts/difference-between-sudo-and-su.xml
> +       <para>You are switching to root, and you need the root password. &sudo; is the safest way to elevate privileges.
yes you are right. Removing this.

2023-05-18 14:55 UTC, dariavladykina reviewed
Great job, the four of you! Please consider some suggestions and comments and LMK if they make sense. Thanks!

2023-05-18 14:55 UTC, dariavladykina commented on references/sudo-best-practices.xml
> +            &rootuser; privileges. Set a reasonable timeout instead to prevent
```suggestion
            &rootuser; privileges. Instead, set a reasonable time-out to prevent
```

2023-05-18 14:55 UTC, dariavladykina commented on references/sudo-best-practices.xml
> +        <term>Limit the &sudo; timeout</term>
```suggestion
        <term>Limit the &sudo; time-out</term>
```

2023-05-18 14:55 UTC, dariavladykina commented on references/sudo-edit-configuration.xml
> +      sure you do not lock yourself out from your system due to a broken &sudo;
```suggestion
      sure you do not lock yourself out of your system due to a broken &sudo;
```

2023-05-18 14:55 UTC, dariavladykina commented on concepts/difference-between-sudo-and-su.xml
> +            You can execute single commands as a &rootuser; or another user, based on your settings in the <filename>/etc/sudoers</filename> file.
```suggestion
            You can execute single commands as &rootuser; or another user, based on your settings in the <filename>/etc/sudoers</filename> file.
```

2023-05-18 14:55 UTC, dariavladykina reviewed
Great job, the four of you! Please consider some suggestions and comments and LMK if they make sense. Thanks!

2023-05-19 10:32 UTC, Amrita42 commented on articles/sudo-run-commands-as-superuser.asm.xml
> +      cases to run commands that require root privileges.</meta>
Good catch on the rootuser @dariavladykina

2023-05-19 11:01 UTC, Amrita42 commented on references/sudo-commands.xml
> +            <command>sudo</command>. For example, to restart the Apache web
I think it should be Apache Web Server service...... server also needs a caps  if user as a one product name .

2023-05-22 05:53 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +              login as &rootuser;, you can use the &sudo; command.
which entities exactly? might already be fixed or it is still too early for me

2023-05-22 07:34 UTC, dariavladykina commented on articles/sudo-run-commands-as-superuser.asm.xml
> +              login as &rootuser;, you can use the &sudo; command.
The `rootuser` and `sudo` entities :-)

2023-05-22 07:41 UTC, jfaltenbacher commented on articles/sudo-run-commands-as-superuser.asm.xml
> +              login as &rootuser;, you can use the &sudo; command.
in the assembly files we have the issue that entities do not work in all parts e.g. they throw a validation error in <description>.  So for some parts, we cannot use entities atm

2023-05-22 08:58 UTC, jfaltenbacher commented on references/sudo-best-practices.xml
> +            pulled in by default by a directive in
yes, that is on purpose :)

2023-05-22 08:59 UTC, jfaltenbacher commented on references/sudo-best-practices.xml
> +            misuse of the &rootuser; account by any intruder. For more
yes, that is on purpose :)

2023-05-22 09:37 UTC, merged

2023-05-22 09:37 UTC, jfaltenbacher commented
submitting final sudo smart docs article