libvirt: concept, 1st draft
SUSE/doc-modular pull request #13
Opened 2021-08-30 10:42 UTC by tbazant

2021-08-30 14:31 UTC, cjschroder requested changes
Just a few small grammar corrections.

2021-08-30 14:31 UTC, cjschroder commented on xml/concept-manage-virtual-machines-libvirt.xml
> +   manage their configuration in the following ways:
configuration > configurations

2021-08-30 14:31 UTC, cjschroder commented on xml/concept-manage-virtual-machines-libvirt.xml
> +   &libvirt; is a collection of software that provides a common API for
Spell out API on its first use

2021-08-30 14:31 UTC, cjschroder commented on xml/concept-manage-virtual-machines-libvirt.xml
> +     storage that is available to &vmguest;s.
is available > are available

2021-08-31 07:12 UTC, tbazant reviewed
included suggestions from @cjschroder

2021-08-31 07:12 UTC, tbazant commented on xml/concept-manage-virtual-machines-libvirt.xml
> +   &libvirt; is a collection of software that provides a common API for
```suggestion
   &libvirt; is a collection of software that provides a common API (Application Programming Interface) for
```

2021-08-31 07:12 UTC, tbazant commented on xml/concept-manage-virtual-machines-libvirt.xml
> +   manage their configuration in the following ways:
```suggestion
   manage their configurations in the following ways:
```

2021-08-31 07:12 UTC, tbazant commented on xml/concept-manage-virtual-machines-libvirt.xml
> +     storage that is available to &vmguest;s.
```suggestion
     storage that are available to &vmguest;s.
```

2021-08-31 07:14 UTC, merged