NTP updated
SUSE/doc-modular pull request #139
Opened 2023-04-26 10:22 UTC by tbazant

### Description

Reworked the NTP docs to align with new smartdocs layout

2023-04-27 09:52 UTC, dariavladykina reviewed
Hi, please see some suggestions here.
Thanks!

2023-04-27 09:52 UTC, dariavladykina commented on tasks/ntp-configure-configuration-file.xml
> +        multiple times to specify more than one peer.
```suggestion
        instead of a time server. System time synchronization among
        <emphasis>peers</emphasis> uses a symmetric architecture instead of the
        client/server mode invoked by <literal>server</literal> and
        <literal>pool</literal> options. You can use <literal>peer</literal>
        multiple times to specify more than one peer.
```

2023-04-27 09:52 UTC, dariavladykina commented on tasks/ntp-configure-yast.xml
> +            <term><guimenu>Only manually</guimenu></term>
```suggestion
            <term><guimenu>Only Manually</guimenu></term>
```

2023-04-27 09:52 UTC, dariavladykina commented on tasks/ntp-configure-yast.xml
> +            <term><guimenu>Now and on boot</guimenu></term>
```suggestion
            <term><guimenu>Now and on Boot</guimenu></term>
```

2023-04-27 09:52 UTC, dariavladykina commented on tasks/ntp-configure-configuration-file.xml
> +        port (123 by default) and responds to client requests.
```suggestion
        <filename>/etc/chrony.conf</filename> file. It opens the NTP server
        port (123 by default) and responds to client requests.
```

2023-05-03 13:03 UTC, lvicoun requested changes

2023-05-04 09:31 UTC, tbazant commented on concepts/ntp-time-synchronization.xml
> +    <section xml:id="ntp-operate-chronyd-service">
yep, a good idea

2023-05-04 11:22 UTC, dariavladykina approved these changes

2023-05-04 11:39 UTC, merged