Configure VM with VMM
SUSE/doc-modular pull request #14
Opened 2021-09-02 12:17 UTC by tbazant

rendered PDF is attached
[task-configure-virtual-machine-manager_color_en.pdf](https://github.com/SUSE/doc-modular/files/7098798/task-configure-virtual-machine-manager_color_en.pdf)

2021-09-09 15:40 UTC, lproven requested changes

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   <guimenu>Overview</guimenu> shows basic details about &vmguest; and the
```suggestion
   <guimenu>Overview</guimenu> shows basic details about &vmguest; and the
```
```suggestion
   The <guimenu>Overview</guimenu> shows basic details about the &vmguest; and the
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   in the <guimenu>Virtual Machine Manager</guimenu> list of machines.
```suggestion
   <guimenu>Name</guimenu>, <guimenu>Title</guimenu>, and
   <guimenu>Description</guimenu> are editable and help you identify &vmguest;
   in the <guimenu>Virtual Machine Manager</guimenu> list of machines.
```
```suggestion
   The <guimenu>Name</guimenu>, <guimenu>Title</guimenu>, and
   <guimenu>Description</guimenu> fields are editable, and will help you to identify
   the &vmguest; in the <guimenu>Virtual Machine Manager</guimenu> list of machines.
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   <guimenu>UUID</guimenu> shows the universally unique identifier of the
```suggestion
   <guimenu>UUID</guimenu> shows the Universally Unique IDentifier of the
```
```suggestion
   <guimenu>UUID</guimenu> shows the universally unique identifier of the
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   status&mdash;<guimenu>Running</guimenu>, <guimenu>Paused</guimenu>, or
```suggestion
   status&mdash;<guimenu>Running</guimenu>, <guimenu>Paused</guimenu>, or
```
```suggestion
   status: <guimenu>Running</guimenu>, <guimenu>Paused</guimenu>, or
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   CPU architecture, used emulator, and chipset type. None of the hypervisor
```suggestion
   CPU architecture, used emulator, and chipset type. None of the hypervisor
```
```suggestion
   CPU architecture, the emulator in use (if any), and the chipset type. None of the hypervisor
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +    to see regularly updated.
```suggestion
    to see regularly updated.
```
```suggestion
    to see.
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +    to see regularly updated.
As I understand it, they will all be updated anyway, so it's just the ones you want to see -- is that right?

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   These components are vital to a &vmguest;, therefore you cannot remove them.
```suggestion
   These components are vital to a &vmguest;, therefore you cannot remove them.
```
```suggestion
   These components are vital to a &vmguest;, so you cannot remove them.
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +    processor configuration.
```suggestion
    <guimenu>CPU</guimenu> includes detailed information about &vmguest;
    processor configuration.
```
```suggestion
    <guimenu>CPU</guimenu> includes detailed information about the processor
    configuration of the &vmguest;
   .
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +    on the destination.
```suggestion
    But the ABI provided to the &vmguest; is reproducible and during migration
    the complete CPU model definition is transferred to the destination
    &vmhost;, ensuring the migrated &vmguest; will see the exact same CPU model
    on the destination.
```
```suggestion
    However, the ABI provided to the &vmguest; is reproducible, and during migration,
    the complete CPU model definition is transferred to the destination
    &vmhost;, ensuring that the migrated &vmguest; will see the exact same CPU model
    on the destination.
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +    than 4TB of memory. The <literal>host-passthrough</literal> model comes
```suggestion
    than 4TB of memory. The <literal>host-passthrough</literal> model comes
```
```suggestion
    than 4&nbsp;TB of memory. The <literal>host-passthrough</literal> model comes
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +    available to &vmguest;.
```suggestion
    available to &vmguest;.
```
```suggestion
    available to the &vmguest;.
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +       Total amount of memory installed on &vmhost;.
```suggestion
       Total amount of memory installed on &vmhost;.
```
```suggestion
       Total amount of memory installed on the &vmhost;.
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +     &vmguest;s with memory requirements of 4TB or more currently need to use
```suggestion
     &vmguest;s with memory requirements of 4TB or more currently need to use
```
```suggestion
     &vmguest;s with memory requirements of 4&nbsp;TB or more currently need to use
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   be used for booting &vmguest;. You can change their order with the up and
```suggestion
   be used for booting &vmguest;. You can change their order with the up and
```
```suggestion
   be used for booting the &vmguest;. You can change their order with the up and
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +     network connection. The list includes &vmhost;'s available physical
```suggestion
     network connection. The list includes &vmhost;'s available physical
```
```suggestion
     network connection. The list includes the &vmhost;'s available physical
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +     the &vmguest; to an already defined virtual network.
```suggestion
     the &vmguest; to a virtual network that was already defined.
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +    pointer movement between &vmhost; and &vmguest; when using a graphical
```suggestion
    pointer movement between the &vmhost; and the &vmguest; when using a graphical
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   You can directly assign host-PCI devices to guests (PCI pass-through). When
```suggestion
   You can directly assign host-PCI devices to guests (PCI pass-through). When
```
```suggestion
   You can directly assign PCI devices on the &vmhost; to guests (PCI pass-through). When
```

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   feature is a &vmhost; configuration as described in FIXME
Is this **FIXME** still outstanding? :-)

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +    machine to a &vmguest; using &vmm;:
Not sure if you want the &vmhost; entity here or are avoiding it intentionally?

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +   <varlistentry>
The `varlist` means we can't prepend "Error message:" or the like onto the front. This is a bit of a snag, IMHO. Maybe reformatting as plain paragraphs, or using nested `itemizedlist`s...?

2021-09-09 15:40 UTC, lproven commented on xml/task-configure-virtual-machine-manager.xml
> +     For more information on disk cache modes, see FIXME
3 more **FIXME** entries here, just in case you had overlooked them.

2021-09-13 07:57 UTC, tbazant commented on xml/task-configure-virtual-machine-manager.xml
> +   feature is a &vmhost; configuration as described in FIXME
yep

2021-09-13 07:59 UTC, tbazant commented on xml/task-configure-virtual-machine-manager.xml
> +     For more information on disk cache modes, see FIXME
they're intentional

2021-09-13 08:11 UTC, tbazant reviewed
included Liam's suggestions

2021-09-13 08:11 UTC, tbazant commented on xml/task-configure-virtual-machine-manager.xml
> +   <varlistentry>
we can prepend a string inside the &lt;term&gt; normally

2021-09-13 08:11 UTC, tbazant commented on xml/task-configure-virtual-machine-manager.xml
> +   </para>
```suggestion
    The following procedure describes how to assign a PCI device from a &vmhost; to a &vmguest; using &vmm;:
   </para>
```

2021-09-13 08:11 UTC, tbazant commented on xml/task-configure-virtual-machine-manager.xml
> +    machine to a &vmguest; using &vmm;:
replaced

2021-09-13 08:12 UTC, merged