Jhalackova raid levels
SUSE/doc-modular pull request #144
Opened 2023-05-03 12:22 UTC by lvicoun

### Description

Moving RAIDs from SLE

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

2023-05-04 13:24 UTC, dariavladykina reviewed
Hi, please see some suggestions here. Thanks!

2023-05-04 13:24 UTC, dariavladykina commented on tasks/raid-naming-raid.xml
> +    and <filename>/proc/partitions</filename>.
```suggestion
    <literal>mdN</literal>, where <literal>N</literal> is a number. For example,
    they can be accessed as <filename>/dev/md127</filename> and
    are listed as <literal>md127</literal> in <filename>/proc/mdstat</filename>
    and <filename>/proc/partitions</filename>.
```

2023-05-04 13:24 UTC, dariavladykina commented on tasks/raid-naming-raid.xml
> +       will still be <literal>mdN</literal>, but a link
```suggestion
       will still be <literal>mdN</literal>, but the link
```

2023-05-04 13:24 UTC, dariavladykina commented on tasks/raid-naming-raid.xml
> +       <filename>/etc/mdadm.conf</filename> by running the following command:
```suggestion
       If a named link to the device is not sufficient for your setup, add
       the line <literal>CREATE names=yes</literal> to
       <filename>/etc/mdadm.conf</filename> by running the following command:
```

2023-05-04 13:24 UTC, dariavladykina commented on tasks/raid-naming-raid.xml
> +       <literal>mdN</literal> names until they get stopped and re-assembled.
```suggestion
       at <filename>/dev/myRAID</filename>, but also listed as
       <literal>myRAID</literal> under <filename>/proc</filename>. Note that
       this will only apply to RAIDs configured after the change to the
       configuration file. Active RAIDs will continue to use the
       <literal>mdN</literal> names until they get stopped and reassembled.
```

2023-05-04 13:24 UTC, dariavladykina commented on tasks/raid-naming-raid.xml
> +        Not all tools may support named RAID devices. In case a tool expects a
```suggestion
        Not all tools may support named RAID devices. If a tool expects a
```

2023-05-05 05:31 UTC, tomschr requested changes
@lvicoun I have some minor structural additions taken from Jana's templates. :slightly_smiling_face:

2023-05-05 05:31 UTC, tomschr commented on articles/raid.asm.xml
> +          xmlns:trans="http://docbook.org/ns/transclusion"
We need the ITS (International Translation Set) namespace to set the `its:translate` attribute. That's for our translation vendors:

```suggestion
          xmlns:trans="http://docbook.org/ns/transclusion"
          xmlns:its="http://www.w3.org/2005/11/its"
```

2023-05-05 05:31 UTC, tomschr commented on articles/raid.asm.xml
> +  <structure renderas="article" xml:id="article-example">
Add the missing language:

```suggestion
  <structure renderas="article" xml:id="article-example" xml:lang="en">
```

2023-05-05 05:31 UTC, tomschr commented on articles/raid.asm.xml
> +      <meta name="updated" content="2023-11-11"/>
Here we set the `its:translate` attribute:

```suggestion
      <meta name="maintainer" content="jsindelarova@suse.com" its:translate="no"/>
      <!-- ISO date of last update as YYYY-MM-DD -->
      <meta name="updated" content="2023-11-11" its:translate="no"/>
```

2023-05-05 05:31 UTC, tomschr commented on articles/raid.asm.xml
> +        <meta name="translation">
Same here. Although it's a comment, I'd suggest to add it anyway.

```suggestion
        <meta name="bugtracker" its:translate="no">
          <phrase role="url">https://bugzilla.suse.com/enter_bug.cgi</phrase>
          <phrase role="component">Non-product-specific documentation</phrase>
          <phrase role="product">Smart Docs</phrase>
          <phrase role="assignee">assignee@suse.com</phrase>
        </meta>
        -->
      <!-- not supported, yet. Use dm: tag for now
        <meta name="translation" its:translate="no">
```

2023-05-05 05:31 UTC, tomschr commented on articles/raid.asm.xml
> +      <meta name="category" content="Systems Management"/>
Same here:

```suggestion
      <meta name="architecture" content="x86;power" its:translate="no"/>
      <meta name="productname" its:translate="no">
        <!-- enter product name and version --><productname version="15-SP5">&sles;</productname>
      </meta>
      <meta name="title" its:translate="yes">Software RAID description and configuration</meta>
      <meta name="description" its:translate="yes">The article focuses on configuring software RAID and provides detail about various levels of RAID.</meta>
      <meta name="social-descr" its:translate="yes">Description of software RAID.</meta>
      <!-- suitable category, comma-separated list of categories -->
      <meta name="category" content="Systems Management" its:translate="no"/>
```

2023-05-05 05:31 UTC, tomschr commented on concepts/raid-about-raids.xml
> +    <meta name="maintainer" content="jsindelarova@suse.com"/>
```suggestion
    <meta name="maintainer" content="jsindelarova@suse.com" its:translate="no"/>
```

2023-05-05 05:31 UTC, tomschr commented on glues/raid-about-raids.xml
> +    <meta name="maintainer" content=""/>
If there is no maintainer ATM, better comment it:

```suggestion
    <!-- <meta name="maintainer" content="" its:translate="no"/> -->
```

2023-05-05 05:31 UTC, tomschr commented on glues/raid-management.xml
> +    <meta name="maintainer" content="jsindelarova@suse.com"/>
```suggestion
    <meta name="maintainer" content="jsindelarova@suse.com" its:translate="no"/>
```

2023-05-05 05:31 UTC, tomschr commented on tasks/raid-configuring-stripe-size.xml
> +    <meta name="maintainer" content="jsindelarova@suse.com"/>
```suggestion
    <meta name="maintainer" content="jsindelarova@suse.com" its:translate="no"/>
```

2023-05-05 05:31 UTC, tomschr commented on tasks/raid-configuring-using-yast.xml
> +    <meta name="maintainer" content="jsindelarova@suse.com"/>
```suggestion
    <meta name="maintainer" content="jsindelarova@suse.com" its:translate="no"/>
```

2023-05-05 05:31 UTC, tomschr commented on tasks/raid-monitoring-raids.xml
> +    <meta name="maintainer" content="jsindelarova@suse.com"/>
```suggestion
    <meta name="maintainer" content="jsindelarova@suse.com" its:translate="no"/>
```

2023-05-05 05:31 UTC, tomschr commented on tasks/raid-naming-raid.xml
> +    <meta name="maintainer" content="jsindelarova@suse.com"/>
```suggestion
    <meta name="maintainer" content="jsindelarova@suse.com" its:translate="no"/>
```

2023-05-05 09:19 UTC, tbazant requested changes
Consider implementing the included suggestions

2023-05-05 09:19 UTC, tbazant commented on concepts/raid-raid-levels.xml
* consider changing the title to 'RAID levels' only
* consider turning this from a concept into a reference
* consider &lt;variablelist>'s instead of subsection for specific RAID levels

2023-05-05 09:19 UTC, tbazant commented on glues/raid-about-raids.xml
> +  </itemizedlist>
This information may be a duplicate of what the table of contents offers, consider removing it

2023-05-05 09:19 UTC, tbazant commented on glues/raid-about-raids.xml
This glue looks like a true concept, not a glue, it has valuable reusable information.

2023-05-05 09:19 UTC, tbazant commented on glues/raid-management.xml
> +<topic xml:id="glue-example"
```suggestion
<topic xml:id="raid-management"
```

2023-05-05 09:19 UTC, tbazant commented on tasks/raid-configuring-using-yast.xml
> +<topic xml:id="task-configuring-using-yast"
```suggestion
<topic xml:id="software-raid-configure-using-yast"
```

2023-05-05 10:46 UTC, merged