Cpu temp assembly
SUSE/doc-modular pull request #148
Opened 2023-05-04 13:33 UTC by dmpop

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

2023-05-04 13:44 UTC, tomschr requested changes
@dmpop Thanks Dima! I'm fine with it. Found some minor issues.

2023-05-04 13:44 UTC, tomschr commented on articles/CPUTemp.asm.xml
> +  <structure xml:id="minvm-intro" xml:lang="en" renderas="article">
The ID looks... familiar. :wink: Copy-pasta issue?

```suggestion
  <structure xml:id="cpu-temp-check" xml:lang="en" renderas="article">
```

2023-05-04 13:44 UTC, tomschr commented on DC-task-check-cpu-temperature
Technically, this DC file is correct. However, I'm not sure if this topic should stand on its own or if it should be integrated into a larger, overarching theme  (something like systems administration?)

Probably this is out of scope for this issue; perhaps something for our next SLE writers call? (Could be that I miss some information)

2023-05-04 13:44 UTC, tomschr commented on articles/CPUTemp.asm.xml
> +        <productname version="ALP">&sles;</productname>
Is ALP a version? :thinking: I would move "ALP" _inside_ the tag like this:

```suggestion
        <productname version="1">ALP</productname>
```

The version (here "1") is taken directly from Tomás' assembly file.

2023-05-04 14:45 UTC, dariavladykina reviewed
Hi, please see some suggestions here. Thanks!

2023-05-04 14:45 UTC, dariavladykina commented on articles/CPUTemp.asm.xml
> +        </itemizedlist>
This part is already featured in the article (after Introduction). This is a duplicate I suggest removing from abstract.

2023-05-04 14:45 UTC, dariavladykina commented on articles/CPUTemp.asm.xml
> +              You want to reduce your electricity bill and make sure that hardware runs optimally.
```suggestion
              You want to reduce your electricity bill and make sure that the hardware runs optimally. 
```

2023-05-04 14:45 UTC, dariavladykina commented on tasks/cpu-temp-check.xml
> +     CPUs cool is a critical cost factor, especially in data centers.
```suggestion
    <para>Energy savings and cost reduction. When a CPU runs at full
     speed, it consumes more energy than when it is idling. Also, running
     CPUs cool is a critical cost factor, especially in data centers.
```

2023-05-04 14:45 UTC, dariavladykina commented on tasks/cpu-temp-check.xml
> +    <para>Easier detection of cooling issues. If a CPU temperature reaches 80°C or higher, it indicates that there is a problem with the cooling system, a fan, or thermal paste wasn't applied correct
```suggestion
    <para>Easier detection of cooling issues. If the CPU temperature reaches 80°C or higher, it indicates that there is a problem with the cooling system or the fan, or that the thermal paste was not applied correctly.
```

2023-05-05 07:51 UTC, dariavladykina reviewed
Please consider some more suggestions as to the article structure.
Also, suggest renaming the assembly - changing the assembly file name.

2023-05-05 07:51 UTC, dariavladykina commented on tasks/cpu-temp-check.xml
>     </dm:docmanager>
This information is maintained at the assembly level only, it needs to be removed.

2023-05-05 07:51 UTC, dariavladykina commented on tasks/cpu-temp-check.xml
> +   <title>Checking and monitoring CPU temperature</title>
Suggest removing this title as it is superfluous and orphaned for such a short article that doesn't have any other parts.
To replace this: `<module resourceref="_cpu-temp-check" renderas="section"/>` by `<module resourceref="_cpu-temp-check" renderas="section" omittitle="true"/>` to get rid of the duplicated title.

2023-05-09 08:55 UTC, merged