Concept: Zypper
SUSE/doc-modular pull request #15
Opened 2021-09-07 12:16 UTC by dmpop

2021-09-07 13:06 UTC, tomschr requested changes
@dmpop Great article! :+1: Although there are quite some comments and suggestion, don't worry. Most are easy to apply and minor things. Some can be considered as a hint or tip.

Hope it helps. Thanks!

2021-09-07 13:06 UTC, tomschr commented on xml/concept-zypper.xml
> +  <title>Zypper</title>
Maybe "Zypper" is just enough for a title. On the other hand, it *could* be helpful to give our readers an idea as not all are familiar with this name. One idea (and probably not the best) could be:

```suggestion
  <title>System management with &zypper;</title>
```

You get the idea, right? :wink: I think something similar was mentioned in our "Open Issues" Conflu page (which still needs to be clarified).

2021-09-07 13:16 UTC, dmpop commented on xml/concept-zypper.xml
> +  <title>Zypper</title>
Good point. Since it's a concept overview, I need to come up with something suitable. Overview of the Zypper package manager?

2021-09-07 13:17 UTC, dmpop commented on xml/concept-zypper.xml
> +   &zypper; offers several benefits compared to graphical package managers.
No, because the list that follows starts with a new sentence and not a list item.

2021-09-07 13:59 UTC, dmpop commented on xml/concept-zypper.xml
> +   solving any dependencies) while requesting the package from the specified
I didn't write the text. It's a copy-paste from our docs. :smile:

2021-09-08 07:01 UTC, merged

2021-09-15 12:59 UTC, taroth21 commented on xml/concept-zypper.xml
> +    <term>Zypper subcommands</term>
@dmpop : With regards to consistent terminology (and as subcommands are dealt with in a later section), shouldn't this heading read `Zypper commands`?