Jhalackova cockpit
SUSE/doc-modular pull request #153
Opened 2023-05-15 12:27 UTC by lvicoun

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

2023-05-18 07:55 UTC, tbazant requested changes
See minor suggestions

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-configuring-servers.xml
> +  </section>
```suggestion
    <procedure xml:id="cockpit-configuring-hostname">
      <title>Changing host name</title>
      <step>
        <para>
          Navigate to the <guimenu>Overview</guimenu> part.
        </para>
      </step>
      <step>
        <para>
          In the <guimenu>Configuration</guimenu> part, click
          <guimenu>edit</guimenu>.
        </para>
      </step>
      <step>
        <para>
          Fill in the following:
        </para>
        <itemizedlist>
          <listitem>
            <para>
              <guimenu>Pretty host name</guimenu> - a user-defined free-form
              host name
            </para>
          </listitem>
          <listitem>
            <para>
              <guimenu>Real host name</guimenu> - is a name how the device is
              called in the network.
            </para>
          </listitem>
        </itemizedlist>
      </step>
    </procedure>
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-configuring-servers.xml
> +  </section>
```suggestion
    <procedure xml:id="cockpit-configuring-timezone">
      <title>Changing system time or time zone</title>
      <step>
        <para>
          Navigate to the <guimenu>Overview</guimenu> part.
        </para>
      </step>
      <step>
        <para>
          In the <guimenu>Configuration</guimenu> pane, click the value of the <guimenu>System time</guimenu>.
        </para>
      </step>
      <step>
        <para>
          In the pop-up window you can change the following:
        </para>
        <itemizedlist>
          <listitem>
            <para>
              <guimenu>Time zone</guimenu> - the value was set during the
              manual installation or in case of the raw images it is set to
              UTC.
            </para>
          </listitem>
          <listitem>
            <para>
              <guimenu>Set time</guimenu> - by default NTP is used for time
              synchronisation. You can set the time manually or if you defined
              alternative NTP servers, you can use those NTP servers for time
              synchronization.
            </para>
          </listitem>
        </itemizedlist>
      </step>
    </procedure>
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-configuring-servers.xml
> +          click on the <guimenu>System time</guimenu> value
```suggestion
          click the <guimenu>System time</guimenu> value
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-configuring-servers.xml
> +              synchronisation. You can set the time manually or if you defined
```suggestion
              synchronization. You can set the time manually or if you defined
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-creating-logical-volumes.xml
> +        Click on the volume group in <guimenu>Devices</guimenu>.
```suggestion
        Click the volume group in <guimenu>Devices</guimenu>.
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-creating-timers.xml
> +      the default unit file. If you want to restore the timer to the default
```suggestion
      the default unit file. To restore the timer to the default
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-creating-users.xml
> +        To assign the <guimenu>sudo</guimenu> privileges, or add an SSH key to
```suggestion
        To assign the <guimenu>sudo</guimenu> privileges or add an SSH key to
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-creating-volume-groups.xml
> +        This topoic focuses on creating volume groups from several disks that
```suggestion
        This topic focuses on creating volume groups from several disks that
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-getting-container-images.xml
> +    <title>Getting container images</title>
```suggestion
    <title>Downloading container images</title>
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-installation.xml
> +        default, but there might some cases when &cockpit; is missing. This
```suggestion
        default, but there may some cases when &cockpit; is missing. This
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-managing-containers.xml
> +          you might lose data
```suggestion
          you may lose data
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-managing-firewall.xml
> +      the &cockpit; service might get blocked and you might get disconnected
```suggestion
      the &cockpit; service may get blocked and you may get disconnected
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-managing-firewall.xml
> +      The <guimenu>public zone</guimenu> is the deafult firewall zone. To add a
```suggestion
      The <guimenu>public zone</guimenu> is the default firewall zone. To add a
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-managing-lvm.xml
> +        or activate volumes, delete them or change the size of the volumes.
```suggestion
        or activate volumes, delete them, or change the size of the volumes.
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-managing-lvm.xml
> +    To perform any administration task on already existing logical volume,
```suggestion
    To perform any administration task on an existing logical volume,
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-managing-systemd-units.xml
> +        Click on the unit, you want to administer.
```suggestion
        Click the unit that you want to administer.
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-managing-systemd-units.xml
> +            disallowing the unit might cause serious troubles for the system.
```suggestion
            disallowing the unit may cause serious troubles for the system.
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-modifying-accounts.xml
> +        Click on the account you want to modify.
```suggestion
        Click the account that you want to modify.
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-modifying-raids.xml
> +    To modify an already existing RAID, proceed as follows:
```suggestion
    To modify an existing RAID, proceed as follows:
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-modifying-raids.xml
> +        With some RAID levels, you can switch on the <guimenu>Bitmap</guimenu>
```suggestion
        With certain RAID levels, you can switch on the <guimenu>Bitmap</guimenu>
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-modifying-raids.xml
> +      resynchronization that might take some time. Keep in mind that each RAID
```suggestion
      resynchronization that may take certain time. Keep in mind that each RAID
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-mounting-partitions.xml
> +    <title>The parttion must be formatted</title>
```suggestion
    <title>The partition must be formatted</title>
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-primary-servers.xml
> +        This topic focuses on loggin into servers that can expose the 9090
```suggestion
        This topic focuses on logging into servers that can expose the 9090
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-primary-servers.xml
> +      configuration allows logging in with the same usernames and passwords
```suggestion
      configuration allows logging in with the same user names and passwords
```

2023-05-18 07:55 UTC, tbazant commented on tasks/cockpit-secondary-servers.xml
> +          Click on the
```suggestion
          Click the
```

2023-05-19 11:23 UTC, tbazant commented on glues/cockpit-managing-services.xml
> +  <title>Service management using &cockpit;</title>
```suggestion
  <title>Managing services using &cockpit;</title>
```

2023-05-19 11:25 UTC, tbazant commented on concepts/cockpit-system-update.xml
> +    <title>&productnameshort; updates and snapshots</title>
```suggestion
    <title>Updates and snapshots</title>
```

2023-05-22 14:35 UTC, dariavladykina reviewed
Hi, please consider some suggestions for this one. Thanks!

2023-05-23 08:45 UTC, merged