Added tr-up run  command + example
SUSE/doc-modular pull request #161
Opened 2023-05-26 11:06 UTC by tbazant

### Are there any relevant issues/feature requests?

* jsc#DOCTEAM-999

2023-05-26 11:51 UTC, lvicoun requested changes
Please add the run subcommand to the transactional-update-usage.xml.

2023-06-05 10:16 UTC, lvicoun approved these changes

2023-06-06 11:16 UTC, dariavladykina reviewed
Hi, please see a minor suggestion here. Thanks!

2023-06-06 11:16 UTC, dariavladykina commented on tasks/transactional-update-no-reboot.xml
> +      transactional session by concatenating them within command shell such as
```suggestion
      transactional session by concatenating them within a command shell such as
```

2023-06-06 14:52 UTC, merged