Removing ALP-Bedrock profiliing
SUSE/doc-modular pull request #172
Opened 2023-06-29 10:53 UTC by tbazant

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-06-29 14:26 UTC, tomschr requested changes
@tbazant Good work! :+1:
Apart from a minor issue, it looks fine. I cannot judge the text though.

2023-06-29 14:26 UTC, tomschr commented on concepts/alp.xml
> +      &productname; (&productnameshort;) is a lightweight operating system for a
In the case of os="generic", both entities end up with the phrase "SUSE Linux (SUSE Linux)". That's unfortunate. You could use another `phrase` to exclude "generic":

```suggestion
      &productname; <phrase os="slemicro;alp-micro;sles">(&productnameshort;)</phrase> is a lightweight operating system for a
```

2023-06-30 07:24 UTC, tbazant commented on concepts/alp.xml
> +      &productname; (&productnameshort;) is a lightweight operating system for a
the `alp.xml` file is included from `DC-alp-micro` only. There is a profiling information for `alp-micro`. DO I really need to profile for &productname;, &productnameshort; ?

2023-06-30 07:40 UTC, tomschr commented on concepts/alp.xml
> +      &productname; (&productnameshort;) is a lightweight operating system for a
Well, it's just for the case if both entities contain the same information. This is the case for SUSE Linux. You don't have to change anything inside the two entities itself.

As we don't know where these files will end up, I thought it might be a precaution. That's why I've wrapped the short version around a `phrase` to exclude it if necessary.

2023-06-30 09:35 UTC, tomschr approved these changes

2023-06-30 10:03 UTC, merged