Jhalackova se linux
SUSE/doc-modular pull request #174
Opened 2023-07-11 12:35 UTC by lvicoun

### Description

SELinux moved to smartdocs. The DC file is currently profiled for SLE Micro.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-08-07 16:31 UTC, taroth21 commented
Hi @lvicoun, as I wanted to read the article in its entirety (as customers would read it), I have build a PDF from it and added annotations there. Please see:

[selinux-article_feedback_taroth.pdf](https://github.com/SUSE/doc-modular/files/12282832/selinux-article_feedback_taroth.pdf)

Overall, I think the structure of the article is useful as it is and the order of most sections are logic to me. 

I tried to avoid a detailed language or style review (as this will be done by @dariavladykina later on), but where I stumbled across a typo (or some things where you could ease the job for the translators a bit), I added remarks (or crossed out typos), hope that was fine. 

Many thanks!

2023-08-07 16:33 UTC, taroth21 requested changes
Hi @lvicoun, please find my remarks in the annotated PDF. Thanks!

2023-08-31 13:16 UTC, dariavladykina reviewed
Hi Jana, please see some suggestions here. Thanks!

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +                  saves file names of all files wich file context differs from the default to the provided output file
```suggestion
                  saves to the provided output file the names of all files whose file context differs from the default 
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +                  forces a reset of
Some content missing here.

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +            relabel your system if you added a new policy.
```suggestion
            relabel your system if you added a new policy
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +                  performing any changes.
```suggestion
                  performing any changes
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +            argument.
```suggestion
            manage &selnx; policy modules using the <option>module</option>
            argument
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +            <command>fcontext</command>, <command>boolean</command>, <command>module</command>
```suggestion
            <command>fcontext</command>, <command>boolean</command>, <command>module</command>.
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +          Using the <command>semanage fcontext</command> command you can perform the
```suggestion
          Using the <command>semanage fcontext</command> command, you can perform the
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +              add your own rules.
```suggestion
              add your own rules
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +          fcontext</command> command does not require modifications or
```suggestion
          fcontext</command> command do not require modifications or
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +          On top of commmon options described in
```suggestion
          On top of the common options described in
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +                target path), For example, you want to assign the same context
```suggestion
                target path). For example, you want to assign the same context
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +                    <option>s</option> - a socket.
```suggestion
                    <option>s</option> - a socket
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +              Bear in mind that the user group should be primary as mapping &selnx; users on Supplementary groups may result in incompatible mappings.
```suggestion
              Bear in mind that the user group should be primary because mapping &selnx; users on Supplementary groups may result in incompatible mappings.
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +          The <command>semanage user</command> command controls the mapping between &selnx; user and the roles nad MLS/MCS levels.
```suggestion
          The <command>semanage user</command> command controls the mapping between the &selnx; user and the roles above MLS/MCS levels. 
```

2023-08-31 13:16 UTC, dariavladykina commented on references/selinux-tools.xml
> +           Using this command you can perform the following tasks:
```suggestion
           Using this command, you can perform the following tasks:
```

2023-09-01 07:50 UTC, merged