[WIP]Systemd services: Adds an asm file template for systemd
SUSE/doc-modular pull request #176
Opened 2023-07-17 14:43 UTC by Amrita42

### Description

Describe the overall goals of this pull request.
The scope is to merge all the three draft into one article and also add more content.

- Enabling and disabling systemd services
- Starting and stopping systemd services
- Sending termination signals to systemd services 

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-09-27 08:06 UTC, tomschr requested changes
@Amrita42 Thanks for all your efforts! :hugs: 

I've added some comments, suggestions, and fixing some typos. Apart from these, I also have some general recommendations:

* Prompts
  Some starts with a command, others with a `&prompt...;` entity. Maybe go through all screens and add some prompts where necessary to make them consistent.
* Screens
  Screens must not be indented. :wink: Always start your text in column 1, although it looks bad from a formatting perspective. The reason for this is, this makes screens look inconsistent in _the output_. It looks weird and the user may be asking if the content should also be indented.
  Another reason: your available space may be limited, especially inside some lists. You will waste valuable characters that are probably needed on the right site.

Apart from the above issues, some other points:

* As I've mentioned it below, the section "About system usage" looks a bit odd to me. It seems not really related to systemd or I'm too dumb to see the connection. :laughing: 
* The section "Structure of a unit file" is very general. Maybe it would be more useful to the reader, if you use an existing (simple) unit file and try to dissect it and explain the necessary pieces?
* The section "Creating a Linux service with systemd" explains how to create the service file, but it actually doesn't explain the `FILE_NAME.sh`. That's the thing that gets started when the service is triggered. What does it contain? What does it do? This is missing.
  Maybe it would be more helpful to have a specific example?

2023-09-29 14:40 UTC, taroth21 requested changes
Hi @Amrita42, many thanks - I'll attach the first part of my review as annotated PDF to this PR and will finish the review at the beginning of next week. 

[what-is-systemd_feedback_taroth_part1.pdf](https://github.com/SUSE/doc-modular/files/12767663/what-is-systemd_feedback_taroth_part1.pdf)

2023-10-02 09:41 UTC, taroth21 commented
Hi Amrita, please find my feedback for the rest of the article here:
[what-is-systemd_feedback_taroth_part2.pdf](https://github.com/SUSE/doc-modular/files/12781534/what-is-systemd_feedback_taroth_part2.pdf)

2023-10-03 07:07 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +      Administration is easier when you understand units and unit files when working with &systemd;.
Thanks Toms :) I will use "unit file"

2023-10-03 07:10 UTC, Amrita42 commented on concepts/types-of-systemd-unit-files.xml
> +      the end of the resource name. &systemd; categorizes units according to the type of resource they describe.
Good point

2023-10-03 10:55 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +         it is enabled or disabled. When you enable a unit, it automatically starts at boot. </para>
@tomschr its not clear , do you mean the directives in the install section or add as a sentence ?

2023-10-03 10:56 UTC, Amrita42 commented on concepts/types-of-systemd-unit-files.xml
> +  <para>Types of unit files available for &systemd;:</para>
re-phrased

2023-10-03 10:59 UTC, Amrita42 commented on concepts/types-of-systemd-unit-files.xml
> +          and the dependency or the hierarchy information for related software.
let me re-phrase , dependency on the other unit files is what i meant

2023-10-03 11:25 UTC, Amrita42 commented on tasks/systemd-as-regular-user.xml
> +          Create a &systemd; unit file and save it at <filename>~/.config/systemd/user/</filename> directory:
Its explained below i.e. FILE_NAME.service

2023-10-03 11:33 UTC, Amrita42 commented on tasks/systemd-as-regular-user.xml
> +         otherwise if a unit file with the same name exists, it would be executed or listed instead.
I had a similar question when I looked at this [section 8 of systemdtimers](https://documentation.suse.com/smart/systems-management/html/systemd-working-with-timers/index.html#systemd-timer-user) >> As a regular user, you must provide the path to the unit files as in the examples below. Otherwise, if a system-wide timer with the same name exists, it would be executed or listed instead.
@fsundermeyer suggested  specifying the complete path ensures there are are no errors otherwise how would the user know if a systemd file with same name exists

2023-10-03 11:40 UTC, Amrita42 commented on concepts/types-of-systemd-unit-files.xml
> +        <literal>inotify</literal> is used to monitor the path for changes.
Linux has used inotify to monitor for changes to paths and files. The inotify kernel API can be used by programs that want to be notified about changes to files

2023-10-03 11:42 UTC, Amrita42 commented on concepts/types-of-systemd-unit-files.xml
> +        <literal>inotify</literal> is used to monitor the path for changes.
re-phrased to define

2023-10-03 11:49 UTC, Amrita42 commented
@tomschr 
As I've mentioned it below, the section "About system usage" looks a bit odd to me. It seems not really related to systemd or I'm too dumb to see the connection. 😆
[Amrita] it is not directly related but i feel useful info to have .
The section "Creating a Linux service with systemd" explains how to create the service file, but it actually doesn't explain the FILE_NAME.sh. That's the thing that gets started when the service is triggered. What does it contain? What does it do? This is missing.
Maybe it would be more helpful to have a specific example?
[Amrita]: I have explained this in _concepts/systemd-unit-file.xml_  , the anatomy of the unit file. I thought it is more specific to creating the a systemd service. Maybe add a link for additional resource or to know more about a unit file see...

2023-10-04 08:29 UTC, fsundermeyer commented on tasks/systemd-as-regular-user.xml
> +         otherwise if a unit file with the same name exists, it would be executed or listed instead.
What Amrita said. In _this_ particular  case the name of the unit file is unique, so not specifying the path works. But if a system unit file and a user unit file have the same name, the system file takes precedence. As a user you are probably not awayre of all existing system unit files, so it is a good practice to _always_ specify a path when running systemd as a user.

2023-10-05 09:58 UTC, Amrita42 commented on references/systemd-gnu-accounting-utilities.xml
Removed

2023-10-05 10:03 UTC, Amrita42 commented
@taroth21 Addressed the feedback from part 1 and 2. Please note for the systemctl commands , I have added example output/also expanded decsriptions where applicable because start/enable/stop etc does not have any output .

2023-10-05 10:31 UTC, Amrita42 commented
**Pending/wip**: two example outputs are nor rendering properly in **systemctl-cheatsheet.xml**

2023-10-05 11:11 UTC, tomschr commented on concepts/systemd-unit-file.xml
> +         it is enabled or disabled. When you enable a unit, it automatically starts at boot. </para>
I'm sorry, @Amrita42. I was referring to the dependencies of the unit itself. Maybe there is a better term for this. For example, the Crony service has these "dependencies" in the `Unit` section:

```INI
[Unit]
Description=NTP client/server
Documentation=man:chronyd(8) man:chrony.conf(5)
After=nss-lookup.target
Wants=network.target
After=network.target
Wants=time-sync.target
Before=time-sync.target
Conflicts=ntpd.service systemd-timesyncd.service
```

Here, the the "After", "Wants", and "Before" are all "dependencies" that the Crony service needs as a requisites. There are more of these keywords. 

My idea was to just mention in a sentence that a unit may require other service types to work properly. Roughly speaking, something like this:

```
Depending on the unit it may require other units to work properly. For example, ...
```

Does that make sense?

2023-10-05 16:15 UTC, fsundermeyer requested changes
Amrita, I think this article needs to be stripped down further. If I understand correctyl it's primary goal is to provide an introduction on the baseics of systemd. Goal of this article is to help readers to understand what systemd does and where a user can interact with systemd.
Everything else (e.g. How to create your own services, How to interprete the output of a specific systemctl command, etc) is subject for aother articles on the respective subject.
Once we have created these specific articles, this article here should have pointers to these specific articles (e.g. the systemd timers article).

Therefore I would remove some sections (and re-use them in the more specific articles) . I would also add (small sections or at least some pointers to):
* the systemd concept of logging (only the concept, everything else would be covered in a seperate article about journalctl)
* dependency handling between units(again, concept only, the details are subject to the creating my own service article)
* an extra section about the concept of targets (as a mechanism to group services)

2023-10-06 07:25 UTC, Amrita42 commented on articles/systemd-services.asm.xml
> +      <title>Managing &systemd; services</title>
Re-phrased as systemd basics

2023-10-06 07:30 UTC, Amrita42 commented on DC-what-is-systemd
> +DOCBOOK5_RNG_URI="urn:x-suse:rng:v2:geekodoc-flat"
good catch

2023-10-06 07:55 UTC, Amrita42 commented on references/systemd-termination-signal-new.xml
> +<!DOCTYPE topic
Yes this was mentioned in Tanja's part 2 pdf review and I have moved the file >> systemd-termination-signal-new.xml. But based on your review , I have removed this ref topic for a new article inclusion

2023-10-06 08:59 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +    <title>Structure of a unit file</title>
Since we are explaining the anatomy of a unit file , I would prefer to use "structure of a unit file"

2023-10-06 09:12 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +      </para>
Done

2023-10-06 09:24 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +          by their process and daemon behavior. It instructs  &systemd; how to correctly manage the service and also determine its state.
To give context, I had a dilemma whether toi includes all the sections ( would it be too much?) or part of it so I went with the line and listed the most common/imp ones :
_Unit files include the following sections:_

2023-10-06 09:25 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +    </varlistentry>
To give context, I had a dilemma whether toi includes all the sections ( would it be too much?) or part of it so I went with the line and listed the most common/imp ones :
_Unit files include the following sections:_

2023-10-06 09:27 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +    </varlistentry>
@fsundermeyer

2023-10-06 10:22 UTC, fsundermeyer commented on concepts/systemd-unit-file.xml
> +    </varlistentry>
How about 

[Service] / [Mount] / [Path] / ...
Unit-type-specific section providing configuration only applicable for the respective type. For the mount type, for example, this section specifies mount points and the file system to mount. For the service it would be information on which daemon to start.

2023-10-08 17:42 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +    </varlistentry>
Added [Mount] and [Path] , [[Service] is defined

2023-10-09 05:29 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +         it is enabled or disabled. When you enable a unit, it automatically starts at boot. </para>
Yes , its very clear , I have added a sentence.

2023-10-10 13:03 UTC, fsundermeyer commented on concepts/systemd-as-regular-user.xml
> +      By default, &systemd; runs with &rootuser; user privileges. In certain scenarios it is more secure
I am not sure the security argument is legit here. I'd rather say you can also use systemd when you do not have root privileges. Or when you want/need to start services as a user. Or when you want to automate certain processes (via systemd timers).

2023-10-10 13:05 UTC, fsundermeyer commented on concepts/systemd-as-regular-user.xml
> +  <section xml:id="create-user-service">
Again, no subsection here.

I also think this section is too specific, we will have a separate article on this topic where we can provide all the details. Think of this part as the introduction for that article. So rather explain that systemd _can_ be used without root privileges and why you want to do this.

2023-10-10 13:06 UTC, fsundermeyer commented on references/systemctl-cheatsheet.xml
> +          <para><emphasis>Example output</emphasis></para>
No examples in this section, please remove all of them

2023-10-11 08:25 UTC, Amrita42 commented on articles/systemd-basics.asm.xml
> +              You can manage all system settings and services with &systemd;.
Removed GOAL

2023-10-11 08:29 UTC, Amrita42 commented on concepts/what-is-systemd.xml
> +        <para>For troubleshooting, you can use <command>systemctl</command> and <command>journalctl</command>, which is
Implemented

2023-10-11 08:34 UTC, Amrita42 commented on references/systemctl-cheatsheet.xml
> +          <para><emphasis>Example output</emphasis></para>
Done

2023-10-11 08:44 UTC, Amrita42 commented on concepts/systemd-as-regular-user.xml
> +      By default, &systemd; runs with &rootuser; user privileges. In certain scenarios it is more secure
re-phrased

2023-10-11 08:45 UTC, Amrita42 commented on concepts/systemd-as-regular-user.xml
> +  <section xml:id="systemd-regular">
Done

2023-10-11 09:25 UTC, Amrita42 commented on concepts/systemd-as-regular-user.xml
> +  <section xml:id="create-user-service">
Implemented.

2023-10-11 09:37 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +            The most common way to specify how a service should be enabled.
re-defined

2023-10-11 10:37 UTC, Amrita42 commented
@dariavladykina Please provide a peer/style review . Thanks

2023-10-11 14:44 UTC, dariavladykina reviewed
Hi Amrita, please see some suggestions from my part. We can have another review round when all is settled. Thanks!

2023-10-11 14:44 UTC, dariavladykina commented on concepts/systemd-as-regular-user.xml
> +  In certain scenarios it is more secure for a service to run with the privilege of a regular user. You can do this by creating a <literal>user</literal>
```suggestion
<abstract><para> You can use &systemd; as a regular user and when you do not have &rootuser; user privileges.
  In certain scenarios, it is more secure for a service to run with the privilege of a regular user. You can do this by creating a <literal>user</literal>
```

2023-10-11 14:44 UTC, dariavladykina commented on concepts/systemd-as-regular-user.xml
> +          the <command>loginctl enable-linger <replaceable>USERNAME</replaceable></command>
```suggestion
          the <command>loginctl enable-linger <replaceable>USERNAME</replaceable></command>.
```

2023-10-11 14:44 UTC, dariavladykina commented on references/systemctl-cheatsheet.xml
> +            Lists the &systemd; units. You can use the optional arguments;
```suggestion
            Lists the &systemd; units. You can use the optional arguments:
```

2023-10-11 14:44 UTC, dariavladykina commented on references/systemctl-cheatsheet.xml
> +    Instead of manually starting the service , use the <command>start</command>command.
```suggestion
    Instead of manually starting the service, use the <command>start</command> command.
```

2023-10-11 14:44 UTC, dariavladykina commented on references/systemctl-cheatsheet.xml
> +    Disables the service at boot.
```suggestion
    Disables the service on boot.
```

2023-10-11 14:44 UTC, dariavladykina commented on references/systemctl-cheatsheet.xml
> +    If the service is not running, it is restarted .
```suggestion
    If the service is not running, it is restarted.
```

2023-10-11 14:44 UTC, dariavladykina commented on references/systemctl-cheatsheet.xml
> +  This makes it impossible to load the service even if another enabled service requires it. It must be stopped manually or
```suggestion
  This makes it impossible to load the service even if another enabled service requires it. It must be stopped manually, or
```

2023-10-11 14:44 UTC, dariavladykina commented on references/systemctl-cheatsheet.xml
> +   Unmasks the service. It is effective when the system restarts, or starts manually.
```suggestion
   Unmasks the service. It is effective when the system restarts or starts manually.
```

2023-10-11 14:44 UTC, dariavladykina commented on references/systemctl-cheatsheet.xml
> +      <listitem><para>Goes into the emergency mode<literal>emergency.target</literal>.</para></listitem>
```suggestion
      <listitem><para>Goes into the emergency mode <literal>emergency.target</literal>.</para></listitem>
```

2023-10-11 14:44 UTC, dariavladykina commented on tasks/systemd-troubleshooting.xml
> +          <command>systemd-analyze plot command</command> to visual the boot process and identify issues.
```suggestion
          <command>systemd-analyze plot command</command> to visualize the boot process and identify issues.
```

2023-10-11 14:44 UTC, dariavladykina commented on tasks/systemd-troubleshooting.xml
> +file in a SVG compatible image viewer or web browser to analyze services that are causing issues during the boot process.</para>
```suggestion
<para>The command creates an SVG file called <filename>boot-plot.svg</filename> that contains a graphical representation of the boot process and potential issues. This includes the start and stop time of each service. You can open this file in an SVG-compatible image viewer or Web browser to analyze services that are causing issues during the boot process.</para>
```

2023-10-11 14:44 UTC, dariavladykina commented on tasks/systemd-troubleshooting.xml
> +        <command>systemd-analyze verify <replaceable>SERVICE</replaceable></command>.</emphasis></term>
```suggestion
        <command>systemd-analyze verify <replaceable>SERVICE</replaceable></command></emphasis></term>
```

2023-10-11 14:44 UTC, dariavladykina commented on tasks/systemd-troubleshooting.xml
> +        journalctl -u <replaceable>SERVICE</replaceable></command> command.</emphasis></term>
```suggestion
        journalctl -u <replaceable>SERVICE</replaceable></command> command</emphasis></term>
```

2023-10-11 14:44 UTC, dariavladykina commented on tasks/systemd-troubleshooting.xml
> +      <term><emphasis>Use the <command>systemd-analyze plot</command> command to visualize the boot process.</emphasis></term>
```suggestion
      <term><emphasis>Use the <command>systemd-analyze plot</command> command to visualize the boot process</emphasis></term>
```

2023-10-11 14:44 UTC, dariavladykina commented on tasks/systemd-troubleshooting.xml
> +        A common issue is a suspended service or a stalled shutdown. To find out, use the following:
```suggestion
      <listitem> <para>If the shutdown or reboot takes long, it could be a service that is not exiting. &systemd;
        waits for some time for each service to exit before trying to terminate it.
        A common issue is a suspended service or a stalled shutdown. To find out, use the following:
```

2023-10-11 14:44 UTC, dariavladykina commented on tasks/systemd-troubleshooting.xml
> +<para>You can cancel the running and waiting jobs, and again shutdown or reboot: </para>
```suggestion
<para>You can cancel the running and waiting jobs, and again shut down or reboot: </para>
```

2023-10-11 14:44 UTC, dariavladykina commented on concepts/systemd-best-practices.xml
> +               Use absolute path for executable files and required files such as configuration files or scripts in your
```suggestion
               Use an absolute path for executable files and required files such as configuration files or scripts in your
```

2023-10-11 14:44 UTC, dariavladykina commented on concepts/systemd-best-practices.xml
> +              Use the <emphasis>ExecReload</emphasis> directive in the <literal>[SECTION]</literal> section, when you want to define a specific command
```suggestion
              Use the <emphasis>ExecReload</emphasis> directive in the <literal>[SECTION]</literal> section when you want to define a specific command
```

2023-10-11 14:44 UTC, dariavladykina commented on concepts/systemd-best-practices.xml
> +              Use the <emphasis>ExecReload</emphasis> directive in the <literal>[SECTION]</literal> section, when you want to define a specific command
Should this be [Service] section instead of [SECTION] section?

2023-10-11 14:44 UTC, dariavladykina commented on concepts/systemd-best-practices.xml
> +               Use the <emphasis>ExecReload</emphasis> directive in the <literal>[SECTION]</literal> section, when you want to define
Should this be [Service] section instead of [SECTION] section?

2023-10-11 14:44 UTC, dariavladykina commented on concepts/systemd-best-practices.xml
> +               Use the <emphasis>ExecReload</emphasis> directive in the <literal>[SECTION]</literal> section, when you want to define
```suggestion
               Use the <emphasis>RestartSec</emphasis> directive in the <literal>[SECTION]</literal> section when you want to
```

2023-10-11 14:44 UTC, dariavladykina commented on concepts/systemd-best-practices.xml
> +               a specified time to release resources or to to prevent rapid restart loops that can cause high system load.
```suggestion
               a specified time to release resources or prevent rapid restart loops that can cause high system load.
```

2023-10-11 14:44 UTC, dariavladykina commented on concepts/systemd-best-practices.xml
> +               If this mode is enabled , the machine is blocked from connecting to the network.
```suggestion
               You can disable emergency mode on a remote machine, for example, a virtual machine hosted on Google Cloud.
               If this mode is enabled, the machine is blocked from connecting to the network.
```

2023-10-12 07:30 UTC, Amrita42 commented on concepts/systemd-best-practices.xml
> +              Use the <emphasis>ExecReload</emphasis> directive in the <literal>[SECTION]</literal> section, when you want to define a specific command
Good catch , yes :)

2023-10-12 07:35 UTC, Amrita42 commented on concepts/systemd-best-practices.xml
> +               Use the <emphasis>ExecReload</emphasis> directive in the <literal>[SECTION]</literal> section, when you want to define
Correct, implemented

2023-10-12 07:36 UTC, Amrita42 commented on concepts/systemd-best-practices.xml
> +               a specified time to release resources or to to prevent rapid restart loops that can cause high system load.
Done

2023-10-12 07:45 UTC, Amrita42 commented on concepts/systemd-unit-file.xml
> +         Crony to work.
re-phrased >> The Chrony service has the following directives , After,Wants.......

2023-10-12 08:05 UTC, Amrita42 commented on concepts/systemd-targets.xml
> +        These files are identified by the suffix <literal>.target</literal>
It was suggested by Frank in his feedback . But yes , when I check the rest of mod-docs , its just server , so will remove the system word

2023-10-12 08:21 UTC, Amrita42 commented on articles/systemd-basics.asm.xml
> +                Learn about &systemd; basics.
Re-phrased to give more details  and yes I have interchanged the places for what and why. 

Thanks Daria

2023-10-12 09:27 UTC, dariavladykina commented on articles/systemd-basics.asm.xml
> +                Learn about &systemd; basics.
I cannot see this update in the built doc, unfortunately

2023-10-12 10:01 UTC, dariavladykina requested changes
A small batch of suggestions, please.

2023-10-12 10:32 UTC, Amrita42 commented on articles/systemd-basics.asm.xml
> +                Learn about &systemd; basics.
Somehow it was not pushed , now it should reflect.

2023-10-12 11:17 UTC, dariavladykina requested changes

2023-10-12 11:17 UTC, dariavladykina commented on articles/systemd-basics.asm.xml
> +                dependency tracking,logging,resource management,socket activation, and system control. </para>
```suggestion
         Learn about the basics of &systemd;, which include essential functionalities such as service management, 
         dependency tracking, logging, resource management, socket activation and system control.
         </para>
```

2023-10-12 11:17 UTC, dariavladykina commented on concepts/systemd-unit-file.xml
> +         the directives; <literal>After</literal>, <literal>Wants</literal>, and <literal>Before</literal>, which are all dependencies for
```suggestion
         it is enabled or disabled. When you enable a unit file, it automatically starts at boot. Based on the specific 
         unit, there could be a dependency on other related units to work properly. For example, &chrony; requires
         the directives <literal>After</literal>, <literal>Wants</literal> and <literal>Before</literal>, which are all dependencies for
```

2023-10-12 11:17 UTC, dariavladykina commented on concepts/systemd-unit-dependencies.xml
> +          <listitem><para>If a unit A has <literal>After=unit B</literal>, when both units are run, unit B is executed fully
```suggestion
          <listitem><para>If unit A has <literal>After=unit B</literal>, when both units are run, unit B is executed fully
```

2023-10-12 11:17 UTC, dariavladykina commented on references/systemctl-cheatsheet.xml
> +      <para>You can use the following common <command>systemctl</command> common commands and refer to
```suggestion
      <para>You can use the following common <command>systemctl</command> commands and refer to
```

2023-10-12 11:17 UTC, dariavladykina commented on concepts/systemd-unit-file.xml
> +          and <literal>scope</literal> do not have a type-specific section.
```suggestion
          Note that the types <literal>device</literal>, <literal>target</literal>, <literal>snapshot</literal>
          and <literal>scope</literal> do not have a type-specific section.
```

2023-10-12 11:53 UTC, merged