Jufa/address sudo feedback
SUSE/doc-modular pull request #199
Opened 2023-09-22 09:57 UTC by jfaltenbacher

Description

Removing admin content. New xml for troubleshoot for users created

2023-09-27 10:41 UTC, jfaltenbacher commented
@janajaeger  : please add link to your article in note of section _1.2 sudo on SUSE Linux sytems_  before merging

2023-10-05 13:53 UTC, taroth21 requested changes
@jfaltenbacher : Many thanks, this is much more straightforward than the previous 'combined' article for multiple target groups! 

Nevertheless I have left some suggestions in a commented PDF on how to move some content around (please also make sure to hand over to Daria for editorial review next).

2023-10-05 13:54 UTC, taroth21 commented
@jfaltenbacher : Please find my feedback here:
[sudo-run-commands-as-superuser_feedback_taroth.pdf](https://github.com/SUSE/doc-modular/files/12819158/sudo-run-commands-as-superuser_feedback_taroth.pdf)

2023-10-09 08:17 UTC, jfaltenbacher commented
@dariavladykina : please perform a language review. Final article as PDF attached:
[sudo-run-commands-as-superuser_en.pdf](https://github.com/SUSE/doc-modular/files/12843828/sudo-run-commands-as-superuser_en.pdf)

2023-10-09 14:09 UTC, dariavladykina reviewed
Hi, please note some suggestions here. Thanks!

2023-10-09 14:09 UTC, dariavladykina commented on tasks/sudo-run-command.xml
> +      <screen>&prompt.user;<command>touch text.txt</command></screen>
```suggestion
      <screen>&prompt.user;<command>touch test.txt</command></screen>
```

2023-10-10 06:48 UTC, jfaltenbacher commented on concepts/sudo-concept.xml
> +    borrows the privileges of another user, for example the &rootuser; user.
fixed as suggested

2023-10-10 06:50 UTC, jfaltenbacher commented on concepts/sudo-concept.xml
> +    As a regular user on Linux, you have reduced permissions which is sufficient
fixed as suggested

2023-10-10 06:50 UTC, jfaltenbacher commented on concepts/sudo-concept.xml
> +    which users are allowed to run &sudo; commands and for which tasks.
fixed as suggested

2023-10-10 06:51 UTC, jfaltenbacher commented on concepts/sudo-concept.xml
> +    administrative permissions.
fixed as suggested

2023-10-10 06:52 UTC, jfaltenbacher commented on concepts/sudo-concept.xml
> +  <para>The following example explains, how the &sudo; command is used, to open
fixed as suggested

2023-10-10 06:52 UTC, jfaltenbacher commented on concepts/sudo-concept.xml
> +            returns, that &rootuser; privileges are required.
fixed as suggested

2023-10-10 06:53 UTC, jfaltenbacher commented on tasks/sudo-run-command.xml
> +      The following procedure describes how to use the &sudo; command, to copy a
fixed as suggested

2023-10-10 06:54 UTC, jfaltenbacher commented on tasks/sudo-run-command.xml
> +        You are prompted to enter the &rootuser; password. Note, that the
fixed as suggested

2023-10-10 06:54 UTC, jfaltenbacher commented on concepts/difference-between-sudo-and-su.xml
> +      elevates the privileges for anyone who knows the &rootuser; password.
fixed as suggested

2023-10-10 06:55 UTC, jfaltenbacher commented on tasks/sudo-run-command.xml
> +      <screen>&prompt.user;<command>touch text.txt</command></screen>
fixed as suggested, good catch

2023-10-10 06:56 UTC, jfaltenbacher commented on concepts/sudo-concept.xml
> +    Any user with access to the &rootuser; password can gain this privileges and
fixed as suggested

2023-10-10 06:57 UTC, jfaltenbacher commented on concepts/sudo-concept.xml
> +            Starting the <command>yast</command> command with &sudo;, prompts
fixed as suggested

2023-10-10 06:57 UTC, jfaltenbacher commented on tasks/sudo-run-command.xml
> +        The terminal returns for example:
fixed as suggested

2023-10-11 08:03 UTC, merged