systemd timers task
SUSE/doc-modular pull request #2
Opened 2021-07-30 11:32 UTC by dmpop

2021-08-02 09:14 UTC, tomschr reviewed
@dmpop Thanks Dima! I took the liberty to going through this (although it was still in a draft state). Just added some thoughts. Maybe they are useful, maybe not. :slightly_smiling_face: 

Some parts raises questions which are better targeted for our doc sle writers call.

2021-08-02 09:14 UTC, tomschr commented on xml/systemd_timers.xml
> +   </para>
Again, a calloutlist?

2021-08-03 15:58 UTC, tomschr commented on xml/systemd_timers.xml
> +Description="Foo shell script"
> I guess, there is always a tension between being general or specific. I'll bring it up in our today's SLE writers call.

The consensus of the call was to be specific with our examples.

2021-08-04 08:15 UTC, taroth21 requested changes
Hi Dima, find my review comments below. I'll add some single comments for some details in the procedure that caught my eye.

2021-08-04 08:15 UTC, taroth21 commented on xml/systemd_timers.xml
> +     Basic understanding of &systemd;.
This could contain a link to a concept topic about systemd.

2021-08-04 08:26 UTC, taroth21 commented on xml/systemd_timers.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Could you also rename the file according to l. 14-17 please?

2021-08-04 14:05 UTC, taroth21 commented on xml/systemd_timers.xml
> +   </para>
```suggestion
   Create a &systemd; service unit that controls the shell
   script. 
  </para>
```

2021-09-03 08:39 UTC, dmpop commented on xml/systemd_timers.xml
> +   </para>
I think callouts are great for complex examples. In this case, there are only four options, and the example itself is very short and simple. Doing a callout here seems like overkill. But if the majority votes for a callout, it's totally fine by me. :smile:

2021-09-03 08:39 UTC, dmpop commented on xml/systemd_timers.xml
> +   </listitem>
What about them?

2021-09-03 08:41 UTC, dmpop commented on xml/systemd_timers.xml
> +   </listitem>
Good point!

2021-09-03 08:42 UTC, dmpop commented on xml/systemd_timers.xml
> +    Save the file under the name <filename>foo.service</filename> in the directory <filename>/etc/systemd/system/</filename>.
Mentioning root access as a prerequisite should suffice, methinks.

2021-09-07 08:01 UTC, tomschr reviewed
@dmpop Some minor comments. I made it convenient with GH suggestions. Up to you to use it. Other than that, it's fine. Once you're done, merge it.

2021-09-07 08:20 UTC, merged