Draft content
SUSE/doc-modular pull request #210
Opened 2023-10-06 15:50 UTC by sounix000

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-10-25 08:38 UTC, tomschr requested changes
Thanks @sounix000! :+1:

I've added my suggestions below. :slightly_smiling_face:  Apart from that, I think the order of the sections are a bit odd IMHO. I would start like this:

1. Requirements
2. Why modify kernel boot parameters?
3. Methods of modifying kernel boot parameters
4. [...]

I think, readers want to know first what they need before they dive into all the details. Perhaps the other reviewers find even a better order.

2023-10-25 08:38 UTC, tomschr commented on xml/task-modify-kernel-boot-parameters.xml
> +  </section>
In my humble opinion, shouldn't the requirement section appear earlier?
It looks a bit out of place if it appears between sections "Methods of modifying kernel boot parameters" and "Temporarily modifying kernel boot parameters". :thinking:

2023-10-25 08:38 UTC, tomschr commented on xml/task-modify-kernel-boot-parameters.xml
> +   linuxefi /boot/vmlinuz-5.14.21-150500.53-default root=UUID=56d052b3-9148-4161-8065-3d97378d5783  <emphasis role="strong">splash=silent</emphasis> resume=/dev/disk/by-uuid/69ff0e54-23a7-4ba8-8983-5
Version numbers in screens are always problematic. In most cases, they are outdated very soon. Also mostly the exact version isn't really needed.

To reduce the maintenance, I'd suggest to replace the exact version number with a placeholder:

```suggestion
   linuxefi /boot/vmlinuz-<replaceable>KERNEL_VERSION</replaceable> root=UUID=56d052b3-9148-4161-8065-3d97378d5783  <emphasis role="strong">splash=silent</emphasis> resume=/dev/disk/by-uuid/69ff0e54-23a7-4ba8-8983-5a29c54ffa5e mitigations=auto quiet security=apparmor crashkernel=301M,high crashkernel=72M,low
```

2023-10-25 08:38 UTC, tomschr commented on xml/task-modify-kernel-boot-parameters.xml
> +          In your running system, open a shell and view the current command
You can only do it if you are root, so:

```suggestion
          In your running system, open a root shell and view the current command
```

2023-10-25 08:38 UTC, tomschr commented on xml/task-modify-kernel-boot-parameters.xml
> +  BOOT_IMAGE=/boot/vmlinuz-5.14.21-150500.53-default root=UUID=56d052b3-9148-4161-8065-3d97378d5783 splash=silent resume=/dev/disk/by-uuid/69ff0e54-23a7-4ba8-8983-5a29c54ffa5e mitigations=auto quiet
Same here with the kernel version:

```suggestion
  BOOT_IMAGE=/boot/vmlinuz-<replaceable>KERNEL_VERSION</replaceable> root=UUID=56d052b3-9148-4161-8065-3d97378d5783 splash=silent resume=/dev/disk/by-uuid/69ff0e54-23a7-4ba8-8983-5a29c54ffa5e mitigations=auto quiet security=apparmor crashkernel=301M,high crashkernel=72M,low
```

2023-10-25 08:38 UTC, tomschr commented on xml/task-modify-kernel-boot-parameters.xml
> +    <meta name="maintainer" content="" its:translate="no"/>
Depending on if you want to create an assembly or not, meta information are needed. Normally this should go into the assembly file, not in this file.

For details, see the other examples in the `articles/` directory or in file `templates/articles/assembly.asm.xml`.

2023-10-25 08:38 UTC, tomschr commented on xml/task-modify-kernel-boot-parameters.xml
> +  <section xml:id="modify-kernel-boot-parameters-reason">
Maybe start here with the requirements? :thinking:

2023-10-25 08:38 UTC, tomschr commented on xml/task-modify-kernel-boot-parameters.xml
> +      <title>Information not directly applicable to temporary changes in kernel boot parameters</title>
The "not directly applicable" makes this title a "negative" one. Can we phrase it in the reverse sense? If it's not applicable to temporary changes, maybe it's for permanent changes?

```suggestion
      <title>Information for permanent changes in kernel boot parameters</title>
```

2023-10-27 14:55 UTC, fsundermeyer requested changes
Overall, a very good first attempt. I think what is still missing, is some explanation when fiddling with Kernel parameters is need/wanted (e.g. tuning? troubleshooting, energy saving, etc). For this you should speak to SMEs.
And before this gets published, it needs to be turned into topics and an assembly,
Thanks Souvik!

2023-10-27 14:55 UTC, fsundermeyer commented on xml/task-modify-kernel-boot-parameters.xml
Yes, this needs to be split into several topics and then strung together in an assembly. Please use the repective files from the template directoty as templates for this.

2023-10-27 14:55 UTC, fsundermeyer commented on xml/task-modify-kernel-boot-parameters.xml
> +  </section>
I think we should also mention linuxrc parameters here. They are easiyl to be confusdd, because during installation they can both be passed to the system by exactly the same way. Some kind of "tip" box briefly explaining the difference and pointing to the comprehensive documentation at https://en.opensuse.org/SDB:Linuxrc is probably sufficient

2023-10-27 14:55 UTC, fsundermeyer commented on xml/task-modify-kernel-boot-parameters.xml
> +    </para>
I'd rather not explain how to fiddle with GRUB2 config files -. thzis opens Pandora's box. The prefereed way on a SUSE system is to run `yast bootload` and modify the parameters under the "Kernel Parameters" tab.

2023-10-27 14:55 UTC, fsundermeyer commented on xml/task-modify-kernel-boot-parameters.xml
> +        To temporarily disable the splash screen, proceed as follows:
It is not clear that this is just an example. I would move this into the previous paragrtaph saying: In the following example, the splash screen is temporarily disabled.

Maybe you also shopuld add and modify a parameter with this example to cover the three most common use-cases.

Also, some general rules should be mentioned, such as that parameters are separated by space. And (if applicable, not sure) how to correctly quote or escape if a value contains a space. Maybe even move this into a general introduction, because it applies to both, temporarily and permanently modifying parameters.

2023-10-27 14:55 UTC, fsundermeyer commented on xml/task-modify-kernel-boot-parameters.xml
> +          <link xlink:href="https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt"/>
Maybe move this to troubleshooting & faqs under "Where to find a list of available Kernel Parameters?"

2023-10-27 14:55 UTC, fsundermeyer commented on xml/task-modify-kernel-boot-parameters.xml
> +      subsequent boot processes.
Maybe mention that this is a good way to test or debug parameter settings?

2023-10-30 07:15 UTC, sounix000 commented on xml/task-modify-kernel-boot-parameters.xml
> +  <section xml:id="modify-kernel-boot-parameters-reason">
I have thought about the sequence of headings a bit differently:

- What is something
- Why is it useful
- How to do it
    - In how many different ways
    - Requirements/Prerequisites
    - Procedure
- Troubleshooting

If I start with `Requirements` as you have suggested, then I assume that the reader knows exactly what he wants, in which case he can always start with his section of interest, and skip reading the previous sections.

2023-10-30 07:29 UTC, sounix000 commented on xml/task-modify-kernel-boot-parameters.xml
> +    <title>Related articles</title>
@tomschr In this section (or its modified placement, as suggested by Frank), I would like to replace `&suselinux;` with `&productname`. But the problem is that the outgoing URLs are valid only for SLES. Is there a mechanism to wrap different URLs within conditionals, so that the correct one is rendered based on the `&productname;`?

2023-10-31 11:02 UTC, tomschr commented on xml/task-modify-kernel-boot-parameters.xml
> +    <title>Related articles</title>
@sounix000 The only mechanism that comes to my mind is _profiling_ (the same what we do in SLE). I think that could be applied here.

You cannot select for product name value(s) directly, but you can do it in an indirect way through profiling attributes. Those attributes are available on _every_ DocBook element. Find a list in the [DocBook reference](https://tdg.docbook.org/tdg/5.2/ref-elements#common.effectivity.attributes). Don't get confused, they use the term "_effectivity attributes_", but the older term is _profiling attributes_. Both are the same.

For your use case you have two variants: SLES and non-SLES. These are your two variants. It would make sense to use `os` attribute as a profing attribute (others would be also possible, it's a matter of semantic and taste).

Once you know your variants and your profiling attribute, you add them to elements, be it inline elements like links, filenames, product names, or whole chapters, section, or topics. You don't add your profiling attribute(s) if they are valid for all variants.

For example:

```xml
<productname os="sles">Productname for SLES</productname>
<productname os="non-sles">Productname for non SLES</productname>

<!-- same with links --->
<para>
Find details about our products at
  <link xlink:href="http://www.example.com/sles" os="sles"/>
  <link xlink:href="http://www.example.com/other" os="non-sles"/>
and win a lottery!
</para>
<para os="sles">For SLES, keep in mind...</para>
```

Depending on what you set in the `PROFOS` variable of your DC file, you get either one. If you want to create a document for SLES, all non-SLES structures are filtered out (and vice-versa).

Tomas did the exact same profiling mechanism for ALP. He created two different variants ("alp-dolomite" and "alp-deployment-agama-interactive") and used the `condition` attribute.

Hope that helps.

2023-11-16 08:54 UTC, sounix000 commented on xml/task-modify-kernel-boot-parameters.xml
> +  </section>
The usual practice is to place the Requirements section just before the actual Procedure. I have followed that practice.

2023-11-17 06:56 UTC, sounix000 commented on xml/task-modify-kernel-boot-parameters.xml
> +          <link xlink:href="https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt"/>
I think a separate section for "Related Articles" gives better visibility, and aligns with the conventions used in other smart docs or guides. I am retaining the current placement for the time being.

2023-11-20 09:35 UTC, taroth21 commented
@sounix000 : Thanks, I had sent my review via mail shortly after you had asked for feedback.

2023-11-24 07:20 UTC, sounix000 commented on xml/task-modify-kernel-boot-parameters.xml
> +          <literal>acpi=</literal>: Toggles the Advanced Configuration and
I get your point - it brings more clarity on the spot, without the reader having to refer to any other documentation. 
But my baseline expectation is that when dealing with something as serious as kernel boot parameters, the reader should know what they want to do, which in this case is using a flag or passing desired values to an argument. 
My goal here is to simply tell them how to do it in the context of SUSE Linux. In any case, the Related Articles section at the bottom has a link to kernel documentation that explains what you suggested: https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt
Duplicating the information from the official kernel docs is a maintenance overhead that we might want to avoid.

2024-01-15 16:29 UTC, taroth21 requested changes
Thanks for overhauling and very well done! I know the editorial review is still to follow after the content review. Nevertheless, I included some code suggestions for typos or other small things that I spotted during the content review. More feedback to come via mail - many thanks!

2024-01-15 16:29 UTC, taroth21 commented on articles/kernel-boot-parameters-modify.asm.xml
> +                It 15 minutes to fully understand the concepts and the process,
```suggestion
                It takes 15 minutes to fully understand the concepts and the process,
```

2024-01-15 16:29 UTC, taroth21 commented on articles/kernel-boot-parameters-modify.asm.xml
> +                effect after reboot.
```suggestion
                and 5 minutes to modify kernel boot parameters and observe their
                effect after reboot.
```

2024-01-15 16:29 UTC, taroth21 commented on articles/kernel-boot-parameters-modify.asm.xml
> +                    processes, you should have <literal>root</literal> or
```suggestion
                    processes, you need to have <literal>root</literal> or
```

2024-01-15 16:29 UTC, taroth21 commented on articles/kernel-boot-parameters-modify.asm.xml
> +                    processes, you should have <literal>root</literal> or
I think 'should have' is not strong enough here - without root privileges, it does not work.

2024-01-15 16:29 UTC, taroth21 commented on concepts/kernel-boot-parameters-modify-introduction.xml
> +      configure certain features and make hem behave in the intended manner.
```suggestion
      configure certain features and make them behave in the intended manner.
```

2024-01-15 16:29 UTC, taroth21 commented on concepts/kernel-boot-parameters-modify-introduction.xml
> +      consider few of the most commonly modified kernel boot parameters:
```suggestion
      to customize your boot process. Among the most commonly modified kernel boot parameters are:
```

2024-01-15 16:29 UTC, taroth21 commented on concepts/kernel-boot-parameters-modify-introduction.xml
> +          <literal>nomodeset</literal>: Disables kernel mode setting.
```suggestion
          <literal>nomodeset</literal>: Disables kernel mode settings.
```

2024-01-15 16:29 UTC, taroth21 commented on tasks/kernel-boot-parameters-modify-temporary.xml
> +    <tip>
```suggestion
    <warning><title>Risk of unusable system</title> 
```

2024-01-15 16:29 UTC, taroth21 commented on tasks/kernel-boot-parameters-modify-temporary.xml
> +    <tip>
I would definitely make this a warning and add a title

2024-01-15 16:29 UTC, taroth21 commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +      should have <literal>root</literal> or equivalent administrative
```suggestion
      need <literal>root</literal> or equivalent administrative
```

2024-01-15 16:29 UTC, taroth21 commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +      <step>
Not sure if the first two steps are really needed.

2024-01-15 16:29 UTC, taroth21 commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +        <para>
Our style guide recommends to avoid root prompts and use sudo where applicable - see https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-prompt

2024-01-15 16:29 UTC, taroth21 commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +<screen>&prompt.root;<command>yast bootloader</command></screen>
```suggestion
<screen>sudo <command>yast bootloader</command></screen>
```

2024-01-15 16:29 UTC, taroth21 commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +          <guimenu>System</guimenu> &gt; <guimenu>Boot Loader</guimenu>.
```suggestion
          Alternatively, open &yastcc; and select <menuchoice>
          <guimenu>System</guimenu><guimenu>Boot Loader</guimenu></menuchoice>.
```

2024-01-15 16:29 UTC, taroth21 commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +          <guimenu>System</guimenu> &gt; <guimenu>Boot Loader</guimenu>.
If you use <menuchoice> with multiple <guimenu> elements inside, our style sheets automatically render the arrow symbol between them.

2024-01-15 16:29 UTC, taroth21 commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +          field.
```suggestion
          field:
```

2024-01-16 05:42 UTC, tomschr commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +<screen>&prompt.root;<command>yast bootloader</command></screen>
@taroth21 Shouldn't we use the entity `prompt.sudo` from `common/generic-entities.ent` here?

2024-01-19 14:48 UTC, sounix000 commented on articles/kernel-boot-parameters-modify.asm.xml
> +                    processes, you should have <literal>root</literal> or
I am replacing `should` with `must` - an even stronger term compared to `need to`. I think Daria will also have similar suggestion.

2024-01-19 14:57 UTC, sounix000 commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +      <step>
Removed the first one, but retained the second step about starting YaST. I think it's necessary.

2024-01-19 14:58 UTC, sounix000 commented on tasks/kernel-boot-parameters-modify-permanent.xml
> +<screen>&prompt.root;<command>yast bootloader</command></screen>
used `prompt.sudo;` as suggested by Toms.

2024-11-19 19:44 UTC, sounix000 commented
NEW PR: https://github.com/SUSE/doc-modular/pull/373

IGNORE THIS PR 

CLOSING THIS PR

2024-11-19 19:44 UTC, closed without merging