Jufa/sudo basics
SUSE/doc-modular pull request #22
Opened 2021-09-13 13:46 UTC by jfaltenbacher

as discussed here are the three new articles created from 
https://documentation.suse.com/sles/15-SP3/html/SLES-all/cha-adm-sudo.html#sec-sudo-conf

any feedback welcome :)

2021-09-13 16:01 UTC, tomschr requested changes
@jfaltenbacher Sorry for the many comments and suggestions. :wink: I found some inconsistencies and things which should be avoided. Nevertheless, I've learned a lot of things about sudo. :+1: Thanks!

2021-09-14 17:26 UTC, jfaltenbacher commented on xml/concept-sudo.xml
> +    In order to execute certain commands, you need root privileges. On each
changed

2021-09-14 17:28 UTC, jfaltenbacher commented on xml/concept-sudo.xml
> +    available to log in as <function>root</function> user:
for Linux, I'd prefer the tag as this will then also be locked for translation and will not go into the wordcount
Thanks for the rootuser entity, I wasn't aware of that and changed it throughout all three documents

2021-09-14 17:33 UTC, jfaltenbacher commented on xml/concept-sudo.xml
> +     <function>root</function> password. All commands executed with
changed

2021-09-14 17:34 UTC, jfaltenbacher commented on xml/concept-sudo.xml
> +     require the <function>root</function> password. All commands executed with
changed as suggested

2021-09-14 17:36 UTC, jfaltenbacher commented on xml/concept-sudo.xml
> +  </note>
yeah, this is tricky since the rootuser and sudo need to be explained first I'd say

2021-09-14 17:37 UTC, jfaltenbacher commented on xml/concept-sudo.xml
> +   <productname>Linux</productname> distribution.
oh yes, I use the entity :)

2021-09-14 17:38 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +   article explains how &sudo; can be configured to your needs.
changed as suggested

2021-09-14 17:39 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +  <section xml:id="task-configuring-sudo-intro-sudoers-config">
ok, yes that was also my thought. Will do this after this merge

2021-09-14 17:41 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +     <filename>/etc/sudoers</filename>.
added as suggested

2021-09-14 17:43 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +    may break updates. Therefore, it is recommended to put custom configuration
changed as suggested

2021-09-14 17:43 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +    into files in the <filename>/etc/sudoers.d/</filename> directory. Use the
changed as suggested

2021-09-14 17:48 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +   <screen>sudo EDITOR=<replaceable>/usr/bin/nano</replaceable> visudo</screen>
converted into own section and moved down to the Instructions part. But very short section of only a few lines now.

2021-09-14 17:50 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +   </screen>
changed as suggested and I will try to memorize

2021-09-14 17:57 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +   </screen>
also changed for all occurrences in all 3 xmls

2021-09-14 17:57 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +      </screen>
changed

2021-09-14 17:57 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +      </screen>
changed

2021-09-14 17:57 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +    User_List Host_List = [(User_List)] [NOPASSWD:|PASSWD:] Cmnd_List
changed

2021-09-14 17:58 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +       /usr/bin/foo ""  # No arguments allowed
changed

2021-09-14 18:01 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +   <screen>&exampleuser_plain; ALL = NOPASSWD: ALL</screen>
right, but it is also mentioned in the concept that the biggest and only difference between sudo and su is that you either need to know the password or not. But I am totally with you that this is not advisable. Maybe adding a note, saying that we do not recommend that would be a workaround?

2021-09-14 18:04 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +    <productname>Linux</productname> distribution.
changed as suggested in all three xmls

2021-09-14 18:05 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +  </para>
will add this with next PR

2021-09-14 18:07 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> + <title>Working with &sudo;</title>
ok, section removed

2021-09-14 18:09 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +    root
changed as suggested

2021-09-14 18:11 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +      password again.
removed

2021-09-14 18:11 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +     bash: /proc/1/maps: Permission denied
changed

2021-09-14 18:12 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +     sudo dd if=/proc/1/maps | cat <!-- TODO: Better example! -->
will check for next PR (I wonder for how long this todo has been in there...)

2021-09-14 18:13 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +     <term><literal>sudo -s (&lt;command&gt;)</literal>
iieks, I dislike literal anyhow - changed as suggested

2021-09-14 18:20 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +     <term><literal>sudo -i (&lt;command&gt;)</literal>
changed as suggested

2021-09-14 18:21 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +      # %wheel ALL=(ALL) NOPASSWD: ALL
changed

2021-09-14 18:22 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +    A simple workaround is to use xhost to temporarily allow the root user
changed as suggested

2021-09-14 18:22 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> + </section>
yep, maybe with next PR

2021-09-15 06:41 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +   <para>
I don not quit understand, let's discuss this

2021-09-15 06:42 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +   content of this xml to concept-sudo.xml</remark>
will do with next PR

2021-09-15 06:43 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +      current user.
will leave as it is

2021-09-15 07:22 UTC, jfaltenbacher commented on xml/task-configuring-sudo.xml
> +      </screen>
to be done next time

2021-09-15 07:23 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +      running the <command>groups <replaceable>USERNAME</replaceable></command>
to be done next time

2021-09-15 07:23 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +      comment out the default rule.
to be done next time

2021-09-15 07:25 UTC, jfaltenbacher commented on xml/task-working-sudo.xml
> +  </procedure>
step added

2021-09-15 07:29 UTC, tomschr commented on xml/task-configuring-sudo.xml
> +   <para>
Sorry if this wasn't clear. Sure,  it's better to discuss this in person. Meanwhile, this is what I had in mind:

https://openbuildservice.org/help/manuals/obs-user-guide/art.obs.bg.html#sec.obsbg.obsconfig

2021-09-15 07:40 UTC, jfaltenbacher commented
fixes from language and content review

2021-09-15 07:41 UTC, merged

2021-09-15 11:37 UTC, jfaltenbacher commented on xml/concept-sudo.xml
> +   <title>&sudo;: concept and basics</title>
need to be changed to sudo: basic concept

2021-09-15 11:39 UTC, jfaltenbacher commented on xml/concept-sudo.xml
> + * product all
_all_ will not work, needs to be changed

2021-09-16 06:29 UTC, jfaltenbacher commented on xml/concept-sudo.xml
> +   <title>&sudo;: concept and basics</title>
fixed