Basic concepts of Snapper
SUSE/doc-modular pull request #230
Opened 2023-10-30 15:28 UTC by dariavladykina

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-11-03 13:58 UTC, dariavladykina commented
@fsundermeyer, @tomschr please kindly review this first try on Snapper. Thanks!

2023-11-03 16:45 UTC, tomschr requested changes
@dariavladykina Thanks for the efforts! :+1: 

It's a good start. :+1:  Was it just to convert the old doc to the new topic format or was the task also to add some more text? 

I think, some tasks are missing. Maybe you could add them in a second step. For example:

* Include/exclude directories considered for a snapshot
* Listing all available snapshots
* Recovering a snapshot
* Removing an "outdated"/old snapshot (to regain the space)
* Using Snapper to restore files

Certainly there are more.

2023-11-03 16:45 UTC, tomschr commented on articles/snapper-basic-concepts.asm.xml
> +    <!-- pull in a topic as is -->
Remove:

```suggestion
```

2023-11-06 10:09 UTC, dariavladykina commented on articles/snapper-basic-concepts.asm.xml
> +        <revision><revnumber>1</revnumber><date>2023-11-11</date>
```suggestion
        <revision><date>2023-11-11</date>
```

2023-11-06 10:10 UTC, dariavladykina commented on articles/snapper-basic-concepts.asm.xml
> +        <revision><revnumber>1</revnumber><date>2023-11-11</date>
```suggestion
        <revision><date>2023-11-11</date>
```

2023-11-06 10:11 UTC, dariavladykina commented on articles/snapper-basic-concepts.asm.xml
> +      <title>The Basic Concepts of Snapper</title>
Shall I create it in [Product entities](https://github.com/SUSE/doc-modular/blob/main/common/product-entities.ent)?

2023-11-06 12:59 UTC, dariavladykina commented on concepts/snapper-basic-concept.xml
> +    thinly provisioned LVM volumes with an XFS or Ext4 file system.</para>
```suggestion
    thinly provisioned LVM volumes with an XFS file system.</para>
```

2023-11-06 12:59 UTC, dariavladykina commented on concepts/snapper-basic-concept.xml
> +        Thinly provisioned LVM volumes formatted with XFS or Ext4.
```suggestion
        Thinly provisioned LVM volumes formatted with XFS.
```

2023-11-24 12:50 UTC, dariavladykina commented on references/snapper-snapshot-types.xml
> +         (<quote>Post</quote>). In case an important system component such as the
```suggestion
         (<quote>pre</quote>) and another one after the installation has finished
         (<quote>post</quote>). In case an important system component such as the
```

2023-11-24 12:50 UTC, dariavladykina commented on references/snapper-snapshot-types.xml
> +         another when the module is closed (<quote>Post</quote>). Old snapshots
```suggestion
         created: one when a &yast; module is started (<quote>pre</quote>) and
         another when the module is closed (<quote>post</quote>). Old snapshots
```

2023-12-07 15:48 UTC, janajaeger commented on concepts/snapper-default-setup.xml
> +  <para>Snapper on &sles; is set up as an undo and recovery tool for system
Are you sure that it just applies to SLES?

2023-12-07 16:10 UTC, janajaeger reviewed
Just a few minor issues. I've yet to build the article and read it as it is supposed to be read. Great job!

I'm having slight issues with the sheer number of links pointing to content outside of the article. You'll have to balance losing your readers to another article vs. providing them with vital information.

2023-12-07 16:36 UTC, janajaeger commented on concepts/snapper-basic-concept.xml
> +        information, see <!-- Change section link/name <xref linkend="sec-snapper-snapshot-boot"/>.-->
Now that I have read the entire piece,  I have also a few smallish structural issues with it:

- The article isn't self-contained (too many links pointing out from all over the place). This could be fixed by adding a "For more information" section at the end that serves two purposes. It rounds of the article and it bundles the links in one spot (at the end when the reader should have read the entire article, anyway). Whether you can bundle of all the links there, remains to be seen.
- The article could use something of a sneak preview section that hints at the fact that there are other articles out there and that more advanced stuff is covered there.

2023-12-27 14:45 UTC, dariavladykina commented on concepts/snapper-default-setup.xml
> +            Configuration <filename>/etc/snapper/configs/root</filename> (0 single) is created automatically.
I have added a screen for visibility and a note to explain number and type of a snapshot.

2023-12-27 14:47 UTC, dariavladykina commented on concepts/snapper-basic-concept.xml
> +        information, see <!-- Change section link/name <xref linkend="sec-snapper-snapshot-boot"/>.-->
Done, thanks!

2023-12-27 14:50 UTC, dariavladykina commented
@tomschr, thank you very much for your additions! Indeed, this is just the beginning of a series of articles that are supposed to be parts of a larger theme and to reference each other. So I hope we can find a way to make this clear for readers (as @janajaeger correctly pointed out) - I can see the imperfection now!

2024-01-22 11:09 UTC, tomschr approved these changes
~Looks fine to me, but I'm not a snapper expert.~ :wink:
Ignore it. Was the wrong PR to approve.

2024-02-02 14:02 UTC, fsundermeyer requested changes
In general, I think the following structure of the article would better help people understanding the topic:

1. What are snapshots (note that snapshots are a btrfs feature and have got nothing to do with snapper)
2. What is snapper and what can it do
3. How is snapper setup by default on SUSE

2024-02-02 14:02 UTC, fsundermeyer commented on references/snapper-snapshot-types.xml
> +  <title>Types of snapshots</title>
earlier?

2024-02-13 16:13 UTC, dariavladykina commented on concepts/snapper-default-setup.xml
> +<para>This is the list of snapshots directly after a fresh installation of a system with a root partition > 16 GB:</para>
```suggestion
<para>This is the list of snapshots directly after a fresh installation of a system with a root partition &gt; 16 GB:</para>
```

2024-02-13 16:15 UTC, dariavladykina commented on concepts/snapper-default-setup.xml
> +      By default, snapshots are disabled on partitions other than <filename>/</filename>.
```suggestion
      (16&nbsp;GB or more), taking snapshots for the root partition <filename class="directory">/</filename> is enabled automatically during installation. 
      ```

2024-02-27 10:54 UTC, dariavladykina commented
[snapper-basic-concepts_en.pdf](https://github.com/SUSE/doc-modular/files/14418346/snapper-basic-concepts_en.pdf)

2024-03-05 12:59 UTC, lvicoun requested changes
Good job!
Besides my notes, any idea if YAST will be part of SLE16?

2024-03-07 12:40 UTC, dariavladykina commented on articles/snapper-basic-concepts.asm.xml
> +                    of the root partition depends on the product. We strongly recommend 50&nbsp;GB or more.
I have added a note how to check this size in 'Default' section.

2024-03-11 11:16 UTC, merged