Using Snapper to undo changes
SUSE/doc-modular pull request #232
Opened 2023-11-06 15:00 UTC by dariavladykina

This is the second article from the series that aims to merge and update the content about [Snapper from the Admin Guide](https://documentation.suse.com/sles/15-SP5/single-html/SLES-administration/#cha-snapper).

2023-12-11 15:00 UTC, janajaeger commented on articles/snapper-undo-changes.asm.xml
> +      <description>For more information</description>
Not that it matters, but "For more information" isn't the proper description for this glue topic?

2023-12-11 15:09 UTC, janajaeger commented on concepts/snapper-undo-changes-intro.xml
> +    <title>Default configuration</title>
Find a different title, maybe? "Default configuration" is a bit non-descriptive.

2023-12-11 15:32 UTC, janajaeger commented on glues/snapper-undo-changes-compare-undo-and-rollback.xml
Very nice topic! The only issue that I have is with the links to non-existing sections or yet-to-be-written articles. Even if they are resolved one day, the disrupt the flow and might make readers jump from this article and never come back.

Only add those links when the reader absolutely needs this reference to proceed with what you're describing. Otherwise put'em right to the end of the article under "For more info".

2023-12-11 15:33 UTC, janajaeger commented on glues/snapper-undo-changes-more-info.xml
Either keep out of the article until you have something to point to or activate this section and let it point to the respective sections in the legacy docs.

2023-12-11 15:54 UTC, janajaeger commented on tasks/snapper-undo-changes-restore-files.xml
> +  <warning>
Maybe word this a bit more strongly. Stress the fact that the readers have to actually do something.

2023-12-11 16:00 UTC, janajaeger commented on tasks/snapper-undo-changes-restore-files.xml
> +    <para>To use the restore feature, timeline snapshots for the root partition
timeline snapshot = backup snapshot?

2023-12-11 16:06 UTC, janajaeger commented on tasks/snapper-undo-changes-restore-files.xml
> +      This restriction only affects snapshots taken from the root file system.
Why does it do that?

2023-12-11 16:25 UTC, janajaeger reviewed
Great job! 

As with the first piece, I'm having issues with the sheer abundance of links leading out from the article from pretty much any point. I suggest reviewing every single one of them and trying to determine whether they are needed at that time at all or whether they'd work better at the end.

The article starts a bit out of the blue. It doesn't really have a proper intro that gently states what the thing is all about.

That's about all I could find. Looking forward reading to the entire set of snappery Smart Docs!

2023-12-12 07:27 UTC, tomschr requested changes
Great article, Daria! :+1:  I have some minor issues. Hope they make sense. :slightly_smiling_face:

2023-12-12 07:27 UTC, tomschr commented on concepts/snapper-undo-changes-intro.xml
> +      (<literal>re</literal>).
Maybe refer to https://docs.python.org/3/library/re.html if you want your readers to get more information about regular expressions in Python.

2023-12-12 07:27 UTC, tomschr commented on concepts/snapper-undo-changes-intro.xml
> +11 &lt;/snapper-zypp-plugin-conf&gt;</screen>
Additionally, it would be nice to see an example with `match="re"`.

2023-12-12 07:27 UTC, tomschr commented on concepts/snapper-undo-changes-intro.xml
> +    installed (line 9). When the kernel, dracut, glibc, systemd, or udev packages
As I've shown above, avoid refer to line numbers. They can change very easily and you forget to adapt it here. Maintenance nightmare is awaiting you! :wink: 

If you want to refer to the "line number", I'd recommend to refer to the callout:

```suggestion
    installed (see <xref linkend="zypp-conf-packages"/>). When the kernel, dracut, glibc, systemd, or udev packages
```

Maybe not exactly the same, but it creates a link so users can click and browser jumps to the line.

2023-12-12 07:27 UTC, tomschr commented on concepts/snapper-undo-changes-intro.xml
> +    as important (lines 4 to 8). All rules are evaluated.
Same here (line numbers).

2023-12-12 07:27 UTC, tomschr commented on glues/snapper-undo-changes-compare-undo-and-rollback.xml
> +        there are two fundamentally different scenarios Snapper can handle:
Use entity from doc-kit?

```suggestion
        there are two fundamentally different scenarios &snapper; can handle: 
```

If you want to use it, make a search-and-replace of all your texts.

2023-12-12 07:27 UTC, tomschr commented on glues/snapper-undo-changes-compare-undo-and-rollback.xml
> +      you want to revert that change, you can use the <command>undochange</command>
Remove filler words?

```suggestion
      you want to revert that change, use the <command>undochange</command> 
```

2023-12-12 07:27 UTC, tomschr commented on glues/snapper-undo-changes-compare-undo-and-rollback.xml
> +      When doing rollbacks as described in <!--<xref linkend="sec-snapper-snapshot-boot"/> -->,
Just to be on the safe side:

```suggestion
      When doing rollbacks <!-- as described in <!--<xref linkend="sec-snapper-snapshot-boot"/> -->, 
```

2023-12-12 07:27 UTC, tomschr commented on tasks/snapper-undo-changes-yast-zypper.xml
> +     </para>
I feel, the command and its signature is a bit unfortunate to be placed inline. Maybe split them into a `screen` like this:

```suggestion
     <para>
      To display the diff for a certain file, run <command>snapper
      diff</command>. It follows this syntax:
     </para>
     <screen>snapp diff <replaceable>PRE</replaceable>..<replaceable>POST</replaceable> [<replaceable>FILENAME</replaceable>]
     <para>If you do not specify a
      <replaceable>FILENAME</replaceable>, a diff for all files will be
      displayed.
     </para>
```

2023-12-12 07:27 UTC, tomschr commented on tasks/snapper-undo-changes-yast-zypper.xml
> +     undoing change done</screen>
Just to be on the safe side: are the lines in the output really indented?

2024-01-04 13:53 UTC, dariavladykina commented on articles/snapper-undo-changes.asm.xml
> +        <revision><date>2023-11-11</date>
```suggestion
        <revision><date>2024-01-04</date>
```

2024-01-04 13:55 UTC, dariavladykina commented on articles/snapper-undo-changes.asm.xml
> +      <description>For more information</description>
```suggestion
      <description>Comparing rollback and undoing changes</description>
```

2025-04-09 11:19 UTC, lvicoun reviewed
Dasha, some suggestions :)

2025-04-09 11:19 UTC, lvicoun commented on concepts/snapper-undo-changes-intro.xml
> +    <title>Default configuration</title>
I'd suggest something like Snapper and snapshots as a title here as it does not only provide info about the default configuration, but about snapper itself and snapshots.

2025-04-09 11:19 UTC, lvicoun commented on glues/snapper-undo-changes-compare-undo-and-rollback.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Nice one! It looks like a concept to me :)

2025-04-09 11:19 UTC, lvicoun commented on tasks/snapper-undo-changes-yast-zypper.xml
> +     <para>
I'd move this para to the first section, where you provide details about Snapper. There you can match the snapshot with pre and post install snapshots IMHO you can directly start with the second para.

2025-04-09 11:19 UTC, lvicoun commented on concepts/snapper-undo-changes-intro.xml
> +   <para>By default, automatic snapshots as described above are configured for the
I know it was planned to write another article about the custom configuration, but as it is not available now I suggest to comment out this sentence for now.

2025-04-09 11:19 UTC, lvicoun commented on concepts/snapper-undo-changes-intro.xml
> +      This line unconditionally matches all packages.
```suggestion
      This line unconditionally matches all packages without marking the snapshot important.
```

2025-04-09 11:19 UTC, lvicoun commented on concepts/snapper-undo-changes-intro.xml
> +    With this configuration snapshot, pairs are made whenever a package is
```suggestion
    With this configuration, snapshot pairs are made whenever a package is
```

2025-04-09 12:04 UTC, dariavladykina commented on concepts/snapper-undo-changes-intro.xml
> +   </para>
```suggestion
   </para> -->
```

2025-04-10 12:52 UTC, merged