Added the draft of prepare statement.
SUSE/doc-modular pull request #234
Opened 2023-11-13 11:59 UTC by lvicoun

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#...
* https://jira.suse.com/browse/SMO-262?jql=issue%20in%20(SMO-295%2C%20SMO-293%2C%20SMO-285%2C%20SMO-262%2C%20SMO-248%20%2C%20PED-7180%2C%20PED-7144%2C%20PED-6478%20%2C%20SMO-291%20%2C%20PED-7186%20%2C%20PED-7187%20)

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-11-21 10:29 UTC, lvicoun commented
[alp-dolomite_en.pdf](https://github.com/SUSE/doc-modular/files/13425009/alp-dolomite_en.pdf)

Please, see section 2.7.5.3.1.1.

2023-11-21 10:45 UTC, Vogtinator commented
Not new in this PR but should be fixed anyway: `<screen>#!/usr/bin/bash</screen>` should be `<screen>#!/bin/bash</screen>`.

The paragraph is wrong anyway, it's not always bash. It could also be `/bin/sh` or some other available shell. Only sh and bash are guaranteed to be there though.

2023-11-21 10:49 UTC, Vogtinator commented
IMO this should be after the "Network configuration" section. The first section should mention that `# combustion: network` is necessary if the combustion script needs network access (package installation, registration, ...) and defaults to DHCP. If some other network configuration is needed, that's what `prepare` is for.

2023-11-21 10:49 UTC, Vogtinator commented on references/combustion-configuration.xml
> +          #!/bin/bash
Too much indentation

2023-11-21 10:54 UTC, lvicoun commented
> Not new in this PR but should be fixed anyway: `<screen>#!/usr/bin/bash</screen>` should be `<screen>#!/bin/bash</screen>`.
> 
> The paragraph is wrong anyway, it's not always bash. It could also be `/bin/sh` or some other available shell. Only sh and bash are guaranteed to be there though.

Thanks! for spotting this!

2023-11-21 12:09 UTC, lvicoun commented on references/combustion-configuration.xml
> +          #!/bin/bash
Thanks for mentioning, that should be fixed after proper source file formatting, but I didn't want to do it now as it might cause many changes in the file and making the content changes almost invisible.

2023-11-21 12:21 UTC, Vogtinator commented on references/combustion-configuration.xml
>          As the <filename>script</filename> file is interpreted by Bash, always
Not true, that depends on the shebang

2023-11-21 12:21 UTC, Vogtinator commented on references/combustion-configuration.xml
> +<screen>#!/bin/<replaceable>INTERPRETER</replaceable></screen>
IMO that's too much detail on something not really important. Would it be enough to write something like "Is executed as script file and needs to start with a shebang like `#!/bin/bash`"?

2023-11-21 12:21 UTC, Vogtinator commented on references/combustion-configuration.xml
> +        You may need to perform changes to the initramfs, for example, to write a custom network configuration for &nm; into
Might be misleading, as the initramfs file itself is not modified.

```suggestion
        You may need to perform changes to the initramfs environment, for example, to write a custom network configuration for &nm; into
```

2023-11-21 12:21 UTC, Vogtinator commented on references/combustion-configuration.xml
> +          For example, to create a static connection and configure DNS and IP address:
The connection isn't static, the IP configuration is

2023-11-21 12:24 UTC, tbazant requested changes
looks good, 2 minor suggestions though

2023-11-21 12:24 UTC, tbazant commented on references/combustion-configuration.xml
> +  <literal>sh</literal>. We cannot guarantee that other interpereters are available.
This is confusing, if it's always BASH, why generalize with INTERPRETER? If it might be SH, then why 'As the script file is interpreted by BASH'?

2023-11-21 12:24 UTC, tbazant commented on references/combustion-configuration.xml
> +        argument to dracut. The network configuration defaults to use DHCP, if other network
```suggestion
        argument to dracut. The network configuration defaults to use DHCP. If other network
```

2023-11-21 13:00 UTC, lvicoun commented on references/combustion-configuration.xml
> +  <literal>sh</literal>. We cannot guarantee that other interpereters are available.
As stated above, the sentence is incorrect as it may be bash or sh.

2023-11-21 15:30 UTC, dariavladykina reviewed
Hi, please see some comments here. Thanks!

2023-11-21 15:30 UTC, dariavladykina commented on references/combustion-configuration.xml
>        secure password. If you use a randomly generated password, use at least
```suggestion
      secure password. For a randomly generated password, use at least
```

2023-11-21 15:30 UTC, dariavladykina commented on references/combustion-configuration.xml
> +          For example, to create a connection with a static IP adderess and configure DNS:
```suggestion
          For example, to create a connection with a static IP address and configure DNS:
```

2023-11-21 15:30 UTC, dariavladykina commented on references/combustion-configuration.xml
> +        argument to dracut. The network configuration defaults to use DHCP. If other network
```suggestion
        argument to dracut. The network configuration defaults to using DHCP. If a different network
```

2023-11-21 15:30 UTC, dariavladykina commented on references/combustion-configuration.xml
> +        start the file with the interpreter declaration at its first line. For example, in case of Bash:
```suggestion
        As the <filename>script</filename> file is interpreted by the shell, always
        start the file with the interpreter declaration on its first line. For example, in case of Bash:
```

2023-11-22 06:33 UTC, merged

2023-11-22 07:32 UTC, Vogtinator commented on references/combustion-configuration.xml
> +        If you do not use the statement, the system will be configured without
This can be misleading: The configuration process (i.e. the combustion script) doesn't have a network configuration but the system itself still does.