adds the systemd boot process concept topic
SUSE/doc-modular pull request #235
Opened 2023-11-15 09:46 UTC by Amrita42

### Description

To tell the reader about what happens during the systemd boot process

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-12-13 05:56 UTC, Amrita42 commented
@fsundermeyer @taroth21 @tomschr @janajaeger please review . Thanks

2023-12-13 07:35 UTC, tomschr requested changes
Good start, thank you Amrita! :+1: 

I have some comments, maybe it's too early in the morning and I got it wrong. :smile: Let's see what the others say.

2023-12-13 07:35 UTC, tomschr commented on concepts/systemd-boot-process.xml
> +initiating and terminating services, etc. </para>
I think I know what you wanted to say. But the first three sentence was a bit confusing for me or at least ambiguous. It sounded like they are contradicting each other.

I stumbled upon the "systemd manages the boot process on a Linux system" sentence. Although you are not entirely wrong, I think it depends on how you define "_boot process_". The term is not clearly defined in your article and it sounds to me you are mixing different stages of the boot process.

My suggestion would be to mention/explain the different stages of the boot process in a list. In the article [_A Basic Guide to Linux Boot Process_](https://www.tecmint.com/linux-boot-process/) from 2020, they identified these steps:

1. **BIOS**
   This is the first step after you switch on your computer. Usually it performs also an integrity check, depending on the BIOS settings. The BIOS also probes for all hardware such as HDD/SDD, RAM, and keyboard.
2. **Bootloader (GRUB)**
  Once BIOS is successfully finished, BIOS probes the MBR (Master Boot Record) for the bootloader and disk partitioning information. Once BIOS locates the bootloader, it's loaded into RAM and executed.
3. **Kernel boot**
  Once GRUB (or any other bootloader) succeeds in loading the Linux kernel, it self-extracts, mounts the root file system, and initializes the /sbin/init program commonly referred to as init.
4. **Systemd**
  The kernel finally loads systemd which runs all the other initialization processes.

That's roughly the steps what it takes.

Introduce it as "the Linux boot process". After you've introduced this list to the readers, then you could refer to step 4 and explain the systemd part of the whole boot process.

Does it make sense?

2023-12-13 07:35 UTC, tomschr commented on concepts/systemd-boot-process.xml
> +  <para>You can use the <command>systemd-analyze</command> command to analyze the performance of the system
Removed filler words:

```suggestion
  <para>Use the <command>systemd-analyze</command> command to analyze the performance of the system
```

2023-12-13 07:35 UTC, tomschr commented on concepts/systemd-boot-process.xml
> +      </variablelist>
Maybe mention the `systemd-analyze plot` command for people who likes more a visual representation?

2024-01-05 16:37 UTC, taroth21 commented on concepts/systemd-boot-process.xml
> +initiating and terminating services, etc. </para>
I agree with @tomschr that a brief description of the general stages of the boot process would be useful before you dig into the systemd-specific part of the boot process.

2024-01-05 16:51 UTC, taroth21 requested changes
Hi Amrita, many thanks! I left some minor comments.

2024-01-05 16:51 UTC, taroth21 commented on concepts/systemd-boot-process.xml
> +    <section xml:id="systemd-performance-analysis">
Are you planning to add more subsections to the systemd boot process topic? If not, this section (rendered as '2.1 System boot performance analysis') would be what our former editor would have called a 'lonely section'. She would have considered this a structural issue and would have advised to 

- either integrate the contents of the lonely section directly into the parent section (and remove the lonely section)

- or (if it makes sense) to add one ore more subsections so there are parallel structures like 2.2, 2.3 etc.

2024-01-05 16:51 UTC, taroth21 commented on concepts/systemd-boot-process.xml
> +  started and running. You can log in and start using the system. &systemd; runs in the background, managing and
```suggestion
  started and running. You can log in and start using the system. From this point on, &systemd; runs in the background, managing and
```

2024-01-05 16:51 UTC, taroth21 commented on concepts/systemd-boot-process.xml
> +<para>&systemd; runs these services parallelly. The login manager is displayed when all the required services are
AFAIK, systemd starts as many services in parallel as possible. I would also mention the _purpose_ of this: the goal is to speed up the boot process.

2024-01-05 16:51 UTC, taroth21 commented on concepts/systemd-boot-process.xml
> +<screen>&prompt.user;systemd-analyze critical-chain
I'm not sure I got it correctly but the main purpose of this 'diagram' seems to be to visualize not only the time it takes for a process to start (that would be the 'blame' command rather) but also the order in which the services start (and this also reflects the dependencies between them, I assume). I'm missing a sentence explaining the major difference between the 'critical-chain' vs. 'blame'.

2024-01-05 16:51 UTC, taroth21 commented on concepts/systemd-boot-process.xml
> +      </variablelist>
Yep, this would be a good addition IMO.

2024-01-05 17:17 UTC, taroth21 commented on concepts/systemd-boot-process.xml
> +initiating and terminating services, etc. </para>
What I miss in this description is some info from 'man bootup', namely that the boot-up process as such is highly parallelized so that the order in which specific target units are reached is not deterministic. Also the following info from the man page is IMHO quite important: 'When systemd starts up the system, it will activate all units that are dependencies of default.target (as well as recursively all dependencies of these dependencies).'

Maybe you can check what else from the sytemd-parts of this man page would be useful to add.

2024-01-08 06:31 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +initiating and terminating services, etc. </para>
Yes I agree , I was in two minds on this because :
1. Whether its too much information and modular docs , i understand we have to keep it minimal and to the point so there is always that ambiguous line between too much and too less content to give the user ( assumptions we make on the technical knowledge of the user i.e. beginner or advanced)

2024-01-08 07:43 UTC, tomschr commented on concepts/systemd-boot-process.xml
> +initiating and terminating services, etc. </para>
I see what you mean.

I still think, the short list should be enough and is not "too much". It's just a recap and fits quite nicely into your text flow. It helps the reader to know where you pick up in your text.

For the time being, the list is probably enough. But if we find out that we need a more thorough deep dive into the Linux boot process, we could create a new concept.

2024-01-08 10:23 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +      </variablelist>
Adding

2024-01-08 10:45 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +  started and running. You can log in and start using the system. &systemd; runs in the background, managing and
re-phrased

2024-01-08 10:49 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +    <section xml:id="systemd-performance-analysis">
I am not planning to add any subsections, I will integrate the lonely section into the main one. Thanks

2024-01-08 11:07 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +<para>&systemd; runs these services parallelly. The login manager is displayed when all the required services are
Re-phrased , yes makes sense

2024-01-19 08:29 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +initiating and terminating services, etc. </para>
Yes , the 3 sentences are confusing I agree , re-phrasing it

2024-01-19 17:44 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +initiating and terminating services, etc. </para>
@tomschr I think for step 2 >> Bootloader (GRUB) , it should be GRUB2, checked this on my system:
Amrita42@localhost /boot $ ls
boot.readme                              sysctl.conf-5.14.21-150400.24.46-default
config-5.14.21-150400.24.46-default      sysctl.conf-5.14.21-150400.24.81-default
config-5.14.21-150400.24.81-default      System.map-5.14.21-150400.24.46-default
efi                                      System.map-5.14.21-150400.24.81-default
**grub2**                                    vmlinux-5.14.21-150400.24.46-default.gz
initrd                                   vmlinux-5.14.21-150400.24.81-default.gz
initrd-5.14.21-150400.24.46-default      vmlinuz
initrd-5.14.21-150400.24.81-default      vmlinuz-5.14.21-150400.24.46-default
symvers-5.14.21-150400.24.46-default.gz  vmlinuz-5.14.21-150400.24.81-default
symvers-5.14.21-150400.24.81-default.gz

2024-01-22 09:36 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +initiating and terminating services, etc. </para>
Implemented

2024-01-25 15:55 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +<screen>&prompt.user;systemd-analyze critical-chain
Re-phrasing the definitions of both to clearly distinguish between the two

2024-01-25 17:21 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +<screen>&prompt.user;systemd-analyze critical-chain
From my understanding:
**systemd-analyze blame:** prints a list of all running units, ordered by the time they took to initialize. The time to initialize a service can also be delayed because of the dependency of waiting on another to initialize. Yes to  _(this also reflects the dependencies between them, I assume)._
**systemd-analyze critical-chain:** prints a tree of the time-critical chain of units (for each of the specified UNITs or for the default target otherwise). The time after the unit is active or started is printed after the "@" character. The time the unit takes to start is printed after the "+" character. ( it is more detailed and mentions time critical units)
**Similarities for both commands**:
this only takes into account the time units spent in "activating" state, and hence does not cover units that never went through an "activating" state (such as device units that transition directly from "inactive" to "active").

2024-01-25 17:39 UTC, Amrita42 commented
Latest 
[systemd-basics_en.pdf](https://github.com/SUSE/doc-modular/files/14056088/systemd-basics_en.pdf)

2024-01-26 15:05 UTC, tomschr requested changes
@Amrita42 Thanks Amrita. I looked a bit closer to the boot process topic. Great work! Some minor typos and some small additions. Hope it helps.

2024-01-26 15:05 UTC, tomschr commented on concepts/systemd-boot-process.xml
> +Once all the services are started, your system is ready to use and the login manager displays. You can now log in and start using the system.
The `default.target` file is a link (by default to `graphical.target`). Not sure if you need to mention it, but one way could be like this:

```suggestion
  This file is a link to <filename>graphical.target</filename> which boots the graphical login  manager.
  &systemd; activates all target units that are dependencies of <filename>default.target</filename> as well as recursively all dependencies of these dependencies.
Once all the services are started, your system is ready to use and the login manager displays. You can now log in and start using the system.
```

2024-02-06 11:56 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +           If the hardware functions as expected, the boot process moves on to the next stage.</para>
Implemented

2024-02-06 11:59 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +Once all the services are started, your system is ready to use and the login manager displays. You can now log in and start using the system.
Thanks Toms :)

2024-02-06 11:59 UTC, Amrita42 commented on concepts/systemd-boot-process.xml
> +Once all the services are started, your system is ready to use and the login manager displays. You can now log in and start using the system.
The suggestions are helpful

2024-02-12 10:07 UTC, Amrita42 commented
@dariavladykina please provide a review . Thanks.

2024-02-13 06:03 UTC, Amrita42 commented
@dariavladykina please wait , looks like i missed some feedback.

2024-02-13 06:11 UTC, Amrita42 commented
@dariavladykina ready for review, thanks.

2024-02-13 13:47 UTC, dariavladykina reviewed
Hi, please see some suggestions here. Thanks!

2024-02-13 13:47 UTC, dariavladykina commented on concepts/systemd-boot-process.xml
> +        to bring the system up and running. This includes services such as networking service, the login manager etc.</para>
```suggestion
        to bring the system up and running. This includes services such as networking service, the login manager, etc.</para>
```

2024-02-13 13:47 UTC, dariavladykina commented on concepts/systemd-boot-process.xml
> +        <title>Analyze the system boot process performance with the <command>systemd-analyze</command> command </title>
```suggestion
        <title>Analyzing the system boot process performance with the <command>systemd-analyze</command> command </title>
```

2024-02-13 13:47 UTC, dariavladykina commented on concepts/systemd-boot-process.xml
> +        boot process. The command can also be used to retrieve other state and trace information
```suggestion
        boot process. The command can also be used to retrieve other state and tracing information
```

2024-02-13 13:47 UTC, dariavladykina commented on concepts/systemd-boot-process.xml
> +        services that are started and the time it takes for each service to start.</emphasis></term>
```suggestion
      <term><emphasis>Getting a high-level overview of the boot process, which includes
        services that are started and the time it takes for each service to start</emphasis></term>
```

2024-02-13 13:47 UTC, dariavladykina commented on concepts/systemd-boot-process.xml
> +command, it displays the time taken by a unit to activate, which is not defined for units like device units that transition directly to active state. </para>
```suggestion
<para>This command prints a tree of time-critical units either for each of the specified 
units or for the default target. The initialization of services might depend on socket 
activation and the parallel execution of units. Similar to the <command>blame</command>
command, it displays the time taken by a unit to activate, which is not defined for units 
like device units that transition directly to the active state. </para>
```

2024-02-13 13:47 UTC, dariavladykina commented on concepts/systemd-boot-process.xml
> +      <term><emphasis>View a list of services started during the boot process and displayed according to
```suggestion
      <term><emphasis>Viewing a list of services started during the boot process and displayed according to
```

2024-02-13 13:47 UTC, dariavladykina commented on concepts/systemd-boot-process.xml
> +&systemd; considers these services to be started immediately, hence the initialization delays can not be analyzed.
```suggestion
It displays the time taken by a unit to activate, which is not defined for units 
like device units that transition directly to the active state. This command does 
not display results for services with <literal>Type=simple</literal> because
&systemd; considers these services to be started immediately, hence the initialization 
delays cannot be analyzed.
```

2024-02-13 13:47 UTC, dariavladykina commented on concepts/systemd-boot-process.xml
> +      <term><emphasis>Generates a vector graphics file that displays the events that take place during the boot process.
```suggestion
      <term><emphasis>Generating a vector graphics file that displays the events that take place during the boot process
```

2024-02-13 13:47 UTC, dariavladykina commented on concepts/systemd-boot-process.xml
> +a set of graphics vectors that applications such as, LibreOffice Draw use to generate a graph.</para>
```suggestion
<para>This command creates an SVG file in the <literal>temp</literal> directory. 
The SVG file is a text file that defines a set of graphic vectors that applications 
such as LibreOffice Draw use to generate a graph.</para>
```

2024-02-15 05:34 UTC, merged