Article about configuring opensm
SUSE/doc-modular pull request #237
Opened 2023-11-16 12:46 UTC by tbazant

### Description

opensm will be a new addition to smartdocs

### Are there any relevant issues/feature requests?

https://jira.suse.com/browse/PED-7185

### Is this (based on) existing content?

no

2023-11-20 14:53 UTC, lvicoun requested changes

2023-11-20 14:53 UTC, lvicoun commented on concepts/opensm.xml
> +      The <command>opensm</command> command stores its main configuration in
This paragraph IMHO belongs to the next section. It does not provide any  information about the opensm cunftioning.

2023-11-20 14:53 UTC, lvicoun commented on concepts/opensm.xml
> +      &infiniband; switches usually come with a &subnetmanager; embedded in their firmware. Because
Please consider moving this sentence behind that one, which actually describes what opensm is and that it can replace the embedded subnet managers.

2023-11-20 14:53 UTC, lvicoun commented on concepts/opensm.xml
> +      devices connected to them them. If no port is specified, &opensm; selects the first available
```suggestion
      devices connected to them. If no port is specified, &opensm; selects the first available
```

2023-11-20 14:53 UTC, lvicoun commented on tasks/opensm-configuring.xml
> +<screen>&prompt.sudo;<command>zypper install opensm</command>
Are you sure here with the zypper in command? I suppose that Dolomite still is a transactional-update system?

2023-11-21 11:08 UTC, dariavladykina reviewed
Hi, please find some minor comments here. Thanks!

2023-11-21 11:08 UTC, dariavladykina commented on concepts/opensm.xml
> +            identify each device.
```suggestion
            Assigning a unique &infiniband; address to each device in the fabric. &infiniband; uses a
            unique addressing scheme known as the <emphasis>local identifier</emphasis> (LID) to
            identify each device.
```

2023-11-21 11:08 UTC, dariavladykina commented on tasks/opensm-configuring.xml
> +      on &opensm; upgrades, we recommend editing <filename>/etc/rdma/opensm</filename> instead to
```suggestion
      on &opensm; upgrades, we recommend editing <filename>/etc/rdma/opensm</filename> instead, to
```

2023-11-21 11:08 UTC, dariavladykina commented on tasks/opensm-configuring.xml
> +        &subnetmanager; on each port of the connected HCA on the host:
```suggestion
        If you are using a direct connect method or if you have multiple switches, enable the
        &subnetmanager; on each port of the connected HCA on the host:
```

2023-11-24 12:30 UTC, merged

2024-01-12 12:05 UTC, janajaeger reviewed
Added a few minor nitpicks mostly related to structure. Nice job and thanks for the intro, the doc would have been unreadable without it.

2024-01-12 12:05 UTC, janajaeger commented on articles/subnet-manager-configuring.asm.xml
Nice read. Really appreciate the intro. The hierarchy is awfully flat, but I don't think that anything could be done about that. The individual sections of the intro are too short to be kept separately. If there's nothing to be added, just ignore this comment ;)

One way to add a bit more content would be to add a for more info section holding links to all the specs you rambling on about in the intro. You could also add them to the intro directly, but then you might loose a few readers who click them right at the start ;)