Jhalackova deploying raw images
SUSE/doc-modular pull request #248
Opened 2023-12-01 12:30 UTC by lvicoun

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-12-04 14:04 UTC, tbazant requested changes
Great job Jana, consider my suggestions pls, hope they make sense

2023-12-04 14:04 UTC, tbazant commented on tasks/deployment-raw-procedure.xml
> +    </step>
I would remove this step and append it to the end of Firstboot, that makes the transiotion from this to Firstboot more streamlined
```suggestion
    
```

2023-12-04 14:04 UTC, tbazant commented on tasks/deployment-jeos-firstboot.xml
> +  </step>
```suggestion
   <step>
      <para>
        After successful deployment, register your system as described in.
      </para>
    </step>
```

2023-12-19 13:59 UTC, dariavladykina reviewed
Hi Jana, please find some comments here. Thanks!

2023-12-19 13:59 UTC, dariavladykina commented on tasks/deployment-raw-procedure.xml
> +        Boot the raw image disk and in the boot loader screen select <guimenu>SLE Micro
```suggestion
        Boot the raw disk image, and in the boot loader screen, select <guimenu>SLE Micro
```

2023-12-19 13:59 UTC, dariavladykina commented on tasks/deployment-preparing-configuration-device.xml
> +        virtualization system or your hardware supports: ISO image, a USB
```suggestion
        virtualization system or your hardware supports: an ISO image, a USB
```

2023-12-19 13:59 UTC, dariavladykina commented on tasks/deployment-jeos-firstboot.xml
> +        When booting the &productnameshort; for the first time without providing any configuration device,
```suggestion
        When booting &productnameshort; for the first time without providing any configuration device,
```

2023-12-19 13:59 UTC, dariavladykina commented on tasks/deployment-registering-system.xml
> +    documentation with <command>SUSEConnect --help</command>
```suggestion
    documentation with <command>SUSEConnect --help</command>.
```

2023-12-20 10:59 UTC, merged