Migration of virt disk cache mode smartdoc article
SUSE/doc-modular pull request #258
Opened 2023-12-13 16:00 UTC by tbazant

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-12-14 11:15 UTC, lvicoun requested changes
Good job. However, I'd suggest expand the mode description more or change the requirements of knowledge. I have basic administration skills and skills with Virt-Manager, but had a hard time understanding how the modes work and some terminology.

2023-12-14 11:15 UTC, lvicoun commented on references/virtual-disk-cache-modes.xml
> +      <term>directsync</term>
Please consider adding the difference between directsync and none (except for that one is informed that writeback can be used)

2023-12-14 11:15 UTC, lvicoun commented on tasks/virtual-disk-cache-mode-configure-using-virsh.xml
> +        Update the <literal>&lt;driver/></literal> definition and append
Please add a reference that the 'CACHE_TYPE' value defines the mode value described in "Virtual disk cache modes"

2023-12-14 11:15 UTC, lvicoun commented on articles/virtual-disk-cache-mode-configure.asm.xml
> +                    Certain steps require &rootuser; privileges.
```suggestion
                   &rootuser; privileges.
```

If I understood it correctly, you actually  can't configure the cache without it.

2023-12-15 13:03 UTC, tbazant commented
> Good job. However, I'd suggest expand the mode description more or change the requirements of knowledge. I have basic administration skills and skills with Virt-Manager, but had a hard time understanding how the modes work and some terminology.

DONE

2023-12-18 15:23 UTC, dariavladykina reviewed
Hi, please consider some suggestions. Thanks!

2023-12-18 15:23 UTC, dariavladykina commented on references/virtual-disk-cache-modes.xml
> +            needed. For unsafe or unstable guests, use <emphasis>writethough</emphasis> or
```suggestion
            These modes are considered to be the safest when the guest operating system uses flushes as
            needed. For unsafe or unstable guests, use <emphasis>writethrough</emphasis> or
```

2023-12-18 15:23 UTC, dariavladykina commented on references/virtual-disk-cache-modes.xml
> +      migration. Otherwise the only cache mode that supports live migration on read/write shared
```suggestion
      migration. Otherwise, the only cache mode that supports live migration on read/write shared
```

2023-12-18 15:23 UTC, dariavladykina commented on references/virtual-disk-cache-modes.xml
> +      allowed. Otherwise &libvirt; does not allow migration unless the cache mode is set to
```suggestion
      allowed. Otherwise, &libvirt; does not allow migration unless the cache mode is set to
```

2023-12-18 15:23 UTC, dariavladykina commented on references/virtual-disk-cache-modes.xml
> +      <command>virsh</command>. For example
```suggestion
      <command>virsh</command>. For example:
```

2023-12-18 15:23 UTC, dariavladykina commented on tasks/virtual-disk-cache-mode-configure-using-vmm.xml
> +        From the <guimenu>Chache mode</guimenu> drop-down list, select the cache mode that matches
```suggestion
        From the <guimenu>Cache mode</guimenu> drop-down list, select the cache mode that matches
```

2023-12-18 15:23 UTC, dariavladykina commented on tasks/virtual-disk-cache-mode-configure-using-virsh.xml
> +        Open you favorite terminal application and identify the VM.
```suggestion
        Open your favorite terminal application and identify the VM.
```

2023-12-18 15:23 UTC, dariavladykina commented on tasks/virtual-disk-cache-mode-configure-using-virsh.xml
> +        includes path to your disk in the <literal>&lt;source></literal>definition, for example:
```suggestion
        includes a path to your disk in the <literal>&lt;source></literal>definition, for example:
```

2023-12-18 15:23 UTC, dariavladykina commented on references/virtual-disk-cache-modes.xml
> +      <quote>--unsafe</quote> option to the migration APIs, which is also supported by
```suggestion
      <command>--unsafe</command> option to the migration APIs, which is also supported by
```

2023-12-19 13:56 UTC, aginies approved these changes

2024-01-03 10:26 UTC, merged

2024-01-12 16:15 UTC, janajaeger reviewed
Dropped a few major  nitpicks with re: proper use of warnings and a few less severe ones on structural things.

Thanks so much for taking care of this one!

2024-01-12 16:15 UTC, janajaeger commented on references/virtual-disk-cache-modes.xml
Very nice job on the varlist with the explanations! Are they in a particular order? If so, tell the reader maybe? For example, if they were ordered by their safety level, state that. I imagine readers would kind of assume this. This also applies to 2.1.

Not quite comfortable with the casual mentions of "unsafe" and "data loss" without properly formatted warnings. Not sure whether it can be done without breaking the list or totally disrupting the reading flow, though. But rules are rules :(

2024-01-12 16:15 UTC, janajaeger commented on references/virtual-disk-cache-modes.xml
> +    <tip>
This tip reads like old Greek to all but the most experienced readers. Could you add a bit more context?

2024-01-12 16:15 UTC, janajaeger commented on references/virtual-disk-cache-modes.xml
> +      <literal>none</literal>. However, this restriction can be overridden with the
This is where I would expect a properly hightlighted warning. You are instructing readers to literally compromise their data integrity.

Why would anyone want or have to do this at all? Are there use cases?

2024-01-12 16:15 UTC, janajaeger commented on tasks/virtual-disk-cache-mode-configure-using-virsh.xml
> +          You may have to restart a running VM for the changes to take effect.
Depending on what? This reads a bit too vague? Depending on the option the reader chose?

2024-01-12 16:15 UTC, janajaeger commented on tasks/virtual-disk-cache-mode-configure-using-virsh.xml
> +  &lt;source file='/home/tbazant/virt/sle15.qcow2'/>
tbazant? Don't you want to anonymize this one?

2024-01-12 16:15 UTC, janajaeger commented on tasks/virtual-disk-cache-mode-configure-using-vmm.xml
> +          You may have to restart a running VM for the changes to take effect.
Depending on what? This reads a bit too vague? Depending on the option the reader chose?

2024-01-12 16:22 UTC, tomschr commented
:information_source: The old URL https://docs.suse.com/smart/virtualization-cloud/html/concept-virtual-disk-cache-modes/ get redirected