Intro to virtualization migrated
SUSE/doc-modular pull request #259
Opened 2023-12-14 11:47 UTC by tbazant

### Is this (based on) existing content?

* old xml:id...
* old URL...

2023-12-14 15:13 UTC, lvicoun requested changes
LGTM. Just some minor things.

2023-12-14 15:13 UTC, lvicoun commented on concepts/virtualization.xml
> +              Server 2003. It uses either Binary Translation or hardware-assisted virtualization
Could we use a different version that is not 20 years old? Or remove the version reference?

2023-12-14 15:13 UTC, lvicoun commented on concepts/virtualization.xml
> +              and include &sls;.
```suggestion
              and include &productnameshort;.
```

2023-12-18 10:25 UTC, dariavladykina reviewed
Hi Tomas, please see some suggestions from my side. Thanks!

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +        virtualization mode or paravirtual mode.
```suggestion
        virtualization mode and paravirtual mode.
```

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +              processors that support it. In FV mode, &vmguest; is also called <emphasis>Hardware
```suggestion
              processors that support it. In FV mode, &vmguest; is also called the <emphasis>Hardware
```

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +              and include &productnameshort;.
Please check the entity specification got &productnameshort;. It expands into _ALP DolomiteSLE MicroSUSE LinuxSLE._

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +              paravirtualized drivers, and paravirtualized interrupt and timer handling.
Probably something is missing here or a verb is incorrect? _paravirtualized drivers, and paravirtualized interrupt and timer handling._

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +                  affects VM migration capabilities.
```suggestion
                  Using advanced hypervisor features, such as PCI pass-through or NUMA, adversely
                  affects VM migration capabilities.
```

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +                  improves VM performance and efficiency.
```suggestion
                  Using paravirtualization and <literal>virtio</literal> drivers generally
                  improves VM performance and efficiency.
```

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +              Live migration can be used to load-balance your services across your infrastructure,
```suggestion
              Live migration can be used to load balance your services across your infrastructure
```

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +          Less hardware: you can run several operating system on one host, therefore all hardware
```suggestion
          Less hardware: you can run several operating systems on one host, therefore all hardware
```

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +          (less servers than service running).
```suggestion
          Save space: your data center space is saved because you do not need more hardware servers
          (fewer servers than services running).
```

2023-12-18 10:25 UTC, dariavladykina commented on concepts/virtualization.xml
> +          to another without any service interruption.
```suggestion
          These features reduce downtime and bring an easy way to move your service from one place
          to another without any service interruption.
```

2023-12-19 11:17 UTC, tbazant reviewed
just minor fixes

2023-12-19 11:17 UTC, tbazant commented on articles/virtualization.asm.xml
> +      <meta name="title" its:translate="yes">Virtualization</meta>
```suggestion
      <meta name="title" its:translate="yes">Introduction to virtualization</meta>
```

2023-12-19 11:17 UTC, tbazant commented on concepts/virtualization.xml
> +              paravirtualized drivers, and paravirtualized interrupt and timer handling.
```suggestion
              paravirtualized drivers, and handling of paravirtualized interrupts and timers.
```

2024-01-03 10:33 UTC, merged

2024-01-12 13:20 UTC, janajaeger reviewed
Just one thought ... have you considered adding a what's next/more info section that points to other pieces on virtualization? The hw assignment article etc.? Or is that planned for some time in the future when the full spectrum of virtualization topics is available? This is a nice piece on the background of virtualization, but people might want to take action?

2024-01-12 13:26 UTC, tomschr commented
@tbazant Just to remind you to open an issue on GitLab for this ID change. :slightly_smiling_face:

2024-01-12 15:46 UTC, tomschr commented
JFI: It's available at https://documentation.suse.com/smart/virtualization-cloud/html/virtualization/