Migrating 'Assigning PCI devices to VM'
SUSE/doc-modular pull request #264
Opened 2023-12-22 12:27 UTC by tbazant

### Is this (based on) existing content?

* old xml:id...
* old URL...

2024-01-02 11:59 UTC, lvicoun requested changes

2024-01-02 11:59 UTC, lvicoun commented on tasks/vm-assign-pci-device-virsh.xml
> +<screen>&prompt.sudo;virsh nodedev-detach <replaceable>pci_0000_03_07_0</replaceable></screen>
This command is already mentioned as step 3.

2024-01-02 11:59 UTC, lvicoun commented on tasks/vm-assign-pci-device-virsh.xml
> +        managed. To switch the device mode to unmanaged, set <literal>managed='no'</literal>. If
I'm not sure if the intention is to set to unmanaged in this case. 
```suggestion
        managed. If the device mode is unmanaged, the option <literal>managed='yes'</literal> value is <literal>'yes'</literal>, 
```

2024-01-02 11:59 UTC, lvicoun commented on tasks/vm-assign-pci-device-virsh.xml
> +        you do so, you need to take care of the related driver with the <command>virsh
```suggestion
        you need to take care of the related driver with the <command>virsh
```

2024-01-02 11:59 UTC, lvicoun commented on tasks/vm-assign-pci-device-virsh.xml
> +        nodedev-detach</command> and <command>virsh nodedev-reattach</command> commands. Before
I'd suggest to provide substeps in this case.

2024-01-02 11:59 UTC, lvicoun commented on tasks/vm-assign-pci-device-virsh.xml
> +      <tip xml:id="tip-libvirt-config-pci-virsh-managed">
I'd move this into a separate section, here it breaks the procedure flow.

2024-01-02 11:59 UTC, lvicoun commented on tasks/vm-assign-pci-device-virsh.xml
> +      <para>
Please consider this as a note/tip how to use the device on host again. As according to the flow, the VM guest is now running, so you should not be able to attach it to the host machine.
If this is command is the only one to make it available again, please move it outside of the procedure as it is not related to assigning the device to the VM guest machine.

2024-01-02 11:59 UTC, lvicoun commented on tasks/vm-assign-pci-device-vmm.xml
> +<topic xml:id="vm-assign-pci-device-vmm"
What about SELinux? No changes required if attaching the device in VManager?
The PCI device handling (managed vs unamanaged) is not related to this type of PCI device assignment?

2024-01-02 12:01 UTC, dariavladykina reviewed
Hi, please see some minor suggestions. Thanks!

2024-01-02 12:01 UTC, dariavladykina commented on tasks/vm-assign-pci-device-vmm.xml
> +        &vmhost;. The following procedure describes how to assign &vmhost;'s PCI device to a
```suggestion
        &vmhost;. The following procedure describes how to assign a &vmhost;'s PCI device to a
```

2024-01-02 12:06 UTC, lvicoun requested changes
Thanks Tomas! Please, see my comments and apply what you consider valuable :)

2024-01-04 10:00 UTC, dariavladykina reviewed
Hi, please see some comments here. Thanks!

2024-01-04 10:00 UTC, dariavladykina commented on tasks/vm-assign-pci-device-unmanaged.xml
> +    When assigning a host device to a &vmguest;, you can specify whether the device is either
```suggestion
    When assigning a host device to a &vmguest;, you can specify whether the device is
```

2024-01-04 10:00 UTC, dariavladykina commented on tasks/vm-assign-pci-device-unmanaged.xml
> +    the host and attaching it to the <systemitem>vfio-pci</systemitem> driver manually as suggested
```suggestion
    the host and attaching it to the <systemitem>vfio-pci</systemitem> driver manually, as suggested
```

2024-01-04 10:00 UTC, dariavladykina commented on tasks/vm-assign-pci-device-vmm.xml
> +        From the list of available PCI devices, choose the one you want to pass to the guest.
```suggestion
        From the list of PCI devices, choose the one you want to pass to the guest.
```

2024-01-04 10:00 UTC, dariavladykina commented on tasks/vm-assign-pci-device-vmm.xml
> +        <title>Adding a PCI device</title>
Please add alt text to the figure with `<textobject role="description"/>`.

2024-01-04 12:00 UTC, merged

2024-01-12 11:45 UTC, janajaeger reviewed
See the files for a few nitpicks. Mainly about missing use cases and troubleshooting. Nice read, though ;) Thanks a million for the migration!

2024-01-12 11:45 UTC, janajaeger commented on tasks/vm-assign-pci-device-virsh.xml
> +      <para>
This is not specific to the the task being done with virsh, but rather to the process of adding hw, right? If so, it doesn't belong here, but one level up in the intro, I'd say.

2024-01-12 11:45 UTC, janajaeger commented on tasks/vm-assign-pci-device-vmm.xml
I assume you have coordinated with Shalaka? IIRC, she was or is still working on a virt-manager piece?