Cockpit as RPM and not container anymore in Dolomite
SUSE/doc-modular pull request #270
Opened 2024-01-08 11:13 UTC by tbazant

### Description

Cockpit is distributed as an RPM package in Dolomite and not as podman container image anymore

### Are there any relevant issues/feature requests?

* bsc#1217518

2024-01-08 14:34 UTC, dariavladykina reviewed
Just a minor nit from me, thanks!

2024-01-08 14:34 UTC, dariavladykina commented on tasks/cockpit-installation.xml
> +        topic provides instructions how to install it and enable its service.
```suggestion
        topic provides instructions on how to install it and enable its service.
```

2024-01-24 14:54 UTC, lvicoun requested changes

2024-01-24 14:54 UTC, lvicoun commented on tasks/cockpit-installation.xml
> -      plugin for administration of virtual machines needs to be installed
Please keep this for SLE Micro as it was as it was a specific demand to mention this particular plugin.

2024-01-24 14:54 UTC, lvicoun commented on tasks/cockpit-installation.xml
> +      &cockpit; is included in the delivered pre-built images by default. If your scenario requires
This does not apply to older Micro releases, the previous version of the text was more pecise.

2024-01-24 15:07 UTC, fsundermeyer commented
Replaced by #286

2024-01-24 15:07 UTC, closed without merging