SLE_MICRO: deploying raw images in VM
SUSE/doc-modular pull request #292
Opened 2024-02-02 10:03 UTC by tbazant

### Description

This update describes SLEMCRO raw image deployment in a VMguest

2024-02-05 10:05 UTC, lvicoun requested changes
Thanks for the help, Tomas! Please see my comments. I'll remove the deployment overview later, as it isn't needed.

2024-02-05 10:05 UTC, lvicoun commented on tasks/prepare-alp-vm.xml
> +        This article describes how to configure a new virtual machine suitable for the
Actually, it describes the whole deployment process :)
```suggestion
        This section describes how to prepare a new virtual machine and what steps to take to deploy &productnameshort; on that machine.
```

2024-02-05 10:05 UTC, lvicoun commented on tasks/prepare-alp-vm.xml
> +        &productnameshort; deployment.
```suggestion
  
```

2024-02-05 16:07 UTC, dariavladykina reviewed
Hi, please find some suggestions from me. Thanks!

2024-02-06 08:27 UTC, tbazant reviewed
Suggestions applied

2024-02-06 08:27 UTC, tbazant commented on articles/deployment-raw-images-virtual-machines.asm.xml
> +                Because virtualized deployment saves hardware resources.
```suggestion
                Virtualized deployment saves hardware resources.
```

2024-02-06 10:41 UTC, tbazant reviewed
last 2 fixes

2024-02-06 10:41 UTC, tbazant commented on tasks/alp-expanding-encrypted-images.xml
> +    </step>
```suggestion
```

2024-02-06 10:41 UTC, tbazant commented on tasks/alp-expanding-encrypted-images.xml
> +        When the system is ready, use the <command>parted</command> command to resize the partition
```suggestion
        Use the <command>parted</command> command to resize the partition
```

2024-02-06 11:15 UTC, merged