SLES Minimal VM revision
SUSE/doc-modular pull request #295
Opened 2024-02-06 13:55 UTC by dmpop

### Description

Complete revision of the content and structure.

2024-02-07 17:36 UTC, fsundermeyer requested changes
The structure is well thought through, only two minor adjustments are needed.
The content however, requires a few changes. There is some ionconsitencies that need to be taken care of. Also installation instructions for XEN, HyperV and OpenStack are missing.

2024-02-08 09:56 UTC, fsundermeyer commented on concepts/minimal-vm-highlights.xml
> +     </para>
How about
...automatically creates a Btrfs snapshot after the initial configuration via jeos-firstboot or cloud-init.

To me that does not sound as if the config would be optional.

2024-02-08 11:07 UTC, dmpop commented on concepts/minimal-vm-on-kvm.xml
> +      Click <guimenu>Forward</guimenu>.
The idea here is to show how to quickly create a VM for _testing_ purposes.

2024-02-08 11:08 UTC, dmpop commented on concepts/minimal-vm-on-kvm.xml
> +    <title>Installing and running &minvm; on &kvm;</title>
Because it's a quick start guide. The purpose of which to introduce the reader to Minimal VM, and not to give them an exhaustive description of all available deployment options.

2024-02-08 11:10 UTC, dmpop commented on concepts/minimal-vm-on-kvm.xml
> +    experiment with &minvm; safely.
Again, the purpose of the document is to introduce reader to Minimal VM, hence the general tone "here are the basic facts about Minimal VM, and here's how you can give it a try".

2024-02-08 11:28 UTC, dmpop commented on concepts/minimal-vm-combustion.xml
> +    First, generate a hash of the desired &rootuser; password. This can be done
I'm not sure I agree in this particular case. There are no steps. Before you run a command, you need to generate a password hash. That's all. But if you think it's a good idea to turn this into a two-step procedure, I'll do it.

2024-02-08 11:32 UTC, dmpop commented on concepts/minimal-vm-combustion.xml
> +</topic>
I'm not sure I understand. It doesn't replaces anything. It just gives an example that illustrates how to use Combustion.

> Also, is this something that can also be done via virt-install?

2024-02-09 10:46 UTC, dmpop commented on concepts/minimal-vm-vs-sles.xml
> +          password.
Yes, and no. You can select keyboard layout, but not language. I'll rephrase.

2024-02-09 10:54 UTC, dmpop commented on concepts/minimal-vm-on-kvm.xml
> +      layout using the keyboard selection dialog.
Yes.

2024-02-15 10:46 UTC, merged