vxlan (jsc#docteam-1283)
SUSE/doc-modular pull request #304
Opened 2024-02-29 13:55 UTC by tbazant

### Description

More scalable version of VLAN where VMs can be isolated from the rest of the network

### Are there any relevant issues/feature requests?

* jsc#docteam-1283

2024-03-18 13:59 UTC, fsundermeyer requested changes
Hi Tomas,

thank you very much, this looks good as a first draft. I have suggested a few improvements inline. In  general, I think a few things are still missing:

* Adding an existing VM to a VXLAN is probably a coner case. What di I need to do to create a new VM that is automatically attached to the VXLAN 
*  The article does not clarify why one would need a VXLAN and how to use it, My thoughts after reading the article were: What now? and Why would I do this?
* The diagram is very confusing and of little help. Why are there two completely separated different VM hosts using VXLANs with the same name?

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-bridge.xml
> +            Disables IPv4 on the bridge.
Using "Disable" here and in the following sounds like neither IPv4 nor IPV6 traffic would pass the bridge. I'd rather say 

"Prevents assigning an IPv4 address"

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-bridge.xml
> +    <title>Creating a network bridge with a VXLAN</title>
```suggestion
    <title>Creating a network bridge with a VXLAN attached</title>
```

2024-03-18 13:59 UTC, fsundermeyer commented on articles/vxlan.asm.xml
> +        <title>Creating a network bridge</title>
```suggestion
        <title>Creating a network bridge with a VXLAN attached</title>
```

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-bridge.xml
> +        </callout>
Questions you may want to address here:

* Can a bridge have several VXLANS attached (and would that make sense)?
* Does the VLAN ID need to be numerical?
*  How to determine which address to use with "local"?  Is this something a can freely choose?
*  Same question as above for "remote"

Also these addresses and the setup should be used in the diagram above

Is this one command really all the magic neede to create a VXLAN?

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-bridge.xml
> +            device forwarding database.
This whole explanatio makes little sense to me because it uses terms and concepts that have never been explained.

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-bridge.xml
> +        If firewall is active, modify its rules to allow incoming UDP
```suggestion
        If <systemitem class="daemon">firewalld</systemitem> is active, modify its rules to allow incoming UDP
```

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-bridge.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This section comes without any introduction, this is a bit weird. I think it should be part of a bigger setction:

2  Setting up a VXLAN on the VMHost

<INTRO paragraph>

2.1 Creating a network bridge
2.2 Creating a virtual network
2.3 Connecting VMs

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-vm.xml
> +    <title>Configuring virtual machines to use VXLAN</title>
```suggestion
    <title>Connecting virtual machines to the VXLAN</title>
```

The original title sounds like you would need to re-configure VMs, which is not the case

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-vm.xml
> +        a VXLAN via a network bridge.
Also, change accordingly (see title)

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-vm.xml
> +      </para>
Please make both commands subsetps and explain which one is for the host an which one for the VM

Also, explain "vnet1" and the role it plays in both outputs (I assume it is a virtual network created by libvirt which is used by this particular VM). If that is true, you would only need to run the test for the host once and not if you add other VMs using the same virtrual network. 

Also, ho would the host check look like if you add VMs using different virtual networks?

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-configure-vm.xml
> +    </step>
You should also mention a result here: If the outputs looks like XYZ you have successfully managed to connect the VM to the VXLAN.

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-create-vlan.xml
> +        Create an XML file that defines a new virtual network. The file should
```suggestion
        Create a temporary XML file (for example, <filename>/tmp/tvxlan1-br0.xml</filename>) that defines a new virtual network. The file should
```

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-create-vlan.xml
> +<screen>&prompt.user;cat ~/vxlan1-br0.xml
Delete the line starting with `cat`

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-create-vlan.xml
> +        Use the definition file to create a new &libvirt;-based virtual network.
```suggestion
        Use the XML file to create a new &libvirt;-based virtual network.
```

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-create-vlan.xml
> +        Remove the XML definition file from disk.
```suggestion
        Remove the XML definition file from disk, it is no longer needed.
```

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-create-vlan.xml
> +<screen>&prompt.user;rm ~/vxlan1-br0.xml</screen>
```suggestion
<screen>&prompt.user;rm /tmp/vxlan1-br0.xml</screen>
```

2024-03-18 13:59 UTC, fsundermeyer commented on tasks/vxlan-create-vlan.xml
> +        Verify the status of the newly created network.
Something like "If the output looks like XYZ, the configuration was successful" is missing

2024-03-20 10:55 UTC, tbazant reviewed
version update + some suggestions applied

2024-03-20 10:55 UTC, tbazant commented on snippets/vxlan-intro.xml
> +<!DOCTYPE warning [
yes

2024-04-05 14:03 UTC, farosas commented on tasks/vxlan-configure-bridge.xml
> +&prompt.sudo;firewall-cmd --permanent --add-port=8472/udp &amp;&amp; firewall-cmd --reload
The sudo doesn't apply to the second clause after the &&. We need another sudo or to break this into two separate commands.

2024-04-05 14:03 UTC, farosas commented on tasks/vxlan-configure-vm.xml
> +<screen>&prompt.sudo;virt-xml <replaceable>VM1</replaceable> --edit
missing a \ at the end

2024-04-05 14:03 UTC, farosas commented on tasks/vxlan-configure-vm.xml
> +        network bridge on the guest.
On the  host? There's no vxlan1-br0 inside the guest.

2024-04-05 14:03 UTC, farosas commented on tasks/vxlan-configure-vm.xml
> +            The configured VXLAN network atatched to the
```suggestion
            The configured VXLAN network attached to the
```

2024-04-09 08:52 UTC, tbazant reviewed
Applied review suggestions

2024-04-09 08:52 UTC, tbazant commented on articles/vxlan.asm.xml
> +                communicate.
```suggestion
                The VXLAN protocol can address more isolated
                virtual networks than the traditional VLAN. Within these networks, groups of virtual machines can safely communicate even across distant network locations.
```

2024-04-09 08:52 UTC, tbazant commented on tasks/vxlan-configure-bridge.xml
> +&prompt.sudo;firewall-cmd --permanent --add-port=8472/udp &amp;&amp; firewall-cmd --reload
```suggestion
&prompt.root;firewall-cmd --permanent --add-port=8472/udp &amp;&amp; firewall-cmd --reload
```

2024-04-09 08:52 UTC, tbazant commented on tasks/vxlan-configure-vm.xml
> +    --network network=vxlan1-br0</screen>
```suggestion
<screen>&prompt.sudo;virt-xml <replaceable>VM1</replaceable> --edit --network network=vxlan1-br0</screen>
```

2024-04-09 08:52 UTC, tbazant commented on tasks/vxlan-configure-vm.xml
> +        network bridge on the guest.
```suggestion
        network bridge on the host.
```

2024-04-09 10:16 UTC, dariavladykina reviewed
Hi, please see some suggestions. Thanks!

2024-04-09 10:16 UTC, dariavladykina commented on tasks/vxlan-configure-bridge.xml
> +    (VMs) use a network bridge to which the VXLAN is attached. Run the following
```suggestion
    use a network bridge to which the VXLAN is attached. Run the following
```

2024-04-09 10:16 UTC, dariavladykina commented on tasks/vxlan-configure-vm.xml
> +    You need to configure virtual machines (VMs) to use the virtual network
```suggestion
    You need to configure virtual machines to use the virtual network
```

2024-04-09 10:16 UTC, dariavladykina commented on tasks/vxlan-create-vlan.xml
> +    that bridge. Run the following procedure on the &vmhost; to add such virtual
```suggestion
    that bridge. Run the following procedure on the &vmhost; to add such a virtual
```

2024-04-09 10:16 UTC, dariavladykina commented on tasks/vxlan-create-vlan.xml
> +        Create a temporary XML file <filename>/tmp/vxlan1-br0.xml</filename>)
```suggestion
        Create a temporary XML file (<filename>/tmp/vxlan1-br0.xml</filename>)
```

2024-04-09 10:16 UTC, dariavladykina commented on tasks/vxlan-create-vlan.xml
> +        Remove the XML definition file from disk, it is no longer needed.
```suggestion
        Remove the XML definition file from disk. It is no longer needed.
```

2024-05-02 10:25 UTC, merged