some proposals for virt-scenario
SUSE/doc-modular pull request #309
Opened 2024-03-14 16:14 UTC by taroth21

### Description

Some proposals for the virt-scenario article from a review.

### Are there any relevant issues/feature requests?

* jsc#DOCTEAM-118.

### Is this (based on) existing content?

* https://documentation.suse.com/smart/virtualization-cloud/html/virt-scenario-creating-customized-vm-guests/index.html

2024-03-18 10:28 UTC, tbazant requested changes
Most suggestions are fine, some require more editing, this is the 1st batch of changes.

2024-03-18 10:28 UTC, tbazant commented on references/virt-scenario-manage-vm.xml
> +    When the VM is identified, you can manage it during launch with the following options.
```suggestion
    When the VM is identified, you can manage it by passing the following options to <command>virt-scenario-launch</command>.
```

2024-03-18 10:28 UTC, tbazant commented on references/virt-scenario-manage-vm.xml
> +      also for the virt-scenario-launch command, therefore added 'during launch' above</remark>
```suggestion
       
```

2024-03-18 10:28 UTC, tbazant commented on tasks/virt-scenario-create-vm.xml
> +    new VM. <remark>taroth: where does it save the file? path?</remark>
```suggestion
    new VM in <filename>~/etc/virt-scenario/vmconfig</filename>.
```

2024-03-18 10:28 UTC, tbazant commented on tasks/virt-scenario-create-vm.xml
>  <screen>conf /home/tux/virt-scenarios/my-overriden-scenario.yaml</screen>
```suggestion  
    </para>
<screen>&gt; conf /home/tux/virt-scenarios/my-overriden-scenario.yaml</screen>
```

2024-03-18 10:28 UTC, tbazant commented on tasks/virt-scenario-create-vm.xml
>      </warning>
```suggestion
    <warning>
    <title>Section names in <filename>virtrscenario.yaml</filename></title>
      <para>
        Never change section names in the
        <filename>/etc/virt-scenario/virtscenario.yaml</filename> file or its
        overriding copies. Otherwise, &virt-scenario; wrongly identifies matching settings and the resulting VM
        configuration will be invalid.
      </para>
    </warning>
```

2024-03-18 10:28 UTC, tbazant commented on tasks/virt-scenario-create-vm.xml
>        to perform only part of the task. After entering the
```suggestion
      By default, &virt-scenario; both creates the &libvirt; XML configuration of
      the new guest and adjusts the &vmhost;. You can instruct &virt-scenario;
      to skip one of the above tasks. After entering the
```

2024-03-21 10:40 UTC, taroth21 reviewed
Looks good to me so far. Only one small suggestion.

2024-03-21 10:40 UTC, taroth21 commented on tasks/virt-scenario-create-vm.xml
>        &virt-scenario;.
I would move the sentence 'Change settings in this file...' to the beginning of the procedure now. Then you have an uninterrupted flow between the first sentence and the example as such _and_ a good introduction to the procedure.

2024-03-21 10:40 UTC, taroth21 commented on tasks/virt-scenario-create-vm.xml
> +      <step>
```suggestion
    <procedure>
     <para>
        To modify the settings for <emphasis>all</emphasis> VMs created by &virt-scenario;, 
        copy the file and change it according to your wishes:
      </para>
      <step>
```

2024-04-05 09:37 UTC, dariavladykina reviewed
Hi, please see a couple of suggestions here. Thanks!

2024-04-05 09:37 UTC, dariavladykina commented on tasks/virt-scenario-create-vm.xml
> +          Backup <filename>/etc/virt-scenario/virtscenario.yaml</filename>
```suggestion
          Back up <filename>/etc/virt-scenario/virtscenario.yaml</filename>
```

2024-04-05 09:37 UTC, dariavladykina commented on tasks/virt-scenario-create-vm.xml
> +            configuration may be invalid.
```suggestion
            <filename>virtscenario.yaml</filename> file, not only the modified settings. 
            Also, never change section names in <filename>virtscenario.yaml</filename>
            or its overriding copies. Doing so might cause &virt-scenario; to misinterpret 
            matching settings, leading to an invalid VM configuration.
```

2024-04-05 09:37 UTC, dariavladykina commented on tasks/virt-scenario-create-vm.xml
> +            configuration, the host system may already have been adjusted appropriately and it is
```suggestion
            configuration, the host system may already have been adjusted appropriately, and it is
```

2024-04-05 09:40 UTC, merged