Add task for setting up UEFI HTTP Boot server
SUSE/doc-modular pull request #31
Opened 2021-09-16 00:50 UTC by tahliar

Rendered PDF:
[task-set-up-uefi-http-boot-server_color_en.pdf](https://github.com/SUSE/doc-modular/files/7174122/task-set-up-uefi-http-boot-server_color_en.pdf)

2021-09-16 17:27 UTC, lproven requested changes

2021-09-16 17:27 UTC, lproven commented on xml/task-set-up-uefi-http-boot-server.xml
> +  <para>This document applies to the following products and product versions:</para>
```suggestion
  <para>This document applies to the following product and product versions:</para>
```

2021-09-16 17:27 UTC, lproven commented on xml/task-set-up-uefi-http-boot-server.xml
> +   This article shows you how to configure DNS, DHCP, and HTTP on a single
Since we are actually talking about all 3 together here, I personally would lose the Oxford comma. I am not sure if others would agree with me, though.

2021-09-16 17:27 UTC, lproven commented on xml/task-set-up-uefi-http-boot-server.xml
> +     You have a &sles; ISO image available, either on a media drive or downloaded
2 questions about this:
1. a "media drive"? Seems a clumsy phrase.
2. will it work with a physical medium? I'd have thought it'd _have_ to be an ISO. I do not know for sure, though.

2021-09-16 17:27 UTC, lproven commented on xml/task-set-up-uefi-http-boot-server.xml
> +2001:db8:f00f:cafe::1 www.httpboot.local</screen>
At a guess, these are example names and addresses, and so probably should be in [replaceable] tags, no?

2021-09-16 17:27 UTC, lproven commented on xml/task-set-up-uefi-http-boot-server.xml
> +   In this procedure, replace the example IP addresses with the appropriate
```suggestion
   In this procedure, replace the example host names and IP addresses with the appropriate
```

2021-09-16 17:27 UTC, lproven commented on xml/task-set-up-uefi-http-boot-server.xml
> +   documentation for information on how to enable HTTP Boot on client machines.
```suggestion
    So long as the client machines' firmware supports HTTP Boot, you can
    now use this server to remotely install operating systems from an HTTP
    URL. Consult the relevant documentation for information on how to
    enable HTTP Boot on client machines.
```

2021-09-16 17:27 UTC, lproven commented on xml/task-set-up-uefi-http-boot-server.xml
> +   documentation for information on how to enable HTTP Boot on client machines.
Basically just moving the condition to before the outcome, as I think this reads more clearly. Otherwise I mentally stumble slightly when I come across the condition at the end of a sentence.

2021-09-16 17:27 UTC, lproven commented on xml/task-set-up-uefi-http-boot-server.xml
> +  <para>This document applies to the following products and product versions:</para>
Only a suggestion.

2021-09-17 06:32 UTC, tahliar commented on xml/task-set-up-uefi-http-boot-server.xml
> +   This article shows you how to configure DNS, DHCP, and HTTP on a single
*gasp* Not my precious Oxford comma!

2021-09-17 06:54 UTC, tahliar commented on xml/task-set-up-uefi-http-boot-server.xml
> +     You have a &sles; ISO image available, either on a media drive or downloaded
1. Installation medium? Any other suggestions?
2. I'm reasonably certain it has to be an ISO, but don't quote me on that.

2021-09-17 06:57 UTC, tahliar commented on xml/task-set-up-uefi-http-boot-server.xml
> +2001:db8:f00f:cafe::1 www.httpboot.local</screen>
Normally I'd say yes, but this whole article uses a ton of example text, so I've relied pretty heavily on saying "for example" and having intros with "replace the examples with your actual stuff". I could potentially rethink it, though.

2021-09-17 07:00 UTC, tahliar commented on xml/task-set-up-uefi-http-boot-server.xml
> +   documentation for information on how to enable HTTP Boot on client machines.
I agree in principle but I don't like "So long as". What if we condensed it further to "You can now use this server to remotely install operating systems on clients that support HTTP Boot"?

2021-09-17 17:09 UTC, lproven commented on xml/task-set-up-uefi-http-boot-server.xml
> +     You have a &sles; ISO image available, either on a media drive or downloaded
How about a "physical optical drive"?

2021-09-20 00:13 UTC, tahliar commented on xml/task-set-up-uefi-http-boot-server.xml
> +     You have a &sles; ISO image available, either on a media drive or downloaded
That sounds even more clumsy tbh! The style guide seems to say that installation medium is the way to go, but actually I think I don't really need to specify - "You have a &sles; ISO image available." should be enough?

2021-09-20 22:58 UTC, merged