DOCTEAM-1338: assembly and dc file
SUSE/doc-modular pull request #315
Opened 2024-03-22 06:24 UTC by Amrita42

### Description

The scope of this PR is to cover the scope of "Setting up a systemd service" as defined in https://jira.suse.com/browse/DOCTEAM-1338
 

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2024-07-29 07:36 UTC, Amrita42 commented
[setting-up-systemd_en.pdf](https://github.com/user-attachments/files/16409116/setting-up-systemd_en.pdf)

2024-11-18 14:33 UTC, taroth21 requested changes
@Amrita42 : Many thanks, well done! Sorry for the large number of comments and suggestions but the majority of them is about updating the metadata and adjusting some structures to the latest template updates (I provide those as suggestions). 

Regarding the content, only some minor nitpicks. Many thanks!The majority of the changes I suggested (as proposals) refer to metadata and adjustments to comply with the latest templates

2024-12-02 07:00 UTC, Amrita42 commented on references/systemd-editing-unit-file.xml
> +  <info>
I will use the second option and rephrase the title

2024-12-02 07:01 UTC, Amrita42 commented on references/systemd-debug-failed-service.xml
> +        <itemizedlist>
Yes , good point I agree +1

2024-12-02 07:43 UTC, Amrita42 commented on references/systemd-editing-unit-file.xml
> +  <info>
Change of name will then need to reflect in other three published articles:
systemd basics
managing systemd services
systemd boot process

This topic is used in the above three .

should i go ahead ? @taroth21

2024-12-02 09:10 UTC, Amrita42 commented on tasks/systemd-edit-service.xml
> +<topic xml:id="edit-systemd-service"
@taroth21 Looking at this more in-depth , this file is not required and I will remove it , as we do have an existing one "systemd-editing-unit-file" in place .

2024-12-02 09:29 UTC, Amrita42 commented on references/systemd-editing-unit-file.xml
> +          When the package is installed, &systemd; unit files reside here.
Yes , the systemd package , rephrased

2024-12-02 09:32 UTC, Amrita42 commented on references/systemd-editing-unit-file.xml
> +          When the package is installed, &systemd; unit files reside here.
its the systemd unit files with RPM packages , re-phrased.

2024-12-02 09:36 UTC, Amrita42 commented on references/systemd-editing-unit-file.xml
> +  <variablelist>
Done , defined which directory takes precedence

2024-12-02 11:55 UTC, Amrita42 commented on tasks/systemd-edit-service.xml
> +<topic xml:id="edit-systemd-service"
Ignore

2024-12-02 11:56 UTC, Amrita42 commented on references/systemd-editing-unit-file.xml
> +  <info>
Resolved in the chat , ignore

2024-12-02 14:03 UTC, closed without merging