doc-kit run (fetch updates & replace entities)
SUSE/doc-modular pull request #319
Opened 2024-03-27 13:48 UTC by taroth21

### Description

Applying the latest changes from doc-kit (metadata updates for assembly files + ALP-related entity updates). 

### Are there any relevant issues/feature requests?

* jsc#DOCTEAM-1332

2024-03-28 08:33 UTC, lvicoun commented on articles/SLE_Micro_admin.asm.xml
> +        <!-- enter product name and version --><productname version="5.4">&slm;</productname>
Here &slema; should stay as it is a 5.4 doc that is still named SLE Micro.

2024-03-28 08:33 UTC, taroth21 commented on articles/SLE_Micro_admin.asm.xml
> +        <!-- enter product name and version --><productname version="5.4">&slm;</productname>
Good catch, thanks!

2024-03-28 08:35 UTC, lvicoun commented on common/product-entities.ent
> +<!ENTITY productname            "<phrase xmlns='http://docbook.org/ns/docbook'><phrase os='slemicro'>&slm;</phrase><phrase os='generic'>&suselinux;</phrase><phrase os='sles'>&sles;</phrase></phrase>"
I think we need do add another <phrase> that will have &slm; as in this case all docs (even the 5.4 adn 5.5) will have the new product name :(

2024-03-28 08:40 UTC, lvicoun commented on concepts/rootless-podman-limitations.xml
> +        &slm; does not allow regular users, thus making it impossible to run
I believe this should also be &productname; and the corresponding listitem should be profiled for Micro.

2024-03-28 08:44 UTC, lvicoun requested changes

2024-03-28 08:44 UTC, lvicoun commented on concepts/snapper-basic-concept.xml
> +      systems, such as &slm;. For more information on &slm; snapshots, refer to
Similar situation here. I'll reach out to Daria and Dima regarding this.

2024-03-28 08:44 UTC, lvicoun commented on tasks/enable-podman.xml
> +        Running a container with &podman; in rootless mode on &slm; may fail,
Again. If this article is related to Micro, then we should use productname here and hide the note for other products.

2024-03-28 08:44 UTC, lvicoun commented on tasks/micro-cloud-useradd.xml
> +    already running system. However, as &slm; is Btrfs-based, the
```suggestion
    already running system. However, as &productname; is Btrfs-based, the
```

2024-03-28 09:11 UTC, tbazant approved these changes
small nits, otherwise great job!

2024-03-28 09:11 UTC, tbazant commented on articles/SLE-Micro-public-cloud.asm.xml
> +        <productname version="slemicro">&slm;</productname>
is this a correct version?

2024-03-28 09:11 UTC, tbazant commented on articles/cockpit-alp.asm.xml
> +        <productname version="slemicro">&slm;</productname>
version?

2024-03-28 09:11 UTC, tbazant commented on common/product-entities.ent
> +<!ENTITY productnumber          "<phrase xmlns='http://docbook.org/ns/docbook'><phrase os='slemicro_5.4'>5.4</phrase><phrase os='slemicro_5.5'>5.5</phrase><phrase os='slemicro_6.0'>6.0</phrase><phras
profiling for alp-dolomite is lost, shall we replace it with &slcs; or rather cancel Dolomite documentation?

2024-03-28 09:27 UTC, taroth21 commented on common/product-entities.ent
> +<!ENTITY productnumber          "<phrase xmlns='http://docbook.org/ns/docbook'><phrase os='slemicro_5.4'>5.4</phrase><phrase os='slemicro_5.5'>5.5</phrase><phrase os='slemicro_6.0'>6.0</phrase><phras
Yes, the product name is gone now. We need to replace the Dolomite docs with a very basic (product) description of SLCS as quickly as possible (see the second part of the description in DOCTEAM-1332). Half a page is good enough for the beginning.

2024-03-28 09:28 UTC, taroth21 commented on common/product-entities.ent
> +<!ENTITY productname            "<phrase xmlns='http://docbook.org/ns/docbook'><phrase os='slemicro'>&slm;</phrase><phrase os='generic'>&suselinux;</phrase><phrase os='sles'>&sles;</phrase></phrase>"
At least, I thought it was the plan to copy over the articles for Micro 5.5 and older to doc-sle? But looking at the docserv2 config, I see that some of the content fro 5.5 is still built from doc-modular (and is included via `<internal>`  in that config).

That makes it difficult now. I think we need to discuss that next Tue.

2024-03-28 09:33 UTC, taroth21 commented on articles/SLE-Micro-public-cloud.asm.xml
> +        <productname version="slemicro">&slm;</productname>
@janajaeger ?

2024-03-28 09:34 UTC, taroth21 commented on articles/SLE_Micro_admin.asm.xml
> +        <!-- enter product name and version --><productname version="5.4">&slm;</productname>
Depends on the answer to my comment below (if we keep building Micro 5.5. and 5.4 docs from both `doc-sle` and `doc-modular`)

2024-03-28 10:44 UTC, lvicoun commented on common/product-entities.ent
> +<!ENTITY productname            "<phrase xmlns='http://docbook.org/ns/docbook'><phrase os='slemicro'>&slm;</phrase><phrase os='generic'>&suselinux;</phrase><phrase os='sles'>&sles;</phrase></phrase>"
Yes, some docs were already moved do doc-modular as it happened before that decision was made.

2024-04-02 16:28 UTC, tbazant requested changes
added more suggestions - removing &alp*

2024-04-02 16:28 UTC, tbazant commented on articles/cpu-check-temperature.asm.xml
> +        <productname version="1">&slfo;</productname>
```suggestion
```

2024-04-02 16:28 UTC, tbazant commented on articles/subnet-manager-configuring.asm.xml
> +        <productname version="1.0">&slfo;</productname>
```suggestion
```

2024-04-02 16:28 UTC, tbazant commented on common/generic-entities.ent
> +<!ENTITY slfo                   "&suselinux; Framework One">
```suggestion
```

2024-04-04 16:02 UTC, taroth21 commented on articles/SLE-Micro-public-cloud.asm.xml
> +        <productname version="slemicro">&slm;</productname>
Please see https://github.com/SUSE/doc-modular/pull/319/commits/321636c71fef1c7b4cba660596bd2ad7b0e6de2a

2024-04-05 14:30 UTC, taroth21 commented on concepts/rootless-podman-limitations.xml
> +        &slm; does not allow regular users, thus making it impossible to run
https://github.com/SUSE/doc-modular/pull/319/commits/93805b9febd72a0068ed440b5fd4f2ad175457d5

2024-04-05 14:30 UTC, taroth21 commented on tasks/enable-podman.xml
> +        Running a container with &podman; in rootless mode on &slm; may fail,
https://github.com/SUSE/doc-modular/pull/319/commits/93805b9febd72a0068ed440b5fd4f2ad175457d5

2024-04-05 14:30 UTC, taroth21 commented on concepts/snapper-basic-concept.xml
> +      systems, such as &slm;. For more information on &slm; snapshots, refer to
https://github.com/SUSE/doc-modular/pull/319/commits/93805b9febd72a0068ed440b5fd4f2ad175457d5

2024-04-08 11:35 UTC, tbazant requested changes
LG but one glitch...

2024-04-08 11:35 UTC, tbazant commented on articles/systemd-timer-working-with.asm.xml
> +        <productname version="6.0">&productname;</productname>
Is `os="slemicro"` missing here?

2024-04-08 11:42 UTC, lvicoun commented on articles/systemd-timer-working-with.asm.xml
> +        <productname version="6.0">&productname;</productname>
Fixed.

2024-04-09 08:37 UTC, merged