All about SSL/TLS certificates
SUSE/doc-modular pull request #320
Opened 2024-03-28 12:54 UTC by tbazant

### Description

A new article that explains and shows what TLS is and how to implement it on SUSE hosts

### Are there any relevant issues/feature requests?

* bsc#1194130
* jsc#DOCTEAM-480

### Is this (based on) existing content?

no

2024-04-18 09:06 UTC, jirib commented
My 2 cents:

- ssl vs tls (right in the beginning) - let's use only TLS later after clarification
- Goal -> plus manage the certs !
- Handshake -> TLS handshake (everywhere) - not sure but TLS 1.3 simplified the TLS handshake https://www.cloudflare.com/learning/ssl/what-happens-in-a-tls-handshake/#:~:text=The%20basic%20steps%20of%20a,cipher%20suites%20is%20vastly%20reduced. (not sure how DH params play role here)
- 1.1 should mention PFS https://en.wikipedia.org/wiki/Forward_secrecy (old days way to decrypt the captured communication while having the private key thus does not work...)
- DH params/key exchange might be good to mention
- 3 creating a private key - not sure if ECDSA key would be compat with all our SLES supported versions, it should be clear here
- 3.1 Tip - should read that some tools allow the passphrase to be provide via systemd unit... but probably not all, untested !
```
/usr/sbin/apache2-systemd-ask-pass:exec /usr/bin/systemd-ask-password "Enter SSL pass phrase for $1 ($2): "
```
- 7 - iiuc there are openssl and gnutls stores; 7.3 is gnutls
- 6 - not sure but java used to have its own trust store but on SLES it uses the system one
- there should be an example how to query if a cert is present in the trust store
```
# an example
$ awk -v cmd='openssl x509 -noout -subject -startdate -enddate' '/BEGIN/{close(cmd)}; { print | cmd }' \
    < /etc/ssl/ca-bundle.pem  2>/dev/null | grep -C 1 'DigiCert Global Root CA'
notAfter=Jan 15 12:00:00 2038 GMT
subject=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
notBefore=Nov 10 00:00:00 2006 GMT
```
- maybe a TLS client-server auth with certs? so only a special tls client could use a tls server ?
- 4.1 - maybe an example for alt_names with an IP ?

2024-04-29 13:59 UTC, dariavladykina reviewed
Hi, please see some suggestions here. Thanks!

2024-04-29 13:59 UTC, dariavladykina commented on tasks/tls-sign-csr-private-ca.xml
> +        that you entered in <xref linkend="tls-creating-private-ca"/>.
```suggestion
        that you entered per <xref linkend="tls-creating-private-ca"/>.
```

2024-04-29 13:59 UTC, dariavladykina commented on tasks/tls-sign-csr-private-ca.xml
> +        the certificate.
```suggestion
        The certificate remains valid for two years. Adjust the value to your
        needs. After this period, you must create a new CSR and have a CA sign
        the certificate.
```

2024-04-29 13:59 UTC, dariavladykina commented on tasks/tls-sign-csr-private-ca.xml
> +        Verify that the data included in the resulting certificate match your
```suggestion
        Verify that the data included in the resulting certificate matches your
```

2024-04-29 13:59 UTC, dariavladykina commented on concepts/tls-certificate-store.xml
> +    store is utilized by software applications and components within the
```suggestion
    store is used by software applications and components within the
```

2024-04-29 13:59 UTC, dariavladykina commented on concepts/tls-certificate-store.xml
> +      certificates in both certificate stores, install the plug-in package
```suggestion
      By default, there are two different CA certificate stores in
      &productnameshort;: the OpenSSL-based store and the NSS (Network Security
      System)-based store. Many GUI-based Web browsers&mdash;such as
      Firefox&mdash;use the NSS certificate store. To avoid installing CA
      certificates in both certificate stores, install the plug-in package
```

2024-04-29 13:59 UTC, dariavladykina commented on concepts/tls-certificate-store.xml
> +      Some of the key benefits of using shared certificate store are:
```suggestion
      Some of the key benefits of using a shared certificate store are:
```

2024-04-29 13:59 UTC, dariavladykina commented on concepts/tls-certificate-store.xml
> +          consistent set of trusted certificates for verifying the authenticity
```suggestion
          consistent set of trusted certificates to verify the authenticity
```

2024-04-29 13:59 UTC, dariavladykina commented on concepts/tls-certificate-store.xml
> +          operating system updates. This ensures that systems remain up-to-date
```suggestion
          operating system updates. This ensures that systems remain up to date
```

2024-04-29 13:59 UTC, dariavladykina commented on tasks/tls-adding-new-certificates.xml
> +    the <command>update-ca-certificates</command> command to update the store.
```suggestion
    To let applications know about a new private CA certificate on the system,
    add it to a system-wide certificate store on the client and use
    the <command>update-ca-certificates</command> command to update the store.
```

2024-04-29 13:59 UTC, dariavladykina commented on tasks/tls-troubleshooting.xml
> +          issuer, no the top level issuer from the certificate chain.
```suggestion
          Describes who issued the certificate. It shows only the parent-level
          issuer, not the top-level issuer from the certificate chain.
```

2024-04-29 13:59 UTC, dariavladykina commented on tasks/tls-troubleshooting.xml
> +          Shows the time period when the certificate is valid.
```suggestion
          Displays certificate validity time.
```

2024-04-29 13:59 UTC, dariavladykina commented on tasks/tls-troubleshooting.xml
> +      <filename>1.pem</filename>, <filename>2.pem</filename> and so on up to the
```suggestion
      <filename>1.pem</filename>, <filename>2.pem</filename> and so on, up to the
```

2024-04-29 13:59 UTC, dariavladykina commented on tasks/tls-troubleshooting.xml
> +      Again, this issuer hash cannot be found among client's root CAs. Continue
```suggestion
      Again, this issuer hash cannot be found among the client's root CAs. Continue
```

2024-04-29 13:59 UTC, dariavladykina commented on tasks/tls-troubleshooting.xml
> +          attribute is <literal>CN</literal> (Common Name) as it contains the
```suggestion
          attribute is <literal>CN</literal> (Common Name), as it contains the
```

2024-05-10 08:56 UTC, lvicoun commented
Hi Tomas,

2024-05-10 09:05 UTC, lvicoun commented
Hi Tomas,
great job! Just a few suggestion. I'd prefer to have two "procedures" in this article - one for install TLS on a trusted CA and one to install the certificate using a private CA. Even though the procedure is outlined in sec 2 I still had problems to follow the flow. I think with the modular approach it is easy to achieve.
Sec 7  System-wide CA certificate store stands there as a concept where I'd expect a procedural part - that is in sec 8. Probably using the concept as part of sec 8 not a standalone section here would work.

2024-05-10 09:06 UTC, lvicoun commented on images/tls-handshake.png
The image has SSL instead of TLS as used in the rest of the article.

2024-05-10 09:16 UTC, lvicoun requested changes

2024-05-10 09:16 UTC, lvicoun commented on tasks/tls-troubleshooting.xml
> +    </calloutlist>
What do I do with those information?

2024-05-10 09:16 UTC, lvicoun commented on tasks/tls-troubleshooting.xml
> +    <title>How do I download server TLS certificate files?</title>
Why one should do that? What problem will this help to solve?

2024-05-10 09:16 UTC, lvicoun commented on tasks/tls-troubleshooting.xml
> +    <title>How do I verify the whole TLS certificate chain?</title>
I think this is more a recommended step after the certificate installation. Or maybe mention when this is necessary?

2024-05-14 08:12 UTC, tbazant commented on tasks/tls-troubleshooting.xml
> +    </calloutlist>
You are just that the certificate that you obtained from the server includes expected information.

2024-05-14 08:13 UTC, tbazant commented on tasks/tls-troubleshooting.xml
> +    <title>How do I download server TLS certificate files?</title>
Because you want to trust the server you are connecting to - and this is the way to go.

2024-05-14 08:14 UTC, tbazant commented on tasks/tls-troubleshooting.xml
> +    <title>How do I verify the whole TLS certificate chain?</title>
It's a troubleshooting section - you want to make sure that the whole certificate chain is trustworthy.

2024-09-12 08:04 UTC, closed without merging