Adding DRAFT status to DC files
SUSE/doc-modular pull request #37
Opened 2021-09-20 16:08 UTC by fsundermeyer

2021-09-21 07:20 UTC, taroth21 requested changes
IIRC, the e-mail-address for bugs needs to be the one registered/used within Bugzilla, therefore changing the one for Dima.

2021-09-21 07:20 UTC, taroth21 commented on xml/concept-klp.xml
> +    <dm:assignee>dpopov@suse.com</dm:assignee>
```suggestion
    <dm:assignee>dmitri.popov@suse.com</dm:assignee>
```

2021-09-21 07:20 UTC, taroth21 commented on xml/concept-zypper.xml
> +    <dm:assignee>dpopov@suse.com</dm:assignee>
```suggestion
    <dm:assignee>dmitri.popov@suse.com</dm:assignee>
```

2021-09-21 07:20 UTC, taroth21 commented on xml/reference-zypper-install.xml
> +    <dm:assignee>dpopov@suse.com</dm:assignee>
```suggestion
    <dm:assignee>dmitri.popov@suse.com</dm:assignee>
```

2021-09-21 07:20 UTC, taroth21 commented on xml/task-check-cpu-temperature.xml
> +     <dm:assignee>dpopov@suse.com</dm:assignee>
```suggestion
     <dm:assignee>dmitri.popov@suse.com</dm:assignee>
```

2021-09-21 07:20 UTC, taroth21 commented on xml/task-create-systemd-timers.xml
>      <dm:assignee>dpopov@suse.com</dm:assignee>
```suggestion
    <dm:assignee>dmitri.popov@suse.com</dm:assignee>
```

2021-09-21 08:27 UTC, merged

2021-10-04 17:07 UTC, sknorr commented
In a way, this is fun -- I specifically updated Docserv2 to not add `--draft` to the command line of docs marked as `beta` [just days earlier](https://github.com/openSUSE/docserv/commit/24382ccb285857f5e653b56f688a5f2423a0e319), because `--draft` also triggers `--meta` + `--remarks` as well, and both of those imo look a bit unprofessional on a published website.

So,

1. Sorry for creating this sort of busywork for you.
2. Should we do something about the fact that DAPS includes meta information and remarks in every `--draft` build? Or do think that is still expected?