[WIP]DOCTEAM-1303: Securing systemd services
SUSE/doc-modular pull request #371
Opened 2024-09-17 11:45 UTC by Amrita42

### Description

Describe the overall goals of this pull request.
The scope is re-haul the existing article and add more content.

### Are there any relevant issues/feature requests?

[DOCTEAM-1303](https://jira.suse.com/browse/DOCTEAM-1303)

### Is this (based on) existing content?

Yes , based on existing content
https://documentation.suse.com/smart/security/html/systemd-securing/index.html#systemd-securing-techniques

2024-11-22 13:30 UTC, taroth21 requested changes
@Amrita42 Many thanks! I'm struggling a bit with section 2. (id="systemd-example-secure-service") and section 2.1 (id="improving-overall-exposure") in the article (see remarks). 2.1 is a 'lone section' (there is no 2.2 or 2.3) which the style guide suggests to avoid. Maybe you can find a way to solve that.

2024-11-22 13:30 UTC, taroth21 commented on concepts/systemd-securing.xml
> +<para>The command upon checking the security settings, assigns a numeric value , also known as <emphasis>exposure level</emphasis>.
Leaving the final editing to Daria, but here I stumbled when reading the sentence because the original word order made it hard to understand the sentence at first glance.

2024-11-22 13:30 UTC, taroth21 commented on tasks/systemd-example-secure-service.xml
> +       Use &systemd; to secure and strengthen services using specific directives and verify the same.
I would specify in the intro already which command you are referring to here (the concrete command is only mentioned in step 4 of the procedure). Maybe even use the same intro like in the following section? 
`Use the command <command>systemd-analyze security</command> to analyze the security settings of a  &systemd; service. `

2024-11-22 13:30 UTC, taroth21 commented on tasks/systemd-example-secure-service.xml
> +                <title>How to improve the overall exposure with options?</title>
```suggestion
                <title>How to improve the exposure level</title>
```

2024-11-22 13:30 UTC, taroth21 commented on tasks/systemd-example-secure-service.xml
> +<screen>
It's the same example like in the previous section (which is good in terms of consistency) but if you have a look at the PDF or HTML output both examples follow each other directly (end of p.4 and beginning of p.5). Therefore it looks to reader like content that is duplicated without a good reason. I would rather omit the example output here and instead give show how to run the `systemd-analyze security` command with one of the following options (so the readers have a concrete example to cling to before you give them the reference list of options.

2024-11-22 13:30 UTC, taroth21 commented on tasks/systemd-example-secure-service.xml
> +                    <tip>
Our schema does not enforce it but I would add a title to all admonitions (also tips) - makes it easier to spot at first sight what the admonition is about.

2024-11-22 13:30 UTC, taroth21 commented on tasks/systemd-example-secure-service.xml
> +                    <tip>
This is the second tip right behind the first... I tend to avoid that in order to not annoy the reader. Maybe consider turning the content of one of them into a normal para.

2024-12-10 09:47 UTC, Amrita42 commented on concepts/systemd-securing.xml
> +<para>The command upon checking the security settings, assigns a numeric value , also known as <emphasis>exposure level</emphasis>.
Yes I agree , its a little confusing , re-phrased

2024-12-10 10:30 UTC, Amrita42 commented on tasks/systemd-example-secure-service.xml
> +                    <tip>
Correct , rephrasing the second tip to make it a <para>

2024-12-11 08:50 UTC, Amrita42 commented on tasks/systemd-example-secure-service.xml
> +<screen>
So here my intention was to highlight the previous example output and how to make it safe using the options . 

I think based on more research , I will re-work this part and add more

2025-01-20 10:39 UTC, Amrita42 commented on tasks/systemd-example-secure-service.xml
> +<screen>
I have added the [Section] part of the service file as an example with some of the options mentioned.

2025-01-21 18:10 UTC, Amrita42 commented
https://github.com/SUSE/doc-modular/pull/414

2025-01-21 18:10 UTC, closed without merging