Updated revhistory entries to unify the structure, : check IDs, dates, titles, punctuation
SUSE/doc-modular pull request #372
Opened 2024-09-20 16:27 UTC by dariavladykina

### Description

Describe the overall goals of this pull request.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2024-09-26 07:22 UTC, dariavladykina commented
A comment: The assembly `articles/SELinux-policy.asm.xml` is a stub, I believe it can be removed.

2024-09-27 16:42 UTC, taroth21 requested changes
Hi @dariavladykina: Many thanks - just two small nitpicks here (see suggestions), otherwise looks good to me. Many thanks!

2024-09-27 16:42 UTC, taroth21 commented on articles/elemental.asm.xml
> +              Updated the title to <quote>Rancher Guide (Elemental)</quote>
```suggestion
              Updated the title to <citetitle>Rancher Guide (Elemental)</citetitle>
```

2024-09-27 16:42 UTC, taroth21 commented on articles/sudo-configure-superuser-privileges.asm.xml
> +              removed section on <quote>Using sudo without root password</quote></para>
```suggestion
            <para>Updated section on creating custom sudo configurations;
              removed section on using sudo without root password</para>
```

2024-09-27 16:42 UTC, taroth21 commented on articles/sudo-configure-superuser-privileges.asm.xml
> +              removed section on <quote>Using sudo without root password</quote></para>
I would rather not quote the exact section titles here but use a descriptive phrase (reason: if the section title is changed later on probably nobody will think of updating the revhistory entry accordingly)

2024-10-07 08:34 UTC, taroth21 approved these changes
LGTM, many thanks!

2024-10-07 12:18 UTC, merged