Jhalackova pxe boot
SUSE/doc-modular pull request #384
Opened 2024-11-12 10:18 UTC by lvicoun

### Description

Adding deployment using the PXE client.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

* old xml:id...
* old URL...

2024-11-12 10:18 UTC, lvicoun commented
[Micro-deployment-pxe_en.pdf](https://github.com/user-attachments/files/17714872/Micro-deployment-pxe_en.pdf)

2024-11-12 14:24 UTC, Vogtinator requested changes

2024-11-12 14:24 UTC, Vogtinator commented on concepts/deployment-network-boot.xml
> +    ready-to-apply configuration examples for DHCP, PXE boot, TFTP, and Wake on LAN. On contrary,
Wake on LAN is orthogonal to PXE deployment

2024-11-12 14:24 UTC, Vogtinator commented on concepts/configure-combustion.xml
> +    provided on the kernel CLI using the <literal>combustion.url</literal> parameter. For details,
There's not really a kernel CLI but rather parameters passed to the kernel

2024-11-12 14:24 UTC, Vogtinator commented on tasks/deployment-network-dhcp.xml
> +     filename "/EFI/x86/grub.efi";
Where is this coming from?

I think there's a section missing about the PXE bootloader and bootloader config setup

2024-11-12 14:24 UTC, Vogtinator commented on tasks/deployment-network-image.xml
> +        The machine should start the deployment. Kernel and initrd are downloaded from the TFTP.
This should go into detail ideally with some screenshots about the deployment process

2024-11-12 14:24 UTC, Vogtinator commented on tasks/deployment-network-tftp.xml
> +              <literal>rd.kiwi.install.image.xz</literal> &ndash; provide the full URL to the
The parameter is called `rd.kiwi.install.image`, without `.xz`

2024-11-12 14:24 UTC, Vogtinator commented on tasks/deployment-network-tftp.xml
> +              installation image <literal>SL-Micro.<replaceable>ARCH</replaceable>&productnumber;.xz</literal>
The other files like `SL-Micro.*.config.bootoptions`, kernel and initrd need to be in the same directory

2024-11-12 14:24 UTC, Vogtinator commented on tasks/deployment-network-tftp.xml
> +              <literal>rd.kiwi.install.pass.bootparam</literal> &ndash; if additional parameters
Maybe it should be explained that after deployment of the image, kiwi performs kexec into the system. This parameter tells kiwi to pass the kernel parameters from deployment to the first boot of the deployed system.

2024-11-12 14:24 UTC, Vogtinator commented on tasks/deployment-network-tftp.xml
> +          <listitem>
This should mention `rd.kiwi.oem.installdevice` as well. If this is provided it performs unattended deployment. Without it, a user has to accept a dialog about overwriting all data.

2024-11-12 14:53 UTC, Vogtinator commented on tasks/deployment-network-dhcp.xml
> +     filename "/EFI/x86/grub.efi";
There it's handled by the installation of the tftpboot-* package: https://documentation.suse.com/sles/15-SP6/html/SLES-all/cha-deployment-prep-pxe.html#sec-deployment-tftp-server-grub-package

We don't have that on SLM, it's up to the user to "somehow" get the kernel+initrd+cmdline booted on the target host.

2024-11-15 14:57 UTC, merged

2024-11-25 13:20 UTC, dariavladykina reviewed
Hi, I've added some comments here. Thanks!