Setting up and Managing NetworkManager
SUSE/doc-modular pull request #400
Opened 2024-12-12 16:12 UTC by harneshalaka

### Description

Smartdoc describing installation, configuration, logging, and troubleshooting NetworkManager.

### Are there any relevant issues/feature requests?

* bsc#...
* jsc#SLE-...

### Is this (based on) existing content?

[* old xml:id...
* old URL...
](https://documentation.suse.com/en-us/sle-micro/6.0/html/Micro-network-configuration/index.html)

2024-12-16 14:03 UTC, lvicoun requested changes
Thanks Shalake for the new fresh insight on this topic :) however, I'd like to propose changes to the article and would like to merge with the SL Micro into a single assembly. Happy to help with the merging :)

2024-12-16 20:10 UTC, taroth21 commented on tasks/networkmanager-nmcli-configure.xml
> +  <screen>nmcli connection modify <replaceable>Nameoftheconnection</replaceable> <replaceable>setting</replaceable> <replaceable>value</replaceable></screen>
Yes, the text within `<replaceable>` should be capitalized - see https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-placeholder

2024-12-17 10:57 UTC, taroth21 requested changes
@harneshalaka : Many thanks, I have added my comments and suggestions now.

2024-12-17 10:57 UTC, taroth21 commented on tasks/networkmanager-nmcli-configure.xml
> +<para>The &nm; creates profile for each Network Interface Controller (NIC). You must create separate profiles for each network to connect the NIC to networks with different settings.</para>
```suggestion
<para>The &nm; creates profile for each Network Interface Controller (NIC).  To connect the NIC to networks with different settings, you must create separate profiles for each network.</para>
```

2024-12-17 10:57 UTC, taroth21 commented on tasks/networkmanager-nmcli-configure.xml
> +   A network bond, <replaceable>NWBOND</replaceable> that uses <varname>active-backup</varname> mode is created.
Maybe you could explain the different bonding modes? (as Tahlia has done in her Code 15-based Smart Doc, see https://documentation.suse.com/smart/network/html/network-bond-managing-devices/index.html#network-bond-modes)

2024-12-17 10:57 UTC, taroth21 commented on tasks/networkmanager-nmcli-configure.xml
> +    <screen>nmcli connection modify <replaceable>NEWCONNECTION</replaceable> ipv4.method manual ipv4.addresses 192.0.2.1/24 ipv4.gateway 192.0.2.254 ipv4.dns 192.0.2.200 ipv4.dns-search example.com</
Please check and make sure to follow our guidelines about example items, see https://documentation.suse.com/style/current/single-html/docu_styleguide/#sec-name

2024-12-19 13:13 UTC, dariavladykina reviewed
Hi! Please see some suggestions from me here. Thanks!

2024-12-20 12:59 UTC, taroth21 commented on articles/SLES-networkmanager-nmcli.asm.xml
> +      <title>Setting up and Managing Network Connections using &nm;</title>
@harneshalaka : This fix for the title was not merged yet, in the PDF that I built after your latest fixes from today the article title still reads: 'Setting up and Managing Network Connections using NetworkManager' . Please change as suggested by @dariavladykina - thanks!

2024-12-20 14:13 UTC, taroth21 requested changes
@harneshalaka : Many thanks for integrating all the feedback! My remaining feedback may look much, but it is actually mostly nitpicks. I provided it in form of suggestions wherever possible, so hopefully applying it should not cause too much work (I hope I got the markup correct everywhere - if not, I'm to blame). ;)

2024-12-20 14:13 UTC, taroth21 commented on references/networkmanager-nm-modify.xml
> +    <title>Modifying network connection</title>
```suggestion
    <title>Modifying network connections</title>
```

2024-12-20 14:13 UTC, taroth21 commented on references/networkmanager-nm-modify.xml
> +          <command>nmcli monitor</command>.</para>
```suggestion
          <command>nmcli monitor</command></para>
```

2024-12-20 14:13 UTC, taroth21 commented on references/networkmanager-nm-modify.xml
> +          <command>nmcli monitor</command>.</para>
I assume the full stop after the command here is a typo, please check!

2024-12-20 14:13 UTC, taroth21 commented on references/networkmanager-nm-enabledisable.xml
> +    <title>Enabling network connection</title>
```suggestion
    <title>Enabling network connections</title>
```

2024-12-20 14:13 UTC, taroth21 commented on references/networkmanager-nm-enabledisable.xml
> +    <title>Disabling network connection</title>
```suggestion
    <title>Disabling network connections</title>
```

2025-01-22 16:37 UTC, dariavladykina reviewed
Hi, please see some suggestions for style and typos here. Thanks!

2025-01-22 16:37 UTC, dariavladykina commented on references/networkmanager-nm-enabledisable.xml
> +       <para>Enable network connection to access and connect devices and resources.</para>
```suggestion
       <para>Enable the network connection to access and connect devices and resources.</para>
```

2025-01-22 16:37 UTC, dariavladykina commented on references/networkmanager-nm-enabledisable.xml
> +    In both cases the changes persist only till the system reboots. After reboot, &nm; and
```suggestion
    In both cases, the changes persist only till the system reboots. After reboot, &nm; and
```

2025-01-22 16:37 UTC, dariavladykina commented on tasks/networkmanager-nmcli-logging.xml
> +  <para><emphasis>TRACE</emphasis>&mdash;logs very detailed usually unimportant events. For example, packet-level details.</para>
```suggestion
  <para><emphasis>TRACE</emphasis>&mdash;logs very detailed, usually unimportant events. For example, packet-level details.</para>
```

2025-01-22 16:37 UTC, dariavladykina commented on tasks/networkmanager-nmcli-logging.xml
> +To change a logging level on particular domains, for example to set <literal>DEBUG</literal> on
```suggestion
To change a logging level on particular domains, for example, to set <literal>DEBUG</literal> on
```

2025-01-22 16:37 UTC, dariavladykina commented on tasks/networkmanager-nmcli-logging.xml
> +To view the &nm; logs realtime:
```suggestion
To view the &nm; logs in real time:
```

2025-01-22 16:37 UTC, dariavladykina commented on tasks/networkmanager-nmcli-logging.xml
> +The following list provides commands to manage &nm; logs using <command>journald</command>
```suggestion
The following list provides commands to manage &nm; logs using <command>journald</command>.
```

2025-01-22 16:37 UTC, dariavladykina commented on references/networking-nmcli.xml
> +        subcommands of the <command>nmcli</command> command, you can use to interact with &nm;
```suggestion
        subcommands of the <command>nmcli</command> command you can use to interact with &nm;
```

2025-01-22 16:37 UTC, dariavladykina commented on references/networking-nmcli.xml
>                with DHCP, and disables the connection's
```suggestion
              with DHCP and disables the connection's
```

2025-01-22 16:37 UTC, dariavladykina commented on tasks/networkmanager-nmcli-troubleshoot.xml
> +    If network is not working, this may be caused &nm; itself. To check that proceed as follows:
```suggestion
    If the network is not working, this may be caused by &nm; itself. To check that, proceed as follows:
```

2025-01-22 16:37 UTC, dariavladykina commented on tasks/networkmanager-nmcli-troubleshoot.xml
> +      View the list of Wi-fi connections
```suggestion
      View the list of Wi-Fi connections:
```

2025-01-22 16:37 UTC, dariavladykina commented on tasks/networkmanager-nmcli-troubleshoot.xml
> +      If the particular device is listed, verify that the Wi-fi connection is active:
```suggestion
      If a particular device is listed, make sure its Wi-Fi connection is active:
```

2025-01-27 11:56 UTC, merged