Toba/task installing virtualization components
SUSE/doc-modular pull request #42
Opened 2021-11-11 10:57 UTC by tbazant

This new article describes how to install virtualization environment.
Rendered PDF is attached 
[task-install-virtualization-components_color_en.pdf](https://github.com/SUSE/doc-modular/files/7519854/task-install-virtualization-components_color_en.pdf)

2021-11-11 15:54 UTC, cjschroder requested changes
This looks good, other than missing a few 'the' and 'a'.

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +    To install &kvm; environment, consider the following patterns:
To install the &kvm; environment

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +    To install &xen; environment, consider the following patterns:
To install the &xen; environment

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +    or <guimenu>Xen Virtualization Host</guimenu> roles. The appropriate
or the `<guimenu>`Xen

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +    <title>Installing &kvm; environment</title>
Installing the &kvm; environment

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +     To install &kvm; virtualization environment and related tools, proceed as
To install the &kvm; virtualization environment

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +    <title>Installing &xen; environment</title>
Installing the &xen; environment

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +     To install &xen; virtualization environment, proceed as follows:
To install the &xen; virtualization environment

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +      Start &yast; and elect<menuchoice> <guimenu>Virtualization</guimenu>
Start &yast; and select

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +    these patterns to install a specific virtualization components on an
install specific (no "a")

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +       Installs basic &vmhost; with &kvm; and &qemu; environment.
Installs a basic &vmhost; with the &kvm; and &qemu; environments.

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +       Installs basic &xen; &vmhost;.
Installs a basic

2021-11-11 15:54 UTC, cjschroder commented on xml/task-install-virtualization-components.xml
> +   environment.
using your preferred

2021-11-11 15:59 UTC, cjschroder commented on DC-task-install-virtualization-components
> +ROOTID="task-example"
should be ROOTID="task-install-virtualization-components"

2021-11-12 08:32 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +    </para>
you're right, i'll limit this

2021-11-12 08:37 UTC, tbazant reviewed
Agreed on Carla's suggestions, thanks!

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +     12&nbsp;SP5, 12&nbsp;SP4, 12&nbsp;SP3
```suggestion
     &sles;&nbsp;15&nbsp;SP3
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +    or <guimenu>Xen Virtualization Host</guimenu> roles. The appropriate
```suggestion
    or the <guimenu>Xen Virtualization Host</guimenu> roles. The appropriate
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +    <title>Installing &kvm; environment</title>
```suggestion
    <title>Installing the &kvm; environment</title>
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +     To install &kvm; virtualization environment and related tools, proceed as
```suggestion
     To install the &kvm; virtualization environment and related tools, proceed as
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +    <title>Installing &xen; environment</title>
```suggestion
    <title>Installing the &xen; environment</title>
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +     To install &xen; virtualization environment, proceed as follows:
```suggestion
     To install the &xen; virtualization environment, proceed as follows:
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +      Start &yast; and elect<menuchoice> <guimenu>Virtualization</guimenu>
```suggestion
      Start &yast; and select<menuchoice> <guimenu>Virtualization</guimenu>
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +    these patterns to install a specific virtualization components on an
```suggestion
    these patterns to install specific virtualization components on an
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +    To install &kvm; environment, consider the following patterns:
```suggestion
    To install the &kvm; environment, consider the following patterns:
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +       Installs basic &vmhost; with &kvm; and &qemu; environment.
```suggestion
       Installs basic &vmhost; with the &kvm; and &qemu; environments.
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +    To install &xen; environment, consider the following patterns:
```suggestion
    To install the &xen; environment, consider the following patterns:
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +       Installs basic &xen; &vmhost;.
```suggestion
       Installs a basic &xen; &vmhost;.
```

2021-11-12 08:37 UTC, tbazant commented on xml/task-install-virtualization-components.xml
> +   to create, run, and manage virtual machines using preferred virtualization
```suggestion
   to create, run, and manage virtual machines using your preferred virtualization
```

2021-11-12 08:39 UTC, tbazant reviewed
Suggestions merged

2021-11-12 08:39 UTC, merged