Template overhaul for next generation Smart Docs
SUSE/doc-modular pull request #47
Opened 2022-03-28 15:17 UTC by janajaeger

- add assembly template with minimal set of metadata
- add glue topic template
- revisit existing reference, task, concepts and make them assembly-ready

2022-04-20 07:19 UTC, tomschr requested changes
@janajaeger Looks very good! Thanks for your efforts. I've added some suggestions, maybe they helps. :slightly_smiling_face: Let me know if you have any questions.

2022-04-20 07:19 UTC, tomschr commented on templates/xml/assembly.xml
> +    <phrase role="language"><!-- comma-separated list of languages --></phrase>
Would add some examples like:

```suggestion
    <phrase role="language"><!-- comma-separated list of languages, for example en-us,de-de,cs-cz --></phrase>
```

2022-04-20 07:19 UTC, tomschr commented on templates/xml/assembly.xml
> +-->
Maybe remove them completely? It would just add too much noise as we aren't sure how to deal with them ATM.

```suggestion
```

2022-04-20 07:19 UTC, tomschr commented on templates/xml/assembly.xml
> +  <output renderas="article"/>
Maybe we should use book instead of article here? This would better align with the stylesheets and the layout. However, we would need to change the `<output renderas="..."/>` element as well.

2022-04-20 07:19 UTC, tomschr commented on templates/xml/assembly.xml
> +  <!-- pull in a topic as is -->
I would amend the comment with:

```suggestion
  <!-- pull in a topic as is -->
  <!-- refer in resourceref to the ID defined in the <resource> element
```

2022-05-05 15:05 UTC, janajaeger commented on templates/xml/assembly.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
I rather like the .asm thing. If daps can be taught to recognize it :) Keeping them named .xml might indeed confuse writers.

2022-05-05 15:21 UTC, janajaeger commented on templates/xml/assembly.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Actually, having assemblies in their own subdir as suggested by Frank is much more feasible. Three cheers for pragmatism :)

2022-05-05 15:56 UTC, janajaeger commented on templates/xml/assembly.xml
> +-->
I would vote to keep it in. We can't afford to not deal with it and we probably need a reminder to do so.

2022-05-05 15:57 UTC, janajaeger commented on templates/xml/assembly.xml
> +  <output renderas="article"/>
Whatever works best. Does this also affect the nesting of sets and such?

2022-12-13 20:40 UTC, tomschr reviewed
Thanks for the assembly joint venture. Was fun! :smile: 
I have some further comments, suggestions, and ideas.

2022-12-13 20:40 UTC, tomschr commented on templates/DC-article
> +ROOTID="article-example"
Maybe add a comment so we know _where_ to find it:

```suggestion
# Point to the ID of the <structure> of your assembly
ROOTID="article-example"
```

2022-12-13 20:40 UTC, tomschr commented on templates/DC-glue
> +# This file originates from the project https://github.com/openSUSE/doc-kit
Do we really need that? Not sure if such a thing can (or should) stand on its own. :thinking:

2022-12-13 20:40 UTC, tomschr commented on templates/README.md
> +* `glue.xml`: Navigation (e.g. if your topic is very complex and you want to provide additional guidance on how to use it)
Is it really only navigation? Maybe find a better description. Maybe something like "combines text or structures that doesn't fit into the previous units. [...]"?

2022-12-13 20:40 UTC, tomschr commented on templates/README.md
> +### ID naming conventions
Should we add here the distinction between Assembly IDs (at the moment, starting with underscore) and normal IDs?

2022-12-13 20:40 UTC, tomschr commented on templates/xml/assembly.xml
> +   <meta name="updated" content="date of last update as B d, Y"/>
:bulb: I'm wondering if we should add "useful" and meaningful content into the respective `<meta>` tag. We could add the description in some comments above.

The reason why I mention this is, that in the future GeekoDoc might be able to introduce some restrictions and validates them (if I find out how). For example, it could be dates, boolean values, languages etc. If you write "yes or no" but GeekoDoc expects a boolean, it will fail.

2022-12-14 06:25 UTC, janajaeger commented on templates/README.md
> +* `glue.xml`: Navigation (e.g. if your topic is very complex and you want to provide additional guidance on how to use it)
Totally agreed. I'm on it!

2022-12-14 10:44 UTC, janajaeger commented on templates/xml/assembly.xml
> +   <meta name="updated" content="date of last update as B d, Y"/>
Care to elaborate?

2022-12-14 13:39 UTC, tomschr commented on templates/xml/assembly.xml
> +   <meta name="updated" content="date of last update as B d, Y"/>
Sure! To make my point, we use the line 47 as an example.

Let's assume for the moment, GeekoDoc is able to validate all the `<meta>` content. Let's further assume, this `<meta name="updated">` expects a date as datatype in its `content` attribute. Therefor the content in this example can't be a string. It has to be a date format. There are some options to allow dates in RELAX NG. However, it is easier to parse dates in  ISO format (year-month-day). IN other words, the explanation can't be added in the `content` attribute, it has to be separate.

If we combine all these things, my suggestion would be something like this:

```suggestion
   <!-- ISO date of last update as YYYY-MM-DD -->
   <meta name="updated" content="2022-12-14"/>

```

The first line is a XML comment that describes the next line. This next line contains an (arbitrary) example that is a valid datatype.

Same for the other meta data.

If you apply this idea to all meta data, every data contains a XML comment, the `<meta>` tag and its valid data, followed by an optional line break.

Does that make sense?

2022-12-14 14:36 UTC, janajaeger commented on templates/xml/assembly.xml
> +   <meta name="updated" content="date of last update as B d, Y"/>
yup, this makes total sense!

2022-12-14 16:01 UTC, janajaeger commented on templates/xml/assembly.xml
> +   <meta name="updated" content="date of last update as B d, Y"/>
Applied.

2023-01-16 15:56 UTC, tomschr commented
The failure comes from daps as it doesn't recognize (yet) the `<assembly>` element. Maybe we could merge it once Frank has released DAPS 4.0?

2023-02-24 13:01 UTC, merged