Tasks for adding and deleting modules
SUSE/doc-modular pull request #9
Opened 2021-08-20 03:48 UTC by tahliar

Rendered PDFs:

[task-add-modules-extensions-after-installation_color_en.pdf](https://github.com/SUSE/doc-modular/files/7018999/task-add-modules-extensions-after-installation_color_en.pdf)

[task-delete-modules-extensions_color_en.pdf](https://github.com/SUSE/doc-modular/files/7019002/task-delete-modules-extensions_color_en.pdf)

2021-08-20 08:09 UTC, tahliar commented
`-list-extensions` is what's in the Deployment Guide (and it works), but `--list-extensions` is what's in the SUSEConnect help output, and is a more standard convention, so I've updated it.

2021-08-20 16:58 UTC, lproven requested changes

2021-08-20 16:58 UTC, lproven commented on xml/task-add-modules-extensions-after-installation.xml
> + </section>
Gosh that's a big list!

At first I was going to suggest making it hierarchical but on a 2nd reading, how about listing versions and products separately?

This applies to versions 12 SP3 through to 15 SP3 of:
[prod list]

Or even 

This applies to: [product list]
And these versions [version list]

Something like that. It's horribly repetitive to my eyes.

I welcome others' opinions on this.

2021-08-20 16:58 UTC, lproven commented on xml/task-add-modules-extensions-after-installation.xml
> +    All extensions require additional registration codes which are liable for cost.
"Liable _for_ cost" is clumsy.

"Which may incur additional licence costs"?

2021-08-20 16:58 UTC, lproven commented on xml/task-add-modules-extensions-after-installation.xml
> +     extensions require additional registration codes, which are liable for cost.
See above comment.

2021-08-20 16:58 UTC, lproven commented on xml/task-add-modules-extensions-after-installation.xml
> +     then activate <guimenu>I Agree to the License Terms</guimenu> and click
"Activate" seems clumsy. "Click"? "Select"? "Pick" or "Choose"?

2021-08-22 23:12 UTC, tahliar commented on xml/task-add-modules-extensions-after-installation.xml
> +     then activate <guimenu>I Agree to the License Terms</guimenu> and click
Normally I would say "Select", but our Style Guide says to use "Activate" for check boxes.

2021-08-22 23:22 UTC, tahliar commented on xml/task-add-modules-extensions-after-installation.xml
> + </section>
This is a (temporary) part of the templates, so any changes would need to be applied to the templates as well. 

I think it's in list form for metadata reasons, but @taroth21 will know more.

2021-08-30 02:03 UTC, merged