Inital version of the Smart Docs reference doc "Working with systemd timers"
SUSE/doc-modular pull request #98
Opened 2023-03-02 10:15 UTC by fsundermeyer

This PR adds a Smart Docs article "Working with systemd timers". It is 

- using the new directory structure we intend to use for all smart docs
- using the new templates (that can also be found in the templates/ directory)
- has been considerably extended compared to the original content

The intention is to use this document as a refernce for upcomin trainings and as a "template" for writers in the future. Because of that I am including more reviewers that usual - this one needs to be good! ;-D
I tried to do my best, but I am sure there still is lots of errors. When reviewing, please consider the following:

- style guide compliance, language, grammar, etc (Daria)
- SEO
- source code formatting, correct use of tags, entities, ...
- content:
  - does it meet our claim for a good smart docs article
  - is something missing, does it answer all potential questions a customer may have on systemd timers (or have at least pointers to resources that may answer additional questions)
    - specifically: does a potential migration to cron need more information 
  - is the structure of the article OK
- ....  

BTW: The original content (copied from SLE 15) can be foung here: https://documentation.suse.com/smart/linux/html/task-create-systemd-timers/task-create-systemd-timers.html

2023-03-02 11:31 UTC, tomschr requested changes
@fsundermeyer Very good work! :+1: I left some ideas and suggestions.

2023-03-02 11:31 UTC, tomschr commented on references/systemd_timer_types.xml
> +        </itemizedlist>
This is a "lonely item" which Rebecca wouldn't approve. :wink: 

I think, you could remove the list foo and just you the screen:

```suggestion
        <para>10am on week days and at 10pm on weekends:</para>
        <screen>OnCalendar=Mon..Fri *-*-* 10:00
OnCalendar=Sat,Sun *-*-* 22:00</screen>
```

2023-03-02 11:31 UTC, tomschr commented on references/systemd_timer_types.xml
> +              systemservices this is almost equal to <literal>OnActiveSec</literal>. Use this for
Space missing?

```suggestion
              system services this is almost equal to <literal>OnActiveSec</literal>. Use this for
```

2023-03-02 11:31 UTC, tomschr commented on tasks/systemd_mailto.xml
> +        Note that you need to replace <replaceable>user</replaceable> in the file name with the
Styleguide requires to have capital names for replaceables:


```suggestion
        <filename>/etc/systemd/system/send_email_to_<replaceable>USER</replaceable>@.service</filename>.
        Note that you need to replace <replaceable>USER</replaceable> in the file name with the
```

2023-03-02 11:31 UTC, tomschr commented on tasks/systemd_mailto.xml
> +        <replaceable>e-mail_address</replaceable> in the file with the login and the e-mail address
Same here:

```suggestion
ExecStart=/usr/local/bin/send_systemd_email <replaceable>EMAIL_ADDRESS</replaceable> %i
User=root
Group=systemd-journal
</screen>
      <para>
        Note that you need to replace <replaceable>USER</replaceable> and
        <replaceable>EMAIL_ADDRESS</replaceable> in the file with the login and the e-mail address
```

2023-03-02 11:31 UTC, tomschr commented on tasks/systemd_mailto.xml
> +      <screen>systemd-analyze verify /etc/systemd/system/send_email_to_<replaceable>user</replaceable>@.service</screen>
```suggestion
      <screen>systemd-analyze verify /etc/systemd/system/send_email_to_<replaceable>USER</replaceable>@.service</screen>
```

2023-03-02 11:31 UTC, tomschr commented on tasks/systemd_mailto.xml
> +      <screen>sudo systemctl start send_email_to_<replaceable>user</replaceable>@dbus.service</screen>
```suggestion
      <screen>sudo systemctl start send_email_to_<replaceable>USER</replaceable>@dbus.service</screen>
```

2023-03-02 11:31 UTC, tomschr commented on tasks/systemd_mailto.xml
> +        If successful, <replaceable>e-mail_address</replaceable> will receive an e-mail with the
```suggestion
        If successful, <replaceable>EMAIL_ADDRESS</replaceable> will receive an e-mail with the
```

2023-03-02 11:31 UTC, tomschr commented on tasks/systemd_mailto.xml
> +OnFailure<co xml:id="systemd-mailto-onfailure"/>=send_email_to_<replaceable>user</replaceable><co xml:id="systemd-mailto-user"/>@%n<co xml:id="systemd-mailto-name"/>.service
```suggestion
OnFailure<co xml:id="systemd-mailto-onfailure"/>=send_email_to_<replaceable>USER</replaceable><co xml:id="systemd-mailto-user"/>@%n<co xml:id="systemd-mailto-name"/>.service
```

2023-03-02 11:31 UTC, tomschr commented on tasks/systemd_timer_user.xml
> +    </listitem>
Although this is correct, maybe you could add another item? Perhaps it would be helpful to advocate/mention to our readers to use `systemctl edit --user --force --all <SERVICENAME>`.

This has the advantage that the user doesn't have to remember the path. It will automatically be placed in the right directory.

2023-03-02 11:31 UTC, tomschr commented on tasks/systemd_timer_troubleshoot.xml
> +  <section>
Would a FAQ here more useful? User come to this sections when they have a problem. And questions. Perhaps you could phrase questions out of these subsections?

2023-03-02 11:31 UTC, tomschr commented on tasks/systemd_timer_troubleshoot.xml
> +    <title>Avoiding errors</title>
Just an idea: what if I want to _modify_ an already existing timer? Maybe the user wants to prolong the time, start it in different intervals etc. Would that be an useful addition?

Perhaps this is more useful for a normal section and not for troubleshooting (as it's not a problem).

2023-03-02 11:44 UTC, dmpop commented on references/systemd_timer_types.xml
> +              systemservices this is almost equal to <literal>OnActiveSec</literal>. Use this for
```suggestion
              systemservices this is almost equal to <literal>OnActiveSec</literal>. Use this for
```

It's either equal or not. If it's not equal, then it's similar.

2023-03-02 11:44 UTC, dmpop commented on references/systemd_timer_types.xml
> +          used. If no unit is specified, seconds are assumed. The following units can be used:
```suggestion
          Values are defined as time units (minutes, hours, days, month, years etc.). The following units are supported:
```

2023-03-02 11:44 UTC, dmpop commented on references/systemd_timer_types.xml
> +          Transient timers are temporary timers only valid for the current session. Using these
```suggestion
          Transient timers are temporary timers that are only valid for the current session. Using these
```

2023-03-02 11:44 UTC, dmpop commented on references/systemd_timer_types.xml
> +          timers you can either use an existing service file or directly start a program. Transient
```suggestion
          timers, you can either use an existing service file or directly start a program. Transient
```

2023-03-02 11:44 UTC, dmpop commented on references/systemd_timer_types.xml
> +          To run a command directly use the following syntax. In this example the script
```suggestion
          To run a command directly use the following syntax. In this example, the script
```

2023-03-02 11:44 UTC, dmpop commented on references/systemd_timer_types.xml
> +          Transient timers can be of types monotonic or real time. The following switches, working
```suggestion
          Transient timers can be monotonic or real time. The following switches, that works
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        In the following example we are using the <command>mailx</command> command from package
```suggestion
        In the following example, we are using the <command>mailx</command> command from package
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        automatically provided by the unit file running the mail script.
```suggestion
        service file for which the failure notification will be received. Both parameters are supplied by the unit file running the mail script.
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        Make sure the scrtipt you just created is executable:
```suggestion
        Make sure the script is executable:
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +           <guimenu>Network Services</guimenu> <guimenu>Mail Server</guimenu></menuchoice>.
```suggestion
          To send emails, you need to install and configure the email server
          Postfix on your system. This can be done by choosing <menuchoice><guimenu>&yast;</guimenu>
           <guimenu>Network Services</guimenu> <guimenu>Mail Server</guimenu></menuchoice>.
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        login of the user that should receive the email.
```suggestion
        Replace <replaceable>user</replaceable> in the file name with the
        login of the user that should receive the email.
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        Note that you need to replace <replaceable>user</replaceable> and
```suggestion
       Replace <replaceable>user</replaceable> and
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        parameter).
Too many parentheses.

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        reported:
```suggestion
       Verify the service file, and fix the reported issues:
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        Now start the service using the <literal>dbus</literal> instance for testing (you may use
```suggestion
        Now start the service using the <literal>dbus</literal> instance for testing (you can use
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        is guaranteed to run on any installation).
```suggestion
        any other service that is currently running. dbus is used in this example, because the service
        is guaranteed to run on any installation).
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        If the test e-mail has been successfully send, proceed by integrating it into your service
```suggestion
        If the test e-mail has been successfully sent, proceed by integrating it into your service
```

Integrating what? Email? Also _proceed by integrating_ can be replaced with _include_

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +        To add e-mail notification to your service, add an <literal>OnFailure</literal> option to the
```suggestion
        To add e-mail notification to the service, add an <literal>OnFailure</literal> option to the
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +            Replace with the login name part of the service unit's file name.
```suggestion
            Replace with the login name part of the service unit's file name.
```

This sentence makes no sense. Replace _what_ in _where_?

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +            Provides the name of the service (<literal>helloworld</literal> in this example). This
```suggestion
            Specifies the name of the service (<literal>helloworld</literal> in this example). This
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +          While the e-mail script is generic, the email service file has the recipient's e-mail
> While the e-mail script is generic

What does _generic_ mean? Also, _because_ is better than _while_

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +          within the copy.
```suggestion
          address hard-coded. T send notification emails to a different user, copy the
          e-mail service file, and replace the user login in the file name and the e-mail address
          within the copy.
```

> replace the user login in the file name and the e-mail address within the copy.

That's confusing.

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +          To send a failure notification to several people at the same time, add the respective
```suggestion
          To send a failure notification to several recipients simultaneously, add the respective
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_mailto.xml
> +          service files space-separated to the service file:
```suggestion
          service files  to the service file (use spaces as separators):
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_catching_up_missed_runs.xml
> +        With systemd timers you can make leeway for missed timer events.
```suggestion
        With systemd timers, you can make leeway for missed timer events.
```

Make leeway? I think you can _have_ leeway_ but you can't make it. Also, leeway is a colloquial word.

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_create.xml
> +        every 24 hours relative to it's activation time. It also runs Monday to Friday at 10am.
```suggestion
        every 24 hours relative to its activation time. It also runs Monday to Friday at 10am.
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_create.xml
> +          need to enable it:
```suggestion
          Enable the timer to make sure that it is activated on boot:
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_create.xml
> +      </para>
```suggestion
        This is a minimum you need for a service file to work. For advanced configuration, refer to ??
      </para>
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_create.xml
> +          service files for timers, since this information is provided with the timer file.
```suggestion
          &systemd; service files normally contain an <literal>[Install]</literal> section, that determines one or more targets for a service to load. This section is not required in
          service files for timers, since this information is provided with the timer file.
```

Frank, you know that `target(s)` is a mortal writing sin, right? :wink:

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_create.xml
> +            Specifies a timer that triggers the service at fixed points in time (here: Monday to
```suggestion
            Specifies a timer that triggers the service at fixed points in time (in this example, Monday to
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_create.xml
> +            The service file that is to be executed.
```suggestion
            The service file to execute.
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_create.xml
> +        Note that there is now equivalent for <literal>OnUnitActiveSec</literal> in cron.
```suggestion
        Note that there is no equivalent for <literal>OnUnitActiveSec</literal> in cron.
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_mailto.xml
> +        workaround to get email notifications when a timer fails.
I've made a suggestion for this specific fragment somewhere above.

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_mailto.xml
> +    You need to
Same.

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_mailto.xml
> +        the timer.
Remove periods in list items.

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_mailto.xml
> +           <guimenu>Network Services</guimenu> <guimenu>Mail Server</guimenu></menuchoice>.
Yeah, same here. I've already went through this.

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_troubleshoot.xml
> +          runs without problems.
```suggestion
          Verify that the executable you specify in the service with <literal>ExecStart</literal>
          runs correctly.
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_troubleshoot.xml
> +      these errors. Given is the following example:
```suggestion
      When you activate a timer that contains non-critical errors, &systemd;a silently ignores them. For example:
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_troubleshoot.xml
> +      <command>journalctl</command>. To filter the journal for what matters, use the
```suggestion
      <command>journalctl</command>. To filter the journal for relevant information, use the
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_troubleshoot.xml
> +      corresponding service file:
```suggestion
      <option>-u</option> switch to specify the systemd timers and service files. Use this option so that   it shows the log entries for the timer <emphasis>and</emphasis> the
      corresponding service file:
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_troubleshoot.xml
> +      troublewshooting timers:
```suggestion
      to man journalctl for in-depth information. The following options are useful for
      troubleshooting timers:
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_troubleshoot.xml
> +          <option>-x</option>: Show explanatory help texts alongside the log entry.
```suggestion
          <option>-x</option>: Show help texts alongside the log entry.
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_user.xml
> +    automate reoccuring tasks like regular backups, processing images, or moving data to the
```suggestion
    automate recurring tasks like regular backups, processing images, or moving data to the
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_user.xml
> +        All <command>systemctl</command> and <command>journalctl</command> command need to be run
```suggestion
        All <command>systemctl</command> and <command>journalctl</command> command must be run
```

2023-03-02 11:44 UTC, dmpop commented on tasks/systemd_timer_user.xml
> +          As a regular user, you should provide the path to the unit files as in the examples
```suggestion
          As a regular user, you must provide the path to the unit files as in the examples
```

2023-03-02 11:50 UTC, lvicoun commented on glues/systemd-timers-more-info.xml
> +        <link xlink:href="https://documentation.suse.com/smart/linux/html/concept-systemd/concept-systemd.html">Basic systemd concepts</link>
Is there a way to use xrefs here?

2023-03-02 11:51 UTC, fsundermeyer commented on articles/systemd_timer_working_with.xml
> +     <meta name="architecture" content="x86_64;zseries;power;aarch64"/>
You tell me

2023-03-02 12:25 UTC, lvicoun reviewed
Great job, Frank! However, I think the section Timer types should be at least referenced from the example explained, otherwise it just sticks there out of nowhere.

2023-03-02 12:25 UTC, lvicoun commented on concepts/systemd-timer-concept.xml
> +    Similar to cron, systemd timer units provide a mechanism for scheduling jobs on Linux. Although
Could the concept be just about systemd itself? There can be a section which compares cron and systemd, but I don't think it should be the main focus of the concept as systemd has been here for a while and I suppose the user came here because of systemd.

2023-03-02 12:48 UTC, janajaeger commented on glues/systemd-timers-more-info.xml
> +        <link xlink:href="https://documentation.suse.com/smart/linux/html/concept-systemd/concept-systemd.html">Basic systemd concepts</link>
No. Not yet, anyway. We have to use web links in the meantime.

2023-03-02 14:07 UTC, tomschr commented on articles/systemd_timer_working_with.xml
> +       <itemizedlist>
Please avoid the bridgehead. Use the following structure instead:

```suggestion
       <itemizedlist>
         <title>Requirements</title>
```

At the moment, the list title doesn't appear, but I've filed issue openSUSE/suse-xsl#535.

2023-03-02 15:19 UTC, fsundermeyer commented on articles/systemd_timer_working_with.xml
> +               Linux. Migrate to systemd timers as a modern replacement of cron.
Rephrased with " Learn how to set up, manage and operate systemd timers, a modern replacement of
cron, for scheduling tasks on Linux."

2023-03-02 16:10 UTC, fsundermeyer commented on articles/systemd_timer_working_with.xml
> +               you run from the timer and for with you would like to receive the notification.
Replaced with "from the service that the timer controls, call the created email service file via
               <literal>OnFailure</literal>"

2023-03-02 16:12 UTC, fsundermeyer commented on glues/systemd-timers-more-info.xml
> +        <link xlink:href="https://documentation.suse.com/smart/linux/html/concept-systemd/concept-systemd.html">Basic systemd concepts</link>
Fixed

2023-03-02 16:13 UTC, fsundermeyer commented on references/systemd_timer_manage.xml
> +        list-timers</command> shows you all timers available on a host.
Fixed

2023-03-02 16:21 UTC, fsundermeyer commented on references/systemd_timer_manage.xml
> +        <screen>&prompt.root;systemctl status helloworld.timer
Fixed

2023-03-02 16:21 UTC, fsundermeyer commented on references/systemd_timer_manage.xml
> +    To list all timers available on the system, use <command>systemctl list-timers</command>. The
Fixed

2023-03-02 16:23 UTC, fsundermeyer commented on references/systemd_timer_manage.xml
> +    <title>Listing timers</title>
Fixed

2023-03-02 16:23 UTC, fsundermeyer commented on references/systemd_timer_manage.xml
> +          <literal>ACTIVATES</literal> shows the name the service the timer activates when it runs.
Fixed

2023-03-02 16:25 UTC, fsundermeyer commented on references/systemd_timer_types.xml
> +        </itemizedlist>
...but it uses the same strcuture and format as the previous list, therefore making it much easier to read. I'll rather not change this

2023-03-02 16:26 UTC, fsundermeyer commented on tasks/systemd_mailto.xml
> +        parameter).
Fixed

2023-03-02 16:31 UTC, fsundermeyer commented on tasks/systemd_mailto.xml
> +          While the e-mail script is generic, the email service file has the recipient's e-mail
Fixed

2023-03-02 16:33 UTC, fsundermeyer commented on tasks/systemd_timer_create.xml
> +            targets refer to ???.
Fixed

2023-03-02 16:43 UTC, fsundermeyer commented on tasks/systemd_mailto.xml
> +        Note that you need to replace <replaceable>user</replaceable> in the file name with the
Fixed

2023-03-02 16:44 UTC, fsundermeyer commented on tasks/systemd_mailto.xml
> +        <replaceable>e-mail_address</replaceable> in the file with the login and the e-mail address
Fixed

2023-03-02 16:44 UTC, fsundermeyer commented on articles/systemd_timer_working_with.xml
> +           <term>GOAL!</term>
Fixed

2023-03-03 13:53 UTC, tbazant commented on articles/systemd_timer_working_with.xml
> +               Learn how to set up and use systemd timer for scheduling tasks on Linux.
```suggestion
               Learn how to set up and use &systemd; timer for scheduling tasks on Linux.
```

2023-03-03 14:02 UTC, tbazant commented on concepts/systemd-timer-concept.xml
> +    systemd timer units serve the same purpose as cron, they offer several advantages:
Remove cron mentions and list the advantages as features.

2023-03-03 14:07 UTC, tbazant commented
What is the advantage of having article types in specific directories, such as `tasks` or `concepts` apart from unnecesity of prepending filenames with `concept-` etc?

2023-03-03 16:54 UTC, fsundermeyer commented on tasks/systemd_timer_user.xml
> +          As a regular user, you should provide the path to the unit files as in the examples
Fixed

2023-03-06 12:49 UTC, tbazant requested changes
A good and huge job actually :-) See some comments

2023-03-06 12:49 UTC, tbazant commented on articles/systemd_timer_working_with.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
General notes:
* Use &systemd; consistently throughout the document
* align/add prompts in &lt;screen/>'s
* leave out cron completely

2023-03-06 12:49 UTC, tbazant commented on references/systemd_timer_types.xml
> +          For more information refer to <command>man 1 systemd-run</command>.
Shall we list 'For more info' items in a dedicated section or like this in a normal paragraph?

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_mailto.xml
> +      <screen>sudo systemctl start send_email_to_<replaceable>USER</replaceable>@dbus.service</screen>
```suggestion
      <screen>&prompt.sudo;systemctl start send_email_to_<replaceable>USER</replaceable>@dbus.service</screen>
```

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_timer_catching_up_missed_runs.xml
> +  <title>&systemd; timer: Catching up on missed runs</title>
i had to search for 'catch up', would 'Executing missed runs' be better?

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_timer_catching_up_missed_runs.xml
> +        With systemd timers, you can make leeway for missed timer events.
-||- for 'leeway'

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_timer_create.xml
> +          This will activate the timer for the current session only.
```suggestion
          Activates the timer for the current session only.
```

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_timer_catching_up_missed_runs.xml
> +    enable this, add the configuration option <literal>Persisten=true</literal> to the Timer
```suggestion
    enable this, add the configuration option <literal>Persisten=true</literal> to the <literal>[Timer]</literal>
```

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_timer_create.xml
> +            The system target in which the timer get activated. For more information on systemd
```suggestion
            The &systemd; target in which the timer geta activated. For more information on &systemd;
```

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_timer_test_cal_entries.xml
> +    accepts the same argument than the <literal>OnCalendar</literal> entry required to set up
```suggestion
    accepts the same argument as the <literal>OnCalendar</literal> entry required to set up
```

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_timer_test_cal_entries.xml
> +    and UTC). It will also show the string in <literal>Normalized form</literal>, it is recommended
is the future tense needed?

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_timer_test_cal_entries.xml
> +    to use that string in the timer file.
```suggestion
  <para>
   You can concatenate several arguments separated by space. If the term
    to test is correct, the output will show you when the timer is triggered next (in loca tuime
    and UTC). It will also show the string in <literal>Normalized form</literal>, it is recommended
    to use that string in the timer file. Consider the following examples:
```

2023-03-06 12:49 UTC, tbazant commented on tasks/systemd_timer_troubleshoot.xml
> +      <option>-u</option> switch to specify the systemd timers and service files. Use this option so that   it shows the log entries for the timer <emphasis>and</emphasis> the
```suggestion
      <option>-u</option> switch to specify the systemd timers and service files. Use this option to show the log entries for the timer <emphasis>and</emphasis> the
```

2023-03-06 18:25 UTC, taroth21 requested changes
Hi Frank, overall: very well done! I started with some comments here but then decided to go through the PDF because it was much easier to comment on issues when you see them in the order as they appear in the article. 

I will therefore attach an annotated PDF as well where you will find the rest of my comments. (In can still transfer them into GH comments if you like).  

[systemd-working-with-timers_annotations_taroth_2023-03-06.pdf](https://github.com/SUSE/doc-modular/files/10901700/systemd-working-with-timers_annotations_taroth_2023-03-06.pdf)

2023-03-08 16:18 UTC, tomschr commented on DC-systemd-working-with-timers
> +MAIN="systemd_timer_working_with.xml"
Why? It shouldn't matter. If you are concerned about SEO, only the ID matters, not the file name. The file name isn't visible to the deliverable.

2023-03-09 13:59 UTC, taroth21 commented on DC-systemd-working-with-timers
> +MAIN="systemd_timer_working_with.xml"
But the root ID of an assembly has to match its file name - hence it is easier to use hyphens in file names as well, then you can simply c&p the file name to the root ID.

2023-03-10 05:58 UTC, tahliar reviewed
I tried to stay fairly high-level for this rather than looking at individual sentences. I didn't completely succeed, but such is life.

2023-03-10 05:58 UTC, tahliar commented on tasks/systemd-mailto.xml
> +    <title>Setting up e-mail notification for &systemd;</title>
I see three procedures in this guide, but only one has a title. I have no strong opinion on procedure titles vs. no procedure titles, but I think we should be consistent with whichever one we choose.

2023-03-10 05:58 UTC, tahliar commented on tasks/systemd-timer-test-cal-entries.xml
> +  </para>
```suggestion
    <abstract>
      <para>
        &systemd; provides a tool for testing and creating calendar timer entries for realtime
        timers: <command>systemd-analyze calendar</command>. It accepts the same argument
        as the <literal>OnCalendar</literal> entry required to set up realtime timers.
      </para>
    </abstract>
  </info>
```
This was a bit repetitive.

2023-03-10 05:58 UTC, tahliar commented on tasks/systemd-timer-troubleshoot.xml
> +      To avoid errors with &systemd; timers make sure to
IIRC, splitting up a sentence into a list like this can make translation more difficult? 

Side note: Capitalisation of the list items is inconsistent.

2023-03-10 05:58 UTC, tahliar commented on tasks/systemd-timer-user.xml
> +    and tasks as mentioned above are valid, however the following differences apply:
This abstract and para are also repetitive.

2023-03-10 05:58 UTC, tahliar commented on tasks/systemd-timer-troubleshoot.xml
> +      Migrating from cron to &systemd; timers is easy. Here is a general recipe on migrating a cron
I've mostly avoided any line editing so as to save some fun for Daria, but two things I couldn't ignore here: 

1. I don't think we should say that a task is easy, as that could frustrate a user who doesn't find it easy. 
2. Recipe? Are we cooking now? ;)

2023-03-10 05:58 UTC, tahliar commented on articles/systemd-timer-working-with.xml
> +       <title>Changelog</title>
Are change logs a thing we're going to start doing again? I assumed that was done away with because anyone can see the changes in GitHub.

2023-03-10 05:58 UTC, tahliar commented on articles/systemd-timer-working-with.xml
> +     <meta name="updated" content="2023-02-28"/>
How useful is this date? Presumably the topics themselves would be updated more often than the assembly file.

2023-03-10 15:54 UTC, fsundermeyer commented on tasks/systemd_timer_user.xml
> +    </listitem>
Good idea - although I would rather not like to add this _now_ without having more information on systemctl edit documented (it has some pitfalls).

2023-03-10 15:55 UTC, fsundermeyer commented on tasks/systemd_timer_troubleshoot.xml
> +    <title>Avoiding errors</title>
Renamed to Troubleshooting & FAQ

2023-03-10 16:03 UTC, fsundermeyer commented on tasks/systemd_timer_troubleshoot.xml
> +  <section>
Renamed to Troubleshooting & FAQs

2023-03-10 16:09 UTC, fsundermeyer commented on concepts/systemd-timer-concept.xml
> +    systemd timer units serve the same purpose as cron, they offer several advantages:
Done

2023-03-10 16:16 UTC, fsundermeyer commented on references/systemd_timer_manage.xml
> +&prompt.root;systemctl list-timers --all hello*</screen>
Done (moved example that was already there)

2023-03-10 16:16 UTC, fsundermeyer commented on DC-systemd-working-with-timers
> +MAIN="systemd_timer_working_with.xml"
done.

2023-03-10 16:17 UTC, fsundermeyer commented on concepts/systemd-timer-concept.xml
> +    Similar to cron, systemd timer units provide a mechanism for scheduling jobs on Linux. Although
done

2023-03-10 16:17 UTC, fsundermeyer commented on concepts/systemd-timer-concept.xml
> +    words, a timer file activates and manages the corresponding service file. For a full refernce
done

2023-03-10 16:18 UTC, fsundermeyer commented on DC-systemd-working-with-timers
> +MAIN="systemd_timer_working_with.xml"
done

2023-03-10 16:23 UTC, fsundermeyer commented on glues/systemd-timers-more-info.xml
> +  <title>For more information</title>
Totally agree, however, assemblies currently do not support this ATM (only an abstract is allowed).

2023-03-10 16:23 UTC, fsundermeyer commented on articles/systemd-timer-working-with.xml
> +         <title>Requirements</title>
@tomschr : This is for you.

2023-03-10 16:32 UTC, fsundermeyer commented on tasks/systemd-timer-user.xml
> +    and tasks as mentioned above are valid, however the following differences apply:
Fixed

2023-03-10 16:36 UTC, fsundermeyer commented on articles/systemd-timer-working-with.xml
> +     <meta name="updated" content="2023-02-28"/>
This date will be used in future to alert people of major changes in the article.

2023-03-10 16:37 UTC, fsundermeyer commented on articles/systemd_timer_working_with.xml
> +           <term>WHY</term>
Fixed

2023-03-10 16:38 UTC, fsundermeyer commented on articles/systemd_timer_working_with.xml
> +     <meta name="architecture" content="x86_64;zseries;power;aarch64"/>
Semicolon

2023-03-14 10:06 UTC, dariavladykina reviewed
Hi Frank, please see some suggestions, mainly for typos and spelling. Thanks!

2023-03-14 10:06 UTC, dariavladykina commented on tasks/systemd-mailto.xml
> +        in this example, because the service is guaranteed to run on any installation).
```suggestion
        To verify the complete procedure, start the service using the 
        <literal>dbus</literal> instance for testing. (You can use any other 
        service that is currently running. dbus is used in this example 
        because the service is guaranteed to run on any installation.)
```

2023-03-14 10:06 UTC, dariavladykina reviewed
Hi Frank, please see some suggestions, mainly for typos and spelling. Thanks!

2023-03-14 12:18 UTC, fsundermeyer commented on tasks/systemd-timer-create.xml
> +            &systemd; targets with systemctl</link>.
This is for PDFs only and intended--thus the link shows up when te PDF is printed.

2023-03-14 16:27 UTC, merged

2023-03-14 16:27 UTC, fsundermeyer commented
Thanks a lot for all the reviews!!